"""Exposed saved-artifact check, stdlib Fraction and original linear connection.

No parent calculations imported. Metric perturbation in saved artifact is input;
all derivatives are analytically obtained from cos(k.x) at zero. The separate
trace_samples are synthetic equation-generated numbers, not this metric's data.
"""
from fractions import Fraction as F
from pathlib import Path
import json, hashlib, sys, platform

base = Path(__file__).resolve().parent
source = base.parent/'SAVED_CONTROL.json'
saved = json.loads(source.read_text())
assert saved['metric_perturbation'] == 'h_ab=-(rho/3) eta_ab, rho=cos((5t-3x)/4)'
eta = [-1,1,1,1]
k = [F(5,4),F(-3,4),F(0),F(0)]


def hessian_h(a,b,c,d):
    # rho,cd(0)=-k_c k_d; h_ab=-rho eta_ab/3.
    return F(eta[a],3)*k[c]*k[d] if a==b else F(0)


def dgamma(a,b,c,d):
    return F(eta[a],2)*(hessian_h(a,c,b,d)+hessian_h(a,b,c,d)-hessian_h(b,c,a,d))


ric = [[sum((dgamma(a,b,c,a)-dgamma(a,b,a,c) for a in range(4)),F(0)) for c in range(4)] for b in range(4)]
saved_ric = [[F(q) for q in row] for row in saved['ricci']]
assert ric == saved_ric
scalar = sum((eta[a]*ric[a][a] for a in range(4)),F(0))
assert scalar == 1
# First-order Ricci at all x has the same coefficient times rho(x).
box_scalar = -scalar*sum((eta[a]*k[a]**2 for a in range(4)),F(0))
alpha_linear = F(saved['alpha'])
tensor = []
for a in range(4):
    for b in range(4):
        gab = eta[a] if a==b else 0
        hess_scalar = -scalar*k[a]*k[b]
        tensor.append(ric[a][b]-F(gab,2)*scalar+2*alpha_linear*(gab*box_scalar-hess_scalar))
assert tensor == [F(0)]*16
v = F(saved['speed'])
gamma = F(5,4)
assert gamma**2*(1-v*v) == 1
frames = [[F(1),F(0),F(0),F(0)]]
for i in range(1,4):
    for sign in [1,-1]:
        u=[gamma,F(0),F(0),F(0)]
        u[i]=sign*gamma*v
        frames.append(u)
contractions=[sum((u[a]*ric[a][b]*u[b] for a in range(4) for b in range(4)),F(0)) for u in frames]
assert contractions == [F(q) for q in saved['contractions']]
scalar_from_clocks=(1-v*v)*sum(contractions[1:])/(2*v*v)-(1+3/(v*v))*contractions[0]
assert scalar_from_clocks == scalar

# Catch a damaged input in memory without changing the preserved artifact.
damaged=[row[:] for row in saved_ric]
damaged[0][1]+=F(1,1000)
assert ric != damaged

records=[(F(row['R']),F(row['Box_R'])) for row in saved['trace_samples']]
(r1,q1),(r2,q2),(r3,q3)=records
alpha_synthetic=(r2-r1)/(6*(q2-q1))
lambda_synthetic=(r1-6*alpha_synthetic*q1)/4
assert alpha_synthetic==F(2,3) and lambda_synthetic==F(1,20)
assert 6*alpha_synthetic*q3-r3+4*lambda_synthetic==0
assert alpha_synthetic != alpha_linear

result={
 'status':'PASS_INDEPENDENT_STDLIB_SAVED_ARTIFACT_RECOMPUTATION',
 'versions':{'python':sys.version,'platform':platform.platform()},
 'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
 'metric_control':{'ricci':[[str(q) for q in row] for row in ric],'contractions':[str(q) for q in contractions],'R':str(scalar),'Box_R':str(box_scalar),'alpha':str(alpha_linear),'original_tensor_residuals':[str(q) for q in tensor]},
 'synthetic_affine_control':{'alpha':str(alpha_synthetic),'Lambda':str(lambda_synthetic),'third_point_residual':'0','provenance':'Generated by parent from stipulated affine trace equation; not independent geometry, not part of linear metric control'},
 'catch_check':'In-memory off-diagonal Ricci corruption rejected',
 'limits':'First-order control only; Fraction reconstruction is independent arithmetic implementation, not new physics or independently measured clocks. Equation-generated affine records check inverse arithmetic only.'
}
with (base/'SAVED_RECOMPUTATION.json').open('x') as f:
    json.dump(result,f,indent=2);f.write('\n')
print(json.dumps(result,indent=2))
