#!/usr/bin/env python3
"""Exact finite-dimensional checks for the reciprocal-root causal-flag follow-up audit.

Requires: sympy
Run:
    python verify_reciprocal_flag_followup.py

The script verifies:
  1. the founding two-channel exchange algebra and that the swap is not Lorentz-causal;
  2. the 3-dimensional abelianization of the (1,1,2)-flag parabolic Lie algebra;
  3. the line/plane/screen graded-volume character formulas;
  4. uniqueness of the exchange-odd normalized weight within those characters;
  5. the exact value on the lower-mixing example;
  6. failure of d(exp) blocks to compose, while the full Jacobi propagator does;
  7. an explicit higher-order metric-natural, torsion-free, non-metric connection family;
  8. the endpoint-scalar obstruction caused by nontrivial isotropy.
"""

from __future__ import annotations

import sympy as sp


def flatten_on_positions(matrix: sp.Matrix, positions: list[tuple[int, int]]) -> sp.Matrix:
    return sp.Matrix([matrix[i, j] for i, j in positions])


def christoffel_ricci_scalar(metric: sp.Matrix, coordinates: list[sp.Symbol]):
    """Return Christoffels, Ricci tensor and scalar curvature."""
    n = metric.rows
    inverse = sp.simplify(metric.inv())
    gamma = [[[sp.Integer(0) for _ in range(n)] for _ in range(n)] for _ in range(n)]
    for k in range(n):
        for i in range(n):
            for j in range(n):
                gamma[k][i][j] = sp.simplify(
                    sp.Rational(1, 2)
                    * sum(
                        inverse[k, ell]
                        * (
                            sp.diff(metric[ell, j], coordinates[i])
                            + sp.diff(metric[ell, i], coordinates[j])
                            - sp.diff(metric[i, j], coordinates[ell])
                        )
                        for ell in range(n)
                    )
                )

    ricci = sp.zeros(n)
    for i in range(n):
        for j in range(n):
            value = sp.Integer(0)
            for k in range(n):
                value += sp.diff(gamma[k][i][j], coordinates[k])
                value -= sp.diff(gamma[k][i][k], coordinates[j])
                for ell in range(n):
                    value += gamma[k][k][ell] * gamma[ell][i][j]
                    value -= gamma[k][j][ell] * gamma[ell][i][k]
            ricci[i, j] = sp.simplify(value)

    scalar = sp.simplify(
        sum(inverse[i, j] * ricci[i, j] for i in range(n) for j in range(n))
    )
    return gamma, ricci, scalar


def main() -> None:
    d = sp.symbols("d", real=True)

    # ------------------------------------------------------------------
    # 1. Founding reciprocal exchange algebra.
    # ------------------------------------------------------------------
    K = sp.Matrix([[0, 1], [1, 0]])
    eta2 = sp.diag(-1, 1)
    D = sp.diag(sp.exp(-d), sp.exp(d))

    assert sp.simplify(D.T * K * D - K) == sp.zeros(2)
    assert sp.simplify(K * D * K - sp.diag(sp.exp(d), sp.exp(-d))) == sp.zeros(2)
    assert sp.simplify(K.T * eta2 * K + eta2) == sp.zeros(2)

    print("1. Reciprocal-core algebra")
    print("   D(d)^T K D(d) = K")
    print("   K D(d) K = D(-d)")
    print("   K^T eta K = -eta, so K is an anti-isometry, not a Lorentz exchange.\n")

    # ------------------------------------------------------------------
    # 2. Lie-algebra abelianization of the flag parabolic.
    #    Allowed block-upper-triangular positions for blocks 1|1|2.
    # ------------------------------------------------------------------
    positions = [
        (0, 0), (0, 1), (0, 2), (0, 3),
        (1, 1), (1, 2), (1, 3),
        (2, 2), (2, 3),
        (3, 2), (3, 3),
    ]
    basis: list[sp.Matrix] = []
    for i, j in positions:
        E = sp.zeros(4)
        E[i, j] = 1
        basis.append(E)

    commutators: list[sp.Matrix] = []
    for X in basis:
        for Y in basis:
            commutators.append(flatten_on_positions(X * Y - Y * X, positions))

    comm_matrix = sp.Matrix.hstack(*commutators)
    comm_rank = comm_matrix.rank()
    assert len(positions) == 11
    assert comm_rank == 8
    assert len(positions) - comm_rank == 3

    f_clock = sp.Matrix([1 if pos == (0, 0) else 0 for pos in positions])
    f_ruler = sp.Matrix([1 if pos == (1, 1) else 0 for pos in positions])
    f_screen = sp.Matrix([1 if pos in {(2, 2), (3, 3)} else 0 for pos in positions])
    for functional in (f_clock, f_ruler, f_screen):
        assert comm_matrix.T * functional == sp.zeros(comm_matrix.cols, 1)
    assert sp.Matrix.hstack(f_clock, f_ruler, f_screen).rank() == 3

    print("2. Flag-parabolic abelianization")
    print(f"   dim(p) = {len(positions)}, dim([p,p]) = {comm_rank}, dim(p/[p,p]) = 3")
    print("   Basis functionals: X00, X11, X22+X33.")
    print("   Hence smooth real characters are generated by log|a|, log|b|, log|det C|.\n")

    # ------------------------------------------------------------------
    # 3. Graded line/plane/screen volumes on an isotropy matrix.
    # ------------------------------------------------------------------
    a, b, x = sp.symbols("a b x", nonzero=True, real=True)
    A2 = sp.Matrix([[a, x], [0, b]])
    gram2 = sp.simplify(A2.T * eta2 * A2)
    assert sp.simplify(gram2[0, 0] + a**2) == 0
    assert sp.simplify(sp.det(gram2) + (a * b) ** 2) == 0

    print("3. Isotropy graded volumes")
    print("   clock factor = |a|")
    print("   clock-ruler area factor = |ab| (independent of the shear x)")
    print("   screen factor = |det C|.\n")

    # Exact telescoping of line, plane, and four-volume factors for a
    # nontrivial pair of causal-flag arrows.  The identity itself is general:
    # the same target Gram determinant appears in the numerator on both sides.
    eta4_test = sp.diag(-1, 1, 1, 1)
    A_test = sp.Matrix(
        [
            [sp.Rational(1, 2), 0, 0, 0],
            [0, 2, 0, 0],
            [sp.Rational(1, 4), 0, 1, 0],
            [0, 0, 0, 1],
        ]
    )
    B_test = sp.Matrix(
        [
            [sp.Rational(3, 2), 0, 0, 0],
            [0, sp.Rational(2, 3), 0, 0],
            [sp.Rational(1, 10), 0, 1, 0],
            [0, sp.Rational(1, 8), 0, 1],
        ]
    )
    U = sp.eye(4)
    e0_test = U[:, 0]

    def gram_volume_sq(map_matrix: sp.Matrix, basis_matrix: sp.Matrix, k: int) -> sp.Expr:
        vectors = map_matrix * basis_matrix[:, :k]
        return sp.simplify(sp.Abs(sp.det(vectors.T * eta4_test * vectors)))

    for k in (1, 2, 4):
        source_sq = gram_volume_sq(sp.eye(4), U, k)
        after_a_sq = gram_volume_sq(A_test, U, k)
        after_ba_sq = gram_volume_sq(B_test * A_test, U, k)
        rho_a_sq = sp.simplify(after_a_sq / source_sq)
        rho_b_on_af_sq = sp.simplify(after_ba_sq / after_a_sq)
        rho_ba_sq = sp.simplify(after_ba_sq / source_sq)
        assert sp.simplify(rho_ba_sq - rho_b_on_af_sq * rho_a_sq) == 0

    assert ((B_test * A_test * e0_test).T * eta4_test * (B_test * A_test * e0_test))[0] < 0
    print("3a. Causal-flag volume telescoping")
    print("   rho_k(BA,F)^2 = rho_k(B,AF)^2 rho_k(A,F)^2 for k=1,2,4.")
    print("   The exact rational test keeps the transported clock line timelike.\n")

    # ------------------------------------------------------------------
    # 4. Exchange-odd normalized weight.
    # ------------------------------------------------------------------
    ct, cr, cs = sp.symbols("c_t c_r c_s", real=True)
    solution = sp.solve(
        [sp.Eq(cr, -ct), sp.Eq(cs, 0), sp.Eq(-ct + cr, 1)],
        [ct, cr, cs],
        dict=True,
    )
    assert solution == [{ct: -sp.Rational(1, 2), cr: sp.Rational(1, 2), cs: 0}]

    print("4. Formal channel exchange")
    print("   Exchange oddness: c_r=-c_t and c_s=0.")
    print("   D_t normalization: -c_t+c_r=1.")
    print("   Unique solution: (-1/2, +1/2, 0).\n")

    # ------------------------------------------------------------------
    # 5. Lower-mixing example from the source document.
    # ------------------------------------------------------------------
    eta4 = sp.diag(-1, 1, 1, 1)
    A = sp.Matrix(
        [
            [sp.Rational(1, 2), 0, 0, 0],
            [0, 2, 0, 0],
            [sp.Rational(1, 4), 0, 1, 0],
            [0, 0, 0, 1],
        ]
    )
    e0 = sp.Matrix([1, 0, 0, 0])
    e1 = sp.Matrix([0, 1, 0, 0])

    source_clock_sq = sp.Abs((e0.T * eta4 * e0)[0])
    target_clock_sq = sp.Abs(((A * e0).T * eta4 * (A * e0))[0])
    rho1_sq = sp.simplify(target_clock_sq / source_clock_sq)

    source_gram = sp.Matrix(
        [[(u.T * eta4 * v)[0] for v in (e0, e1)] for u in (e0, e1)]
    )
    target_vectors = (A * e0, A * e1)
    target_gram = sp.Matrix(
        [[(u.T * eta4 * v)[0] for v in target_vectors] for u in target_vectors]
    )
    rho2_sq = sp.simplify(sp.Abs(sp.det(target_gram)) / sp.Abs(sp.det(source_gram)))

    b1 = sp.log(sp.sqrt(rho1_sq))
    b2 = sp.log(sp.sqrt(rho2_sq))
    delta_rf = sp.simplify(sp.Rational(1, 2) * b2 - b1)
    expected = sp.log(sp.Rational(64, 3)) / 4
    assert sp.simplify(
        sp.expand_log(delta_rf, force=True) - sp.expand_log(expected, force=True)
    ) == 0

    print("5. Lower-mixing arrow")
    print("   rho_1^2 =", rho1_sq)
    print("   rho_2^2 =", rho2_sq)
    print("   delta_RF = log(64/3)/4 =", sp.N(expected, 14), "\n")

    # ------------------------------------------------------------------
    # 6. d(exp) does not compose; full Jacobi state propagation does.
    #    On curvature +1, the transverse d(exp) factor is sin(r)/r.
    # ------------------------------------------------------------------
    r = sp.pi / 6
    s = sp.pi / 6
    j_total = sp.simplify(sp.sin(r + s) / (r + s))
    j_product = sp.simplify((sp.sin(r) / r) * (sp.sin(s) / s))
    assert sp.simplify(j_total - j_product) != 0

    u, v = sp.symbols("u v", real=True)
    M = lambda z: sp.Matrix([[sp.cos(z), sp.sin(z)], [-sp.sin(z), sp.cos(z)]])
    assert sp.simplify(M(u + v) - M(v) * M(u)) == sp.zeros(2)

    print("6. Exponential/Jacobi composition")
    print("   d(exp) transverse factor at r+s:", j_total)
    print("   product of segment factors:", j_product)
    print("   They differ.")
    print("   The full 2x2 Jacobi fundamental matrix M(v)M(u)=M(u+v) exactly.\n")

    # ------------------------------------------------------------------
    # 7. Higher-order metric-natural non-metric connection family.
    #    g = -dt^2 + (1+t^2)^2 dx^2 + dy^2 + dz^2.
    #    Let S = Ric^sharp, alpha=dR, and
    #       nabla^(c)_X Y = nabla^g_X Y + c[alpha(X)S(Y)+alpha(Y)S(X)].
    #    This is torsion-free, natural, third order, and generally non-metric.
    # ------------------------------------------------------------------
    t, xcoord, ycoord, zcoord, c = sp.symbols("t x y z c", real=True)
    coordinates = [t, xcoord, ycoord, zcoord]
    scale = 1 + t**2
    metric = sp.diag(-1, scale**2, 1, 1)
    gamma, ricci, scalar = christoffel_ricci_scalar(metric, coordinates)
    expected_ricci = sp.diag(-2 / scale, 2 * scale, 0, 0)
    assert sp.simplify(ricci - expected_ricci) == sp.zeros(4)
    assert sp.simplify(scalar - 4 / scale) == 0

    S = sp.simplify(metric.inv() * ricci)
    assert sp.simplify(S - sp.diag(2 / scale, 2 / scale, 0, 0)) == sp.zeros(4)
    alpha0 = sp.diff(scalar, t)

    # Along the t-curve, e_t and e_y are LC-parallel.  The added connection
    # coefficient for e_t is 2*c*alpha0*S00; for e_y it is zero.
    added_clock_generator = sp.simplify(2 * c * alpha0 * S[0, 0])
    added_ruler_generator = sp.Integer(0)
    integral_clock = sp.simplify(sp.integrate(added_clock_generator, (t, 0, 1)))
    ell_clock = -integral_clock
    ell_ruler = -sp.integrate(added_ruler_generator, (t, 0, 1))
    delta_connection = sp.simplify((ell_ruler - ell_clock) / 2)

    assert integral_clock == -6 * c
    assert ell_clock == 6 * c
    assert delta_connection == -3 * c

    # One non-metricity component: Q_000 = (nabla^(c)_0 g)_{00}.
    # C^0_00=2*c*alpha0*S00 and g00=-1, so Q_000=-2*g00*C^0_00.
    Q000 = sp.simplify(-2 * metric[0, 0] * added_clock_generator)
    assert sp.simplify(Q000) != 0

    print("7. Higher-order natural connection counterfamily")
    print("   scalar curvature R =", scalar)
    print("   Ric^sharp =")
    sp.pprint(S)
    print("   For the t-y causal flag from t=0 to t=1:")
    print("   ell_clock =", ell_clock, ", ell_ruler =", ell_ruler)
    print("   delta_RF of its transport =", delta_connection)
    print("   c is arbitrary, proving metric-to-arrow nonuniqueness beyond first order.\n")

    # ------------------------------------------------------------------
    # 8. c_eff endpoint-scalar obstruction on the unscaled flag groupoid.
    # ------------------------------------------------------------------
    lambda_D = sp.exp(-2 * d)
    assert sp.simplify(lambda_D - 1) != 0

    print("8. Endpoint-scalar obstruction")
    print("   On the unscaled flag object, D_t is an isotropy arrow but")
    print("   exp[-2 delta_RF(D_t)] = exp(-2t) != 1.")
    print("   Therefore this character cannot be c_eff(target)/c_eff(source)")
    print("   on that object space without adding calibration state or killing periods.\n")

    print("All exact checks passed.")


if __name__ == "__main__":
    main()
