# ============================================================================
# DEPRECATED / INVALID OFF-ROUND -- DO NOT USE for shaped (off-round) matter.
# Found by blind verifier 7cf94053 (2026-06-16): this auto-generated 2-D matter
# Euler-Lagrange is WRONG in the L4 (Skyrme quartic) sector whenever the matter
# carries genuine ANGULAR deformation (Theta_theta != 0 and/or c,d != 0).  It is
# correct ONLY in the round limit (coincides with the true EL to 3e-16; that is
# why all round validations passed).  Correct 2-D EL: axisym_matter_el_CORRECT.py
# (direct variation, identity-consistent with the Hilbert stress).  Correct full-
# 3-D EL: matter_el_3d_gen.py (same direct-variation method; machine-zero on round;
# symbolic div(T) = -EL d_r Theta exact).  Kept for provenance only.  2026-06-16.
# ============================================================================
import numpy as np
from numpy import exp,sin,cos,sqrt

def matter_el_resid(r,theta,a,b,c,d,Th,a_r,b_r,c_r,d_r,Th_r,a_t,b_t,c_t,d_t,Th_t,a_rr,b_rr,c_rr,d_rr,Th_rr,a_tt,b_tt,c_tt,d_tt,Th_tt,a_rt,b_rt,c_rt,d_rt,Th_rt,xi,kappa):
    return (-1/2*Th_r**2*kappa*np.exp(-2*b - 2*c)*np.sin(2*Th)/r**2 - 1/2*Th_r**2*kappa*np.exp(-2*b - 2*d)*np.sin(2*Th)/r**2 + (1/2)*Th_r*a_r*kappa*np.exp(-2*b - 2*c)*np.cos(2*Th)/r**2 - 1/2*Th_r*a_r*kappa*np.exp(-2*b - 2*c)/r**2 + (1/2)*Th_r*a_r*kappa*np.exp(-2*b - 2*d)*np.cos(2*Th)/r**2 - 1/2*Th_r*a_r*kappa*np.exp(-2*b - 2*d)/r**2 - Th_r*a_r*xi*np.exp(-2*b) - 1/2*Th_r*b_r*kappa*np.exp(-2*b - 2*c)*np.cos(2*Th)/r**2 + (1/2)*Th_r*b_r*kappa*np.exp(-2*b - 2*c)/r**2 - 1/2*Th_r*b_r*kappa*np.exp(-2*b - 2*d)*np.cos(2*Th)/r**2 + (1/2)*Th_r*b_r*kappa*np.exp(-2*b - 2*d)/r**2 + Th_r*b_r*xi*np.exp(-2*b) - 1/2*Th_r*c_r*kappa*np.exp(-2*b - 2*c)*np.cos(2*Th)/r**2 + (1/2)*Th_r*c_r*kappa*np.exp(-2*b - 2*c)/r**2 + (1/2)*Th_r*c_r*kappa*np.exp(-2*b - 2*d)*np.cos(2*Th)/r**2 - 1/2*Th_r*c_r*kappa*np.exp(-2*b - 2*d)/r**2 - Th_r*c_r*xi*np.exp(-2*b) + (1/2)*Th_r*d_r*kappa*np.exp(-2*b - 2*c)*np.cos(2*Th)/r**2 - 1/2*Th_r*d_r*kappa*np.exp(-2*b - 2*c)/r**2 - 1/2*Th_r*d_r*kappa*np.exp(-2*b - 2*d)*np.cos(2*Th)/r**2 + (1/2)*Th_r*d_r*kappa*np.exp(-2*b - 2*d)/r**2 - Th_r*d_r*xi*np.exp(-2*b) - 2*Th_r*xi*np.exp(-2*b)/r + (1/2)*Th_rr*kappa*np.exp(-2*b - 2*c)*np.cos(2*Th)/r**2 - 1/2*Th_rr*kappa*np.exp(-2*b - 2*c)/r**2 + (1/2)*Th_rr*kappa*np.exp(-2*b - 2*d)*np.cos(2*Th)/r**2 - 1/2*Th_rr*kappa*np.exp(-2*b - 2*d)/r**2 - Th_rr*xi*np.exp(-2*b) - 1/2*Th_t**2*kappa*np.exp(-2*c - 2*d)*np.sin(2*Th)/r**4 + (1/2)*Th_t*a_t*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/r**4 - 1/2*Th_t*a_t*kappa*np.exp(-2*c - 2*d)/r**4 - Th_t*a_t*xi*np.exp(-2*c)/r**2 + (1/2)*Th_t*b_t*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/r**4 - 1/2*Th_t*b_t*kappa*np.exp(-2*c - 2*d)/r**4 - Th_t*b_t*xi*np.exp(-2*c)/r**2 - 1/2*Th_t*c_t*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/r**4 + (1/2)*Th_t*c_t*kappa*np.exp(-2*c - 2*d)/r**4 + Th_t*c_t*xi*np.exp(-2*c)/r**2 - 1/2*Th_t*d_t*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/r**4 + (1/2)*Th_t*d_t*kappa*np.exp(-2*c - 2*d)/r**4 - Th_t*d_t*xi*np.exp(-2*c)/r**2 + (1/2)*Th_t*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/(r**4*np.tan(theta)) - 1/2*Th_t*kappa*np.exp(-2*c - 2*d)/(r**4*np.tan(theta)) - Th_t*xi*np.exp(-2*c)/(r**2*np.tan(theta)) + (1/2)*Th_tt*kappa*np.exp(-2*c - 2*d)*np.cos(2*Th)/r**4 - 1/2*Th_tt*kappa*np.exp(-2*c - 2*d)/r**4 - Th_tt*xi*np.exp(-2*c)/r**2 + (1/2)*kappa*np.exp(-2*c - 2*d)*np.sin(2*Th)/r**4 - 1/4*kappa*np.exp(-2*c - 2*d)*np.sin(4*Th)/r**4 + (1/2)*xi*np.exp(-2*d)*np.sin(2*Th)/r**2 + (1/2)*xi*np.exp(-2*c)*np.sin(2*Th)/r**2)
