#!/usr/bin/env python3
"""AUTO-GENERATED by gen_einstein_3d_weyl.py. Mixed Einstein G^mu_nu for
the static diagonal 3-D Weyl metric. torch-evaluable. DO NOT EDIT."""
import torch
def Gmix_components(r, theta, a,a_r,a_t,a_p,a_rr,a_tt,a_pp,a_rt,a_rp,a_tp,
                    b,b_r,b_t,b_p,b_rr,b_tt,b_pp,b_rt,b_rp,b_tp,
                    c,c_r,c_t,c_p,c_rr,c_tt,c_pp,c_rt,c_rp,c_tp,
                    d,d_r,d_t,d_p,d_rr,d_tt,d_pp,d_rt,d_rp,d_tp):
    exp=torch.exp; sin=torch.sin; cos=torch.cos; tan=torch.tan
    out=[]
    G_0_0 = -1/2*a_t*exp(-2*c)*tan(theta)/r**2 - 1/2*a_t*exp(-2*c)/(r**2*tan(theta)) + a_t*exp(-2*c)/(r**2*sin(2*theta)) + 2*b_p**2*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*b_p*c_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - 2*b_p*d_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*b_pp*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - b_r*c_r*exp(-2*b) - b_r*d_r*exp(-2*b) - 2*b_r*exp(-2*b)/r + b_t**2*exp(-2*c)/r**2 - b_t*c_t*exp(-2*c)/r**2 + b_t*d_t*exp(-2*c)/r**2 - 1/2*b_t*exp(-2*c)*tan(theta)/r**2 + (1/2)*b_t*exp(-2*c)/(r**2*tan(theta)) + b_t*exp(-2*c)/(r**2*sin(2*theta)) + b_tt*exp(-2*c)/r**2 + 2*c_p**2*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - 2*c_p*d_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*c_pp*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + c_r**2*exp(-2*b) + c_r*d_r*exp(-2*b) + 3*c_r*exp(-2*b)/r + c_rr*exp(-2*b) - c_t*d_t*exp(-2*c)/r**2 + (1/2)*c_t*exp(-2*c)*tan(theta)/r**2 - 1/2*c_t*exp(-2*c)/(r**2*tan(theta)) - c_t*exp(-2*c)/(r**2*sin(2*theta)) + d_r**2*exp(-2*b) + 3*d_r*exp(-2*b)/r + d_rr*exp(-2*b) + d_t**2*exp(-2*c)/r**2 - 3/2*d_t*exp(-2*c)*tan(theta)/r**2 + (1/2)*d_t*exp(-2*c)/(r**2*tan(theta)) + 3*d_t*exp(-2*c)/(r**2*sin(2*theta)) + d_tt*exp(-2*c)/r**2 - exp(-2*c)/r**2 + exp(-2*b)/r**2
    G_0_1 = 0
    G_0_2 = 0
    G_0_3 = 0
    G_1_0 = 0
    G_1_1 = (2*a_p**2*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + 2*a_p*c_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) - 2*a_p*d_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + 2*a_pp*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + a_r*c_r*r**2*exp(2*c) + a_r*d_r*r**2*exp(2*c) + 2*a_r*r*exp(2*c) + a_t**2*exp(2*b) - a_t*c_t*exp(2*b) + a_t*d_t*exp(2*b) - 1/2*a_t*exp(2*b)*tan(theta) + (1/2)*a_t*exp(2*b)/tan(theta) + a_t*exp(2*b)/sin(2*theta) + a_tt*exp(2*b) - 1/2*b_t*exp(2*b)*tan(theta) - 1/2*b_t*exp(2*b)/tan(theta) + b_t*exp(2*b)/sin(2*theta) + 2*c_p**2*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) - 2*c_p*d_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + 2*c_pp*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + c_r*d_r*r**2*exp(2*c) + c_r*r*exp(2*c) - c_t*d_t*exp(2*b) + (1/2)*c_t*exp(2*b)*tan(theta) - 1/2*c_t*exp(2*b)/tan(theta) - c_t*exp(2*b)/sin(2*theta) + d_r*r*exp(2*c) + d_t**2*exp(2*b) - 3/2*d_t*exp(2*b)*tan(theta) + (1/2)*d_t*exp(2*b)/tan(theta) + 3*d_t*exp(2*b)/sin(2*theta) + d_tt*exp(2*b) - exp(2*b) + exp(2*c))*exp(-2*b - 2*c)/r**2
    G_1_2 = (-a_r*a_t*r + a_r*b_t*r - a_rt*r + a_t*c_r*r + a_t + b_t*d_r*r + b_t + c_r*d_t*r + c_r*r/tan(theta) - d_r*d_t*r - d_r*r/tan(theta) - d_rt*r)*exp(-2*b)/r
    G_1_3 = (a_p*(d_r*r + 1) + b_p*(c_r*r + 1) - c_p*(c_r*r + 1) + c_p*(d_r*r + 1) + r*(-a_p*a_r + a_r*b_p - a_rp - c_rp))*exp(-2*b)/r
    G_2_0 = 0
    G_2_1 = (-a_r*a_t*r + a_r*b_t*r - a_rt*r + a_t*c_r*r + a_t + b_t*d_r*r + b_t + c_r*d_t*r + c_r*r/tan(theta) - d_r*d_t*r - d_r*r/tan(theta) - d_rt*r)*exp(-2*c)/r**3
    G_2_2 = 2*a_p**2*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*a_p*b_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - 2*a_p*d_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*a_pp*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + a_r**2*exp(-2*b) - a_r*b_r*exp(-2*b) + a_r*d_r*exp(-2*b) + a_r*exp(-2*b)/r + a_rr*exp(-2*b) + a_t*b_t*exp(-2*c)/r**2 + a_t*d_t*exp(-2*c)/r**2 - 1/2*a_t*exp(-2*c)*tan(theta)/r**2 + (1/2)*a_t*exp(-2*c)/(r**2*tan(theta)) + a_t*exp(-2*c)/(r**2*sin(2*theta)) + 2*b_p**2*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - 2*b_p*d_p*exp(-2*d)/(-r**2*cos(2*theta) + r**2) + 2*b_pp*exp(-2*d)/(-r**2*cos(2*theta) + r**2) - b_r*d_r*exp(-2*b) - b_r*exp(-2*b)/r + b_t*d_t*exp(-2*c)/r**2 - 1/2*b_t*exp(-2*c)*tan(theta)/r**2 + (1/2)*b_t*exp(-2*c)/(r**2*tan(theta)) + b_t*exp(-2*c)/(r**2*sin(2*theta)) + (1/2)*c_t*exp(-2*c)*tan(theta)/r**2 + (1/2)*c_t*exp(-2*c)/(r**2*tan(theta)) - c_t*exp(-2*c)/(r**2*sin(2*theta)) + d_r**2*exp(-2*b) + 2*d_r*exp(-2*b)/r + d_rr*exp(-2*b) - 3/2*d_t*exp(-2*c)*tan(theta)/r**2 - 3/2*d_t*exp(-2*c)/(r**2*tan(theta)) + 3*d_t*exp(-2*c)/(r**2*sin(2*theta))
    G_2_3 = (-a_p*a_t + a_p*d_t + a_p/tan(theta) + a_t*c_p - a_tp - b_p*b_t + b_p*d_t + b_p/tan(theta) + b_t*c_p - b_tp)*exp(-2*c)/r**2
    G_3_0 = 0
    G_3_1 = (a_p*(d_r*r + 1) + b_p*(c_r*r + 1) - c_p*(c_r*r + 1) + c_p*(d_r*r + 1) + r*(-a_p*a_r + a_r*b_p - a_rp - c_rp))*exp(-2*d)/(r**3*sin(theta)**2)
    G_3_2 = (-a_p*a_t + a_p*d_t + a_p/tan(theta) + a_t*c_p - a_tp - b_p*b_t + b_p*d_t + b_p/tan(theta) + b_t*c_p - b_tp)*exp(-2*d)/(r**2*sin(theta)**2)
    G_3_3 = (2*a_p*b_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + 2*a_p*c_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) + a_r**2*r**2*exp(2*c) - a_r*b_r*r**2*exp(2*c) + a_r*c_r*r**2*exp(2*c) + a_r*r*exp(2*c) + a_rr*r**2*exp(2*c) + a_t**2*exp(2*b) + a_t*b_t*exp(2*b) - a_t*c_t*exp(2*b) + (1/2)*a_t*exp(2*b)*tan(theta) + (1/2)*a_t*exp(2*b)/tan(theta) - a_t*exp(2*b)/sin(2*theta) + a_tt*exp(2*b) + 2*b_p*c_p*exp(2*b + 2*c - 2*d)/(1 - cos(2*theta)) - b_r*c_r*r**2*exp(2*c) - b_r*r*exp(2*c) + b_t**2*exp(2*b) - b_t*c_t*exp(2*b) + (1/2)*b_t*exp(2*b)*tan(theta) + (1/2)*b_t*exp(2*b)/tan(theta) - b_t*exp(2*b)/sin(2*theta) + b_tt*exp(2*b) + c_r**2*r**2*exp(2*c) + 2*c_r*r*exp(2*c) + c_rr*r**2*exp(2*c) - 1/2*c_t*exp(2*b)*tan(theta) - 1/2*c_t*exp(2*b)/tan(theta) + c_t*exp(2*b)/sin(2*theta) + (3/2)*d_t*exp(2*b)*tan(theta) + (3/2)*d_t*exp(2*b)/tan(theta) - 3*d_t*exp(2*b)/sin(2*theta))*exp(-2*b - 2*c)/r**2
    return [[G_0_0,G_0_1,G_0_2,G_0_3],
            [G_1_0,G_1_1,G_1_2,G_1_3],
            [G_2_0,G_2_1,G_2_2,G_2_3],
            [G_3_0,G_3_1,G_3_2,G_3_3]]
