#!/usr/bin/env python3
"""
export_for_local_llm.py -- the LOCAL-LLM CROSS-CHECK EXPORT GATE
(Part C cadence of COGNITIVE_CORRAL_TRIGGERS_SETUP.md).

Builds the payload to feed a second model (the cross-check / adversarial reader, to be installed later)
and ENFORCES the freshness + allowed-lane invariants so the second model is never fed contradictory
stale frontier claims or a forbid-only ruleset.

THE GATE (refuses to export unless ALL hold):
  1. The payload carries the full DURABLE corral (CLAUDE.md principles + DRIVER TRIGGERS + every memory
     tagged [DURABLE]) + only CURRENT frontier (LIVE.md + memories tagged [CURRENT]) -- NEVER memories
     tagged [SUPERSEDED] / [HISTORICAL].
  2. The ALLOWED-LANE clause (category-A technique / GR-as-reference always GREEN) is present VERBATIM --
     NON-DROPPABLE.  A second model given only the "forbid" half over-blocks (flags every legitimate JFNK
     / continuation / Schwarzschild-limit as a violation) and becomes a brake.  If the clause is missing,
     the export ABORTS.
  3. NO untagged DATED (project/frontier) memory may ride along -- a DATED memory with no
     [CURRENT]/[SUPERSEDED]/[HISTORICAL]/[CONFLICT] tag is a freshness FAILURE and ABORTS the export
     (forces the Part-C freshness pass to be complete first).

PROVENANCE/HONESTY only, never MERIT: the gate decides what is CURRENT + TAGGED, never what is right.

Usage:  python3 export_for_local_llm.py            # validate + write local_llm_export.md
        python3 export_for_local_llm.py --check    # validate only (exit 1 on any gate failure)
"""
import os
import re
import sys
import glob

REPO = os.path.dirname(os.path.abspath(__file__))
MEMDIR = os.path.expanduser(
    "~/.claude/projects/-home-udt-admin-udt-mass-codex/memory")
LIVE = os.path.join(REPO, "LIVE.md")
CLAUDEMD = os.path.join(REPO, "CLAUDE.md")
OUT = os.path.join(REPO, "local_llm_export.md")

DURABLE_TYPES = ("user", "feedback")          # always-durable metadata types
TAG_RE = re.compile(r"\*\*\[(DURABLE|CURRENT|SUPERSEDED|HISTORICAL|CONFLICT)\b", re.I)
TYPE_RE = re.compile(r"^\s*type:\s*(\w+)", re.M)
# the non-droppable lane marker, present verbatim in CLAUDE.md ## DRIVER TRIGGERS
LANE_ANCHOR = "LEAVES ROOM FOR THE WORK"
LANE_KEY = "CATEGORY-A"


def _read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def _frontmatter_type(body):
    m = TYPE_RE.search(body)
    return (m.group(1).lower() if m else "")


def _tag(body):
    m = TAG_RE.search(body)
    return (m.group(1).upper() if m else None)


def _extract_lane(claudemd):
    """Pull the allowed-lane clause verbatim from CLAUDE.md (anchor -> next blank-line-then-heading)."""
    i = claudemd.find(LANE_ANCHOR)
    if i < 0:
        return None
    # from the line containing the anchor to the start of the numbered trigger list ("Each: ")
    j = claudemd.find("Each: **TRIGGER**", i)
    seg = claudemd[i:j] if j > i else claudemd[i:i + 2000]
    return seg.strip() if LANE_KEY in seg else None


def build():
    problems = []
    # --- the non-droppable allowed-lane clause ---
    claudemd = _read(CLAUDEMD)
    lane = _extract_lane(claudemd)
    if not lane:
        problems.append("ABORT: the allowed-lane clause (CATEGORY-A always-green) is MISSING from "
                        "CLAUDE.md ## DRIVER TRIGGERS -- it is NON-DROPPABLE for the cross-check payload.")

    # --- classify every memory; refuse untagged DATED ---
    include, excluded, conflicts = [], [], []
    for path in sorted(glob.glob(os.path.join(MEMDIR, "*.md"))):
        name = os.path.basename(path)
        if name == "MEMORY.md":
            continue
        body = _read(path)
        mtype = _frontmatter_type(body)
        tag = _tag(body)
        durable = (mtype in DURABLE_TYPES) or (tag == "DURABLE")
        if durable:
            include.append((name, body))
        elif tag == "CURRENT":
            include.append((name, body))
        elif tag in ("SUPERSEDED", "HISTORICAL"):
            excluded.append((name, tag))
        elif tag == "CONFLICT":
            conflicts.append(name)
            problems.append(f"ABORT: {name} is tagged CONFLICT -- unresolved; resolve with Charles "
                            f"before exporting.")
        else:
            problems.append(f"ABORT: DATED memory {name} (type={mtype or '?'}) carries NO freshness tag "
                            f"-- run the Part-C freshness pass before exporting.")

    if problems:
        print("EXPORT GATE: FAILED\n  " + "\n  ".join(problems), file=sys.stderr)
        print(f"  ({len(include)} would-include, {len(excluded)} excluded-stale, "
              f"{len(conflicts)} conflicts)", file=sys.stderr)
        return None

    # --- assemble the payload ---
    parts = [
        "# LOCAL-LLM CROSS-CHECK EXPORT (udt_mass_codex)\n",
        "> Generated by export_for_local_llm.py. PROVENANCE/HONESTY cross-check payload: the DURABLE\n"
        "> cognitive corral + ONLY the CURRENT frontier + the NON-DROPPABLE allowed-lane clause. Stale\n"
        "> (SUPERSEDED/HISTORICAL) memories are excluded. The second model checks for SMUGGLED PHYSICS /\n"
        "> IMPOSED answers, NEVER judges whether a result is the 'right' shape (merit-never).\n",
        "\n## *** NON-DROPPABLE: THE ALLOWED LANE (read before flagging anything) ***\n\n" + lane + "\n",
        "\n## CLAUDE.md — principles + DRIVER TRIGGERS (the durable corral)\n\n" + claudemd + "\n",
        "\n## LIVE.md — the CURRENT frontier (source of truth)\n\n" + _read(LIVE) + "\n",
        "\n## DURABLE + CURRENT memories\n",
    ]
    for name, body in include:
        parts.append(f"\n### {name}\n\n{body}\n")
    parts.append(f"\n---\n_Excluded as stale: {', '.join(n for n, _ in excluded) or '(none)'}_\n")
    payload = "".join(parts)
    return payload, include, excluded


def main():
    check_only = "--check" in sys.argv
    res = build()
    if res is None:
        sys.exit(1)
    payload, include, excluded = res
    print(f"EXPORT GATE: PASSED -- {len(include)} memories included (DURABLE+CURRENT), "
          f"{len(excluded)} excluded as stale. Allowed-lane clause present.")
    if not check_only:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(payload)
        print(f"  wrote {OUT} ({len(payload)} chars)")
    sys.exit(0)


if __name__ == "__main__":
    main()
