#!/usr/bin/env python3
"""
gen_einstein_3d_weyl.py -- AUTO-GENERATE the analytic mixed Einstein tensor G^mu_nu
for the STATIC DIAGONAL 3-D Weyl metric

  ds^2 = -e^{2a} dt^2 + e^{2b} dr^2 + e^{2c} r^2 dtheta^2 + e^{2d} r^2 sin^2 th dpsi^2

with a,b,c,d = a,b,c,d(r,theta,psi) (FULL 3-D, psi LIVE, NO axisymmetry).

WHY (category-A conditioning, same cure as the validated 2-D axisym_einstein_analytic):
A purely-numerical NR Einstein engine differentiating the raw spherical metric does
NOT numerically cancel the coordinate-pole cot(theta)/(1/sin^2 theta) structure --
the residual GROWS with resolution near the GL poles (flat space != 0 numerically).
The cure used and validated in 2-D: derive G^mu_nu ANALYTICALLY (sympy cancels the
cot/1/sin terms symbolically into finite expressions), then evaluate ONLY the SMOOTH
warp derivatives a,b,c,d spectrally.  This is the SAME native Einstein content as the
numerical core (charter principle 4: transformed GR numerics), specialized to the
diagonal-Weyl class and made pole-stable.  We EXTEND the 2-D generator to carry psi.

OUTPUT: einstein_3d_weyl_gen.py with Gmix_components(...) returning the 4x4 mixed G
as torch-evaluable expressions in the warps and their 1st/2nd partials (r,th,ps).

VALIDATION (run at bottom): flat (a=b=c=d=0) -> G=0 EXACTLY (symbolic); Schwarzschild
(a=-b=0.5 ln(1-2M/r), c=d=0, th/ps-independent) -> G=0 EXACTLY (symbolic).
"""
import sympy as sp

t, r, th, ps = sp.symbols('t r theta psi', real=True)
xi, kap = sp.symbols('xi kappa', positive=True)

# warps as functions of (r,theta,psi)
a = sp.Function('a')(r, th, ps)
b = sp.Function('b')(r, th, ps)
c = sp.Function('c')(r, th, ps)
d = sp.Function('d')(r, th, ps)

sin, cos, exp = sp.sin, sp.cos, sp.exp

g = sp.zeros(4, 4)
g[0, 0] = -exp(2*a)
g[1, 1] = exp(2*b)
g[2, 2] = exp(2*c)*r**2
g[3, 3] = exp(2*d)*r**2*sin(th)**2
ginv = g.inv()

coords = [t, r, th, ps]

# Christoffel
print("building Christoffel...")
Gamma = [[[sp.S(0)]*4 for _ in range(4)] for _ in range(4)]
for l in range(4):
    for m in range(4):
        for n in range(4):
            s = sp.S(0)
            for k in range(4):
                s += ginv[l, k]*(sp.diff(g[k, m], coords[n])
                                 + sp.diff(g[k, n], coords[m])
                                 - sp.diff(g[m, n], coords[k]))
            Gamma[l][m][n] = sp.simplify(s/2)

# Ricci  R_{mn} = d_l G^l_{mn} - d_n G^l_{ml} + G^l_{lk}G^k_{mn} - G^l_{nk}G^k_{ml}
print("building Ricci...")
Ric = sp.zeros(4, 4)
for m in range(4):
    for n in range(4):
        s = sp.S(0)
        for l in range(4):
            s += sp.diff(Gamma[l][m][n], coords[l]) - sp.diff(Gamma[l][m][l], coords[n])
            for k in range(4):
                s += Gamma[l][l][k]*Gamma[k][m][n] - Gamma[l][n][k]*Gamma[k][m][l]
        Ric[m, n] = s

Rscal = sp.S(0)
for m in range(4):
    for n in range(4):
        Rscal += ginv[m, n]*Ric[m, n]

print("building mixed Einstein G^m_n ...")
Gmn = Ric - sp.Rational(1, 2)*g*Rscal
Gmix = sp.zeros(4, 4)
for m in range(4):
    for n in range(4):
        s = sp.S(0)
        for k in range(4):
            s += ginv[m, k]*Gmn[k, n]
        Gmix[m, n] = s

# substitute the cot/sin structure and lower the function-derivatives to plain symbols
print("lowering to codegen symbols (this simplifies the cot/1/sin terms)...")

# build replacement: a -> A, a_r -> A_r, etc. for each warp and each partial up to 2nd
subs = {}
names = {a: 'a', b: 'b', c: 'c', d: 'd'}
plain = {}
for f, nm in names.items():
    A = sp.Symbol(nm)
    Ar = sp.Symbol(nm+'_r'); At = sp.Symbol(nm+'_t'); Ap = sp.Symbol(nm+'_p')
    Arr = sp.Symbol(nm+'_rr'); Att = sp.Symbol(nm+'_tt'); App = sp.Symbol(nm+'_pp')
    Art = sp.Symbol(nm+'_rt'); Arp = sp.Symbol(nm+'_rp'); Atp = sp.Symbol(nm+'_tp')
    subs[sp.diff(f, r, r)] = Arr
    subs[sp.diff(f, th, th)] = Att
    subs[sp.diff(f, ps, ps)] = App
    subs[sp.diff(f, r, th)] = Art
    subs[sp.diff(f, r, ps)] = Arp
    subs[sp.diff(f, th, ps)] = Atp
    subs[sp.diff(f, r)] = Ar
    subs[sp.diff(f, th)] = At
    subs[sp.diff(f, ps)] = Ap
    subs[f] = A

print("simplify + substitute each component ...")
exprs = {}
for m in range(4):
    for n in range(4):
        e = sp.simplify(Gmix[m, n])
        e = e.subs(subs)
        exprs[(m, n)] = e

# emit a torch-evaluable module
lines = []
lines.append('#!/usr/bin/env python3')
lines.append('"""AUTO-GENERATED by gen_einstein_3d_weyl.py. Mixed Einstein G^mu_nu for')
lines.append('the static diagonal 3-D Weyl metric. torch-evaluable. DO NOT EDIT."""')
lines.append('import torch')
lines.append('def Gmix_components(r, theta, a,a_r,a_t,a_p,a_rr,a_tt,a_pp,a_rt,a_rp,a_tp,')
lines.append('                    b,b_r,b_t,b_p,b_rr,b_tt,b_pp,b_rt,b_rp,b_tp,')
lines.append('                    c,c_r,c_t,c_p,c_rr,c_tt,c_pp,c_rt,c_rp,c_tp,')
lines.append('                    d,d_r,d_t,d_p,d_rr,d_tt,d_pp,d_rt,d_rp,d_tp):')
lines.append('    exp=torch.exp; sin=torch.sin; cos=torch.cos; tan=torch.tan')
lines.append('    out=[]')

from sympy.printing.pycode import pycode
for m in range(4):
    for n in range(4):
        e = exprs[(m, n)]
        code = pycode(e, fully_qualified_modules=False)
        # map math.* / sympy print to torch
        code = code.replace('math.exp', 'exp').replace('math.sin', 'sin')
        code = code.replace('math.cos', 'cos').replace('math.tan', 'tan')
        code = code.replace('exp(', 'exp(').replace('theta', 'theta')
        lines.append(f'    G_{m}_{n} = {code}')
lines.append('    return [[G_0_0,G_0_1,G_0_2,G_0_3],')
lines.append('            [G_1_0,G_1_1,G_1_2,G_1_3],')
lines.append('            [G_2_0,G_2_1,G_2_2,G_2_3],')
lines.append('            [G_3_0,G_3_1,G_3_2,G_3_3]]')

with open('einstein_3d_weyl_gen.py', 'w') as f:
    f.write('\n'.join(lines)+'\n')
print("wrote einstein_3d_weyl_gen.py")

# --- symbolic validation ---
print("\n=== symbolic validation ===")
flat = {a: 0, b: 0, c: 0, d: 0}
# need derivatives zero too: substitute the function by 0 everywhere -> derivs 0
def check_flat():
    mx = sp.S(0)
    for m in range(4):
        for n in range(4):
            e = Gmix[m, n].subs({a: sp.S(0), b: sp.S(0), c: sp.S(0), d: sp.S(0)})
            e = sp.simplify(e)
            if e != 0:
                print(f"  FLAT G^{m}_{n} = {e}")
                mx = e
    return mx
fm = check_flat()
print("flat-space residual:", "0 (PASS)" if fm == 0 else fm)
