def main() -> None:
    print("H1 source localization criterion")
    print("=" * 35)
    print("There are two exact ways an H1 source can enter.")
    print()
    print("Collar density:")
    print("  source term appears in the radial equation")
    print("  f'' + 2f'/r + 2s(r)f/r^2 = 0")
    print("  It acts on every linking S2 through the collar.")
    print()
    print("Localized shell:")
    print("  source appears as a distribution at phi0")
    print("  f'' contains Delta f' delta(r-R)")
    print("  It changes the boundary momentum jump.")
    print()
    print("Localization criterion:")
    print("  If the H1 angular structure is transported as data on each")
    print("  linking S2, it is a collar-density candidate.")
    print("  If it exists only as a matching/jump condition at F=1,")
    print("  it is a shell candidate.")
    print()
    print("No-approximation verdict:")
    print("  The normalized H1 spectrum is collar-constant, but source")
    print("  localization depends on whether the H1 data lives through the")
    print("  collar or only at the phi0 interface.")


if __name__ == "__main__":
    main()
