def main() -> None:
    print("q stationarity requirement")
    print("=" * 27)
    print("C1 radial action in f:")
    print("  S_C1 = (1/4) integral r^2 f'^2 dr")
    print()
    print("Variation gives the boundary term:")
    print("  delta S_C1,boundary = Pi_F delta F")
    print("  Pi_F = (1/2) R^2 f'(R)")
    print()
    print("There is no independent delta q boundary term in this first-order")
    print("variational problem.")
    print()
    print("Therefore a local boundary functional S_b(F,n) can cancel Pi_F")
    print("but cannot by itself impose stationarity with respect to q.")
    print()
    print("To select q locally, one of the following must be true:")
    print("  1. the boundary functional depends on slope/extrinsic-curvature data;")
    print("  2. the variational principle is rewritten in phase-space form;")
    print("  3. q is selected by a collar bulk/self-consistency equation instead.")
    print()
    print("No-approximation verdict:")
    print("  Direct q selection is not supplied by the ordinary C1 endpoint")
    print("  variation. The current native route is collar self-consistency")
    print("  unless a genuine slope/joint boundary term is derived.")


if __name__ == "__main__":
    main()
