def main() -> None:
    print("phi0 boundary value/derivative split")
    print("=" * 43)
    print("Let F=f(phi0) and let a denote angular boundary data.")
    print()
    print("The most general local expansion near F=1 is:")
    print("  S_b(F,a) = S_0[a] + S_1[a](F-1) + O((F-1)^2)")
    print()
    print("C1 momentum closure fixes only:")
    print("  S_1[a] = q/2")
    print("or, after H1/S2 projection:")
    print("  <S_1,ab> = (q/6) delta_ab")
    print()
    print("For banked P_phi0:")
    print("  q = 1/3")
    print("  q/2 = 1/6")
    print("  eta = q/6 = 1/18")
    print()
    print("But the transfer exponential depends on the angular quadratic")
    print("operator contained in S_0[a], not merely on S_1.")
    print()
    print("Therefore:")
    print("  S_0[a] = (eta/2) <a, I_3 a>       gives 3 exp(-eta/2)")
    print("  S_0[a] = (eta B/2) <a, I_3 a>     gives 3 exp(-eta B/2)")
    print()
    print("No-approximation verdict:")
    print("  The scalar phi0 momentum scale eta is exact once q is fixed.")
    print("  The angular transfer operator is not fixed by that derivative alone.")


if __name__ == "__main__":
    main()
