def main() -> None:
    print("curvature-share action no-go")
    print("=" * 30)
    print("Tempting native scalar through the collar:")
    print("  A[f] = R3/R2 = 1 - f - r f'")
    print()
    print("Tempting action-density contribution:")
    print("  V_A = A[f] f^2 / 6")
    print("  L_A = -V_A")
    print()
    print("Exact Euler-Lagrange contribution from L_A:")
    print("  dL_A/df - d/dr(dL_A/df') = f(f-1)/3")
    print()
    print("Equivalent total-derivative decomposition:")
    print("  L_A = -(1-f-r f')f^2/6")
    print("      = total derivative + (-f^2/6 + f^3/9)")
    print()
    print("Therefore:")
    print("  the explicit q-bearing derivative part is absorbed into a boundary term")
    print("  and the remaining collar variation is f(f-1)/3, not (q/3)f.")
    print()
    print("At phi0:")
    print("  f=1")
    print("  f(f-1)/3 = 0")
    print()
    print("No-go verdict:")
    print("  The raw curvature-share scalar A=R3/R2 is a real metric ingredient,")
    print("  but placing A f^2/6 into an ordinary scalar collar action does not")
    print("  derive s(q)=q/3. The missing object must be more than this scalar")
    print("  curvature-share coefficient.")


if __name__ == "__main__":
    main()
