def main() -> None:
    print("activation action requirements")
    print("=" * 32)
    print("To produce the radial source equation:")
    print("  f'' + 2f'/r + 2s(q) f/r^2 = 0")
    print()
    print("an action term must contribute to the Euler-Lagrange equation as:")
    print("  + 2s(q) f/r^2")
    print()
    print("Equivalently, after multiplying by r^2:")
    print("  radial equation source term = 2s(q) f")
    print()
    print("For s(q)=q/3, the required contribution is:")
    print("  (2q/3) f")
    print()
    print("A boundary-only term S_b(F,n) cannot produce this collar bulk source.")
    print("It can only change endpoint momentum/value conditions.")
    print()
    print("Therefore s(q)=q/3 requires one of:")
    print("  1. a collar-local action density proportional to q times H1 share;")
    print("  2. a phase-space/slope boundary term whose variation is equivalent")
    print("     to such a collar source;")
    print("  3. a derived reduction where eliminating H1 collar data induces the source.")
    print()
    print("No-approximation verdict:")
    print("  The activation law cannot be derived from the existing endpoint-only")
    print("  H1 boundary skeleton. It needs a collar action or a slope/joint action.")


if __name__ == "__main__":
    main()
