def main() -> None:
    print("collar action source test")
    print("=" * 25)
    print("Use the radial variational form:")
    print("  S = integral [1/4 r^2 f'^2 - V(f,r)] dr")
    print()
    print("Euler-Lagrange equation:")
    print("  (1/2 r^2 f')' + dV/df = 0")
    print()
    print("Equivalent radial equation:")
    print("  f'' + 2f'/r + 2(dV/df)/r^2 = 0")
    print()
    print("To get:")
    print("  f'' + 2f'/r + 2s(q) f/r^2 = 0")
    print()
    print("we need:")
    print("  dV/df = s(q) f")
    print("  V = (1/2) s(q) f^2")
    print()
    print("For s(q)=q/3:")
    print("  V = (q/6) f^2")
    print()
    print("Problem:")
    print("  q depends on f' through q=-r f'/f.")
    print("  Therefore V=(q/6)f^2 is not an ordinary potential V(f,r).")
    print("  It is derivative-dependent unless q is treated as an independent")
    print("  boundary/collar variable.")
    print()
    print("No-approximation verdict:")
    print("  A simple local potential can generate a fixed s, but s(q)=q/3")
    print("  requires derivative-dependent or phase-space collar structure.")


if __name__ == "__main__":
    main()
