def main() -> None:
    print("constrained q action test")
    print("=" * 27)
    print("Try treating q as an independent collar variable:")
    print("  q + r f'/f = 0")
    print()
    print("Candidate action structure:")
    print("  S = integral [1/4 r^2 f'^2 - (q/6)f^2")
    print("                + lambda(q + r f'/f)] dr")
    print()
    print("Variations give:")
    print("  delta lambda: q + r f'/f = 0")
    print("  delta q:      -f^2/6 + lambda = 0")
    print("                lambda = f^2/6")
    print()
    print("The multiplier is fixed algebraically, but this does not by itself")
    print("select q=1/3. q still follows from the coupled f equation.")
    print()
    print("Risk:")
    print("  The term -(q/6)f^2 was inserted to force s(q)=q/3.")
    print("  Unless that term is derived, the constrained-variable action")
    print("  only repackages the postulate.")
    print()
    print("No-approximation verdict:")
    print("  Promoting q to an independent variable is mathematically possible,")
    print("  but it does not derive the activation law unless the q f^2 term")
    print("  has a native origin.")


if __name__ == "__main__":
    main()
