def main() -> None:
    print("GHY / Dirichlet cancellation audit")
    print("=" * 39)
    print("Metric:")
    print("  ds^2 = -f dt^2 + f^{-1} dr^2 + r^2 dOmega^2")
    print()
    print("Raw EH radial primitive:")
    print("  B_EH = 2R(1-f) - R^2 f'")
    print()
    print("Timelike r=R boundary:")
    print("  n^r = sqrt(f)")
    print("  K = 2 sqrt(f)/R + f'/(2 sqrt(f))")
    print("  sqrt(|h|) = sqrt(f) R^2 sin(theta)")
    print()
    print("Suppressing angular/time factors:")
    print("  sqrt(|h|) K = 2 R f + (R^2 f')/2")
    print("  2 sqrt(|h|) K = 4 R f + R^2 f'")
    print()
    print("Dirichlet-completed EH + GHY boundary combination:")
    print("  B_EH + 2 sqrt(|h|) K")
    print("    = [2R(1-f) - R^2 f'] + [4Rf + R^2 f']")
    print("    = 2R(1+f)")
    print()
    print("At phi0 where f=1:")
    print("  B_EH + 2K term = 4R")
    print("  flat reference value = 4R")
    print("  subtracted value = 0")
    print()
    print("No-invention verdict:")
    print("  The raw EH total derivative sees the phi0 slope.")
    print("  Standard Dirichlet EH+GHY completion cancels that slope dependence.")
    print("  Therefore the eta-producing boundary momentum is not derived by")
    print("  ordinary GR Dirichlet boundary completion at f=1.")
    print()
    print("Refined target:")
    print("  If a native term exists, it must behave like a mixed/Neumann/joint/edge")
    print("  contribution, not like standard Dirichlet EH+GHY quasilocal energy.")


if __name__ == "__main__":
    main()
