def main() -> None:
    print("delta_h variational status")
    print("=" * 28)
    print("C1 radial action:")
    print("  S_C1 = 1/4 integral r^2 f'^2 dr")
    print()
    print("Variation:")
    print("  delta S_C1 = bulk + [Pi_f delta f]")
    print("  Pi_f = 1/2 r^2 f'")
    print()
    print("Boundary value at phi0:")
    print("  f(R) = 1")
    print()
    print("Collar factorization:")
    print("  f(r) = (R/r)^p h(r)")
    print("  h(R) = 1")
    print("  q = p + delta_h")
    print()
    print("A variation of delta_h changes f'(R), not f(R):")
    print("  delta f(R) = 0")
    print("  delta f'(R) != 0")
    print()
    print("Consequence:")
    print("  The ordinary first-order C1 boundary term [Pi_f delta f]")
    print("  does not stationarize delta_h when f(R) is fixed.")
    print()
    print("Therefore delta_h=0 cannot be derived from:")
    print("  a plain Dirichlet phi0 value condition, or")
    print("  a boundary functional depending only on f(R).")
    print()
    print("It can only be derived by one of:")
    print("  1. bulk equation plus regularity/global endpoint condition;")
    print("  2. a derivative-dependent boundary/joint term involving f'(R)")
    print("     or extrinsic curvature;")
    print("  3. a Calderon projector that restricts allowed Cauchy data to")
    print("     a one-eigenvalue graph;")
    print("  4. a native angular/collar source law that keeps h'(R)=0.")
    print()
    print("Status verdict:")
    print("  The p=q proof must use a Cauchy-data restriction, not only")
    print("  the already-known C1 momentum boundary variation.")


if __name__ == "__main__":
    main()
