def main() -> None:
    print("mixed Hodge domain theorem audit")
    print("=" * 34)
    print("Collar:")
    print("  M = I x S2")
    print("  boundary = S2_endpoint union S2_phi0")
    print()
    print("Angular H1 carrier:")
    print("  omega_H1 = dOmega_S2")
    print("  boundary type: absolute/tangential angular carrier")
    print("  harmonic representative: nonzero")
    print("  carrier dimension: one scalar area-form from Lambda^3 H1")
    print()
    print("Scalar h residual:")
    print("  y = ln h")
    print("  y(endpoint)=0")
    print("  y(phi0)=0")
    print("  boundary type: relative scalar residual")
    print()
    print("Relative harmonic 0-form test on the interval:")
    print("  Delta y = 0")
    print("  y|boundary = 0")
    print("  maximum principle / energy identity gives y=0")
    print()
    print("Thus:")
    print("  absolute harmonic H1 area carrier survives")
    print("  relative harmonic scalar h residual vanishes")
    print()
    print("Domain theorem candidate:")
    print("  Elementary phi0 data are mixed Hodge representatives:")
    print("    absolute harmonic angular carrier")
    print("    no relative scalar residual zero-mode")
    print()
    print("Consequences:")
    print("  h=1")
    print("  delta_h=0")
    print("  p=q")
    print("  H1 one-graph branch gives q=1/3")
    print()
    print("No-overclaim verdict:")
    print("  This is close to a proof of the remaining domain premise if UDT's")
    print("  elementary phi0 projector is identified with the mixed Hodge")
    print("  harmonic representative projector on the collar.")
    print("  The only remaining step is deriving that identification from the")
    print("  UDT boundary variational problem.")


if __name__ == "__main__":
    main()
