"""
B2-1 (load-bearing): l=2 quadrupole time-dependent vacuum perturbation.
Does a genuine d_t^2 (wave) operator appear, and is it PHYSICAL vs GAUGE?

Background: flat round metric in (t,r,th,psi) with c=1.
Perturbation (diagonal angular warp, as author describes):
  g_thth -> r^2 (1 + eps h(t,r) P2),  g_psps -> r^2 sin^2 th (1 - eps h(t,r) P2)
  P2 = (3 cos^2 th - 1)/2
Compute O(eps) vacuum Einstein eqs; inspect G_thth for d_t^2 h.

Then B2-1 gauge test: also test the SAME warp but check whether the
d_t^2 term can be removed by a gauge (diffeomorphism) vector. We use the
standard result that for l>=2 the metric perturbation has a gauge-invariant
content (Regge-Wheeler/Zerilli); l=0,1 do not radiate. We test directly by
counting: a pure-gauge l=2 even perturbation generated by xi_mu cannot
produce a non-removable d_t^2 in a gauge-invariant combination.
"""
import sympy as sp

t, r, th, ps, eps = sp.symbols('t r theta psi epsilon', real=True)
h = sp.Function('h')(t, r)
P2 = (3*sp.cos(th)**2 - 1)/2

x = [t, r, th, ps]

# c = 1 flat round background + warp
g = sp.zeros(4, 4)
g[0, 0] = -1
g[1, 1] = 1
g[2, 2] = r**2 * (1 + eps*h*P2)
g[3, 3] = r**2 * sp.sin(th)**2 * (1 - eps*h*P2)

ginv = g.inv()

def christoffel(g, ginv, x):
    n = len(x)
    Gam = [[[sp.Integer(0)]*n for _ in range(n)] for _ in range(n)]
    for a in range(n):
        for b in range(n):
            for cc in range(n):
                s = 0
                for d in range(n):
                    s += ginv[a, d]*(sp.diff(g[d, b], x[cc]) + sp.diff(g[d, cc], x[b]) - sp.diff(g[b, cc], x[d]))
                Gam[a][b][cc] = s/2
    return Gam

Gam = christoffel(g, ginv, x)

def ricci(Gam, x):
    n = len(x)
    Ric = sp.zeros(n, n)
    for a in range(n):
        for b in range(n):
            s = 0
            for cc in range(n):
                s += sp.diff(Gam[cc][a][b], x[cc]) - sp.diff(Gam[cc][a][cc], x[b])
                for d in range(n):
                    s += Gam[cc][cc][d]*Gam[d][a][b] - Gam[cc][a][d]*Gam[d][b][cc]
            Ric[a, b] = s
    return Ric

Ric = ricci(Gam, x)
Rscal = sum(ginv[a, b]*Ric[a, b] for a in range(4) for b in range(4))

# linearize in eps: G_munu at O(eps)
G = sp.zeros(4, 4)
for a in range(4):
    for b in range(4):
        Gab = Ric[a, b] - sp.Rational(1, 2)*g[a, b]*Rscal
        # O(eps) coefficient
        ser = sp.series(Gab, eps, 0, 2).removeO()
        lin = sp.simplify(sp.diff(ser, eps).subs(eps, 0))
        G[a, b] = lin

print("O(eps) vacuum Einstein components:")
print("  G_tr  =", sp.simplify(G[0, 1]))
Gthth = sp.expand(sp.simplify(G[2, 2]))
print("  G_thth=", Gthth)
# Extract coefficient of h_tt
htt = sp.diff(h, t, 2)
coeff_htt = sp.simplify(Gthth.coeff(htt))
print("\n  coefficient of d_t^2 h in G_thth =", coeff_htt)
print("  is it identically zero? ->", sp.simplify(coeff_htt) == 0)
