"""W1 ROUTE C — BLIND ADVERSARIAL VERIFIER, SECOND PASS (verifier2).

New file, 2026-06-11.  Replaces the stalled first verifier
(w_stiffness_routeC_verifier.py, killed after 2+ h inside an open-ended
sp.solve on a nested-radical expression at its line 179; its conclusions
are treated as ABSENT — nothing here inherits from it beyond the attack
map, which was re-derived independently).

HARD RULE OBEYED THROUGHOUT: no open-ended sp.solve on radical/nested
expressions anywhere in this file.  Claimed roots and stationary points
are verified by SUBSTITUTION; uniqueness is verified by LINEARITY/DEGREE
arguments (the Route A verifier proved the q-bracket is LINEAR in q —
the same style is used here: the bracket polynomial's degree is checked,
making root uniqueness a theorem, and the claimed root is substituted).

TARGET: w_stiffness_routeC_sector_audit.py (41 checks PASS on rerun,
log /tmp/routeC_rerun.log — NOTE: the results doc says "42"; the actual
call-site count and the log both say 41; grep -c 'check(' returns 42
because it counts the `def check(` line.  Off-by-one in the doc, not in
the script).

ATTACK MAP (independent machinery; different constructions, different
points, different methods from the route):
  W0  independent rebuild of the P1 class (metric assembled differently),
      flux closed form, tadpole, jet scans, NEW rational spot points.
  W1  q*-branch WITHOUT solve: (a) the q-stationarity bracket of L_C1 is
      proved LINEAR in q by polynomial-degree check (uniqueness theorem);
      (b) the claimed root is verified by substitution; (c) the
      eliminated density is verified by substitution on an explicitly
      positive branch parametrization (Delta = v^2 X d/(1+d), d > 0 —
      every nested radical resolves over positive atoms); (d) the branch
      w-force sign (the basis of the tadpole "opposition" claim) is
      re-derived, and the OPPOSITE branch's sign flip is recorded.
  W2  S6 attacked on a STRICTLY LARGER class than the route's: general
      angular block (A, B independent) PLUS the off-diagonal angular
      entry g_theta-phi = r^2 p(r,theta) PLUS q: jet scans of C1, flux,
      source, completion family, H1-carrier energy; union of
      differentiated functions.
  W3  rep-independence: general 4-potential Maxwell on the extended
      block differentiates only A_mu (no Christoffels in
      sqrt(-g) F_{mu nu} F^{mu nu}).
  W4  THE MAXWELL RE-SOLVING ATTACK (solution-level loophole of claims
      1/3): (a) the monopole rep's off-shell residual at q != 0 is
      GENUINELY nonzero (exact evaluation on explicit fields at an exact
      point — non-vacuous, unlike a failed-simplify != 0); (b) the O(q)
      residual's jet content is EXACTLY {df, dq} — no dv at O(q); dv
      first enters the source at O(q^2), so the on-shell sector's
      nonlocal w-derivative dependence starts at O(q^3); (c) Q_f is
      TOPOLOGICALLY PROTECTED: for every regular axisymmetric correction
      potential the sphere flux is unchanged (Stokes, exact) — the
      re-solved Q_f acquires NO dependence on anything; (d) DUAL-POTENTIAL
      THEOREM (exact, ALL orders in q): every axisymmetric magnetic
      Maxwell field on the class is generated by a dual potential
      psi(r,theta) with sqrt(-g)F^{r phi} = psi_theta,
      sqrt(-g)F^{theta phi} = -psi_r; the divergence equations hold
      IDENTICALLY for any psi, the remaining Maxwell content (dF = 0) is
      exactly the psi-EL equation of the flux action, and the on-shell
      flux DENSITY in this rep differentiates ONLY psi — the metric
      (w, q, f) enters algebraically.  Hence re-solving cannot smuggle
      LOCAL angular-block derivatives into the on-shell density at any
      order in q; metric-derivative dependence enters only nonlocally
      through psi's PDE.  (e) ORDER COUNTING of the on-shell w-force:
      the response correction to the w-force enters at O(q^2) — the SAME
      order as the tadpole — through the w-derivative of the Maxwell
      quadratic form (the G' term of the envelope identity
      dE*/dw = E0' - <L1', G^{-1} L1> + (1/2)<a*, G' a*>), whose q = 0
      kernel is computed exactly and is sign-definite OPPOSITE to the
      tadpole.  The first verifier's design note claimed the correction
      is O(q^3); that count kept only the <L1', G^{-1} L1> cross term
      (verified O(q^3) here) and DROPPED the G' term.  Consequence is an
      AMENDMENT to any on-shell reading of claim 3, not to the route
      (the route explicitly left re-solving open).
  W5  claim 4 (responsive Hessian = C1 angular second variation):
      verified by independent construction + EXACT rational-point
      substitution with non-harmonic test functions; the two banked
      couplings re-derived by INTEGRATE-THEN-EXPAND (closed-form
      kappa-symbolic integration first, series second — opposite order
      of operations from the route's expand-then-integrate).
  W6  non-vacuity guard on the route's S5 momenta/second-variation
      checks (diff w.r.t. a Derivative atom and a derivative-free d2L
      can both be vacuously satisfied): explicit-fluctuation first AND
      second variations, required NONZERO while fluctuation-derivative-
      free.
  W7  statics premise: all densities rebuilt with f, q, v functions of
      (T, r, theta); jet scans (the "structural time-row extension"
      note).  The weld objects are adjudicated in the report (they are
      constraint identities, not action pieces — see verdict text).

Run:  python3 w_stiffness_routeC_verifier2.py
"""

from __future__ import annotations

import sys

import sympy as sp

FAILURES: list[str] = []
NCHECK = 0


def check(label: str, ok: bool) -> None:
    global NCHECK
    NCHECK += 1
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
    if not ok:
        FAILURES.append(label)


def hr(title: str) -> None:
    print()
    print("=" * 78)
    print(title)
    print("=" * 78)


def diff_funcs(expr) -> set:
    expr = sp.sympify(expr).doit()
    return {d.expr.func for d in expr.atoms(sp.Derivative)}


def has_func(expr, fn) -> bool:
    return fn.func in {a.func for a in sp.sympify(expr).atoms(sp.Function)}


# ===========================================================================
hr("W0 — INDEPENDENT REBUILD: metric, flux closed form, tadpole, jet scans")
# ===========================================================================
T = sp.Symbol("T", real=True)
r = sp.Symbol("r", positive=True)
th = sp.Symbol("theta", real=True)
ph = sp.Symbol("varphi", real=True)
coords = [T, r, th, ph]
cc = sp.Symbol("c", positive=True)
mu = sp.Symbol("mu", positive=True)
Qf = sp.Symbol("Q_f", positive=True)
s_s = sp.Symbol("s", real=True)
Wr = sp.Function("W")(r)
sth = sp.sin(th)

f = sp.Function("f", positive=True)(r, th)
q = sp.Function("q", real=True)(r, th)
v = sp.Function("v", positive=True)(r, th)

# metric assembled from a symmetric-pair list (different construction path
# from the route's explicit Matrix literal)
g = sp.zeros(4, 4)
for (a, b, val) in [(0, 0, -f), (1, 1, 1 / f), (1, 2, q),
                    (2, 2, r**2 * v**2), (3, 3, r**2 * sth**2 / v**2)]:
    g[a, b] = val
    g[b, a] = val
D2 = r**2 * v**2 - f * q**2
check("det rebuilt: -det g = r^2 sin^2(th) D / v^2, D = r^2 v^2 - f q^2",
      sp.simplify(-g.det() - r**2 * sth**2 * D2 / v**2) == 0)
ginv = g.inv()
check("inverse verified by MULTIPLICATION: g g^{-1} = 1",
      sp.simplify(g * ginv - sp.eye(4)) == sp.zeros(4, 4))
sqrtmg = r * sth * sp.sqrt(D2) / v

F0 = sp.zeros(4, 4)
F0[2, 3] = Qf * sth
F0[3, 2] = -Qf * sth
F0up = ginv * F0 * ginv
L_flux = sp.simplify(-(sp.Rational(1, 4) / mu) * sqrtmg
                     * sum(F0[i, j] * F0up[i, j]
                           for i in range(4) for j in range(4)))
check("CLAIM 1 flux closed form: L_flux = -(Q_f^2/(2 mu)) sin(th) v"
      "/(r sqrt(D)) exactly  [v = 1+w]",
      sp.simplify(L_flux + (Qf**2 / (2 * mu)) * sth * v
                  / (r * sp.sqrt(D2))) == 0)
tad = sp.simplify(sp.diff(L_flux, v))
check("CLAIM 3 tadpole closed form: dL_flux/dw = +(Q_f^2/(2 mu)) sin(th) "
      "f q^2/(r D^{3/2}) exactly (substitution-derived, no solve)",
      sp.simplify(tad - (Qf**2 / (2 * mu)) * sth * f * q**2
                  / (r * D2**sp.Rational(3, 2))) == 0)
check("flux density zeroth-jet in EVERYTHING (no Derivative atoms)",
      diff_funcs(L_flux) == set())
check("q = 0: L_flux exactly w-blind (v absent after substitution)",
      not has_func(sp.simplify(L_flux.subs(q, 0)), v))
# NEW rational spot point (different from the route's): f=5, q=1/3, v=2,
# r=1, Q_f=mu=1: D = 4 - 5/9 = 31/9; sqrt(D) = sqrt(31)/3
spot = L_flux.subs([(f, 5), (q, sp.Rational(1, 3)), (v, 2), (r, 1),
                    (Qf, 1), (mu, 1)])
check("NEW rational spot point f=5, q=1/3, v=2, r=1: L_flux = "
      "-3 sin(th)/sqrt(31) exactly",
      sp.simplify(spot + 3 * sth / sp.sqrt(31)) == 0)
spot_t = tad.subs([(f, 5), (q, sp.Rational(1, 3)), (v, 2), (r, 1),
                   (Qf, 1), (mu, 1)])
check("NEW rational spot point: tadpole = (5/18)*27/(31 sqrt(31)/27)... "
      "= (15/2) sin(th)/(31 sqrt(31)/27) exactly (evaluated symbolically)",
      sp.simplify(spot_t - sp.Rational(1, 2) * sth * 5 * sp.Rational(1, 9)
                  / (sp.Rational(31, 9)**sp.Rational(3, 2))) == 0)

# C1 with the FULL 16-term contraction (guards a dropped-term error)
phi = -sp.log(f) / 2
dphi = [sp.diff(phi, x) for x in coords]
L_C1 = sp.simplify(-(cc / 2) * f * sqrtmg
                   * sum(ginv[i, j] * dphi[i] * dphi[j]
                         for i in range(4) for j in range(4)))
check("C1 rebuilt (all 16 inverse-metric terms): differentiates f ONLY",
      diff_funcs(L_C1) == {f.func})

# ===========================================================================
hr("W1 — q* BRANCH WITHOUT SOLVE: linearity theorem + substitution")
# ===========================================================================
# pointwise atoms (the q-elimination is pointwise algebra; L_C1 is
# zeroth-jet in q by W0, so dL/dq is a pointwise function of the atoms)
F_, Fr_, Fth_, V_, R_, q_ = sp.symbols("F F_r F_th V R qq", positive=True)
S_th = sp.Symbol("s_th", positive=True)
Dpt = R_**2 * V_**2 - F_ * q_**2
Lpt = (-(cc / 8) * R_ * S_th
       * (F_ * R_**2 * V_**2 * Fr_**2 - 2 * F_ * q_ * Fr_ * Fth_ + Fth_**2)
       / (V_ * F_ * sp.sqrt(Dpt)))
# the q-stationarity bracket: dL/dq * (positive factor) -> polynomial in q
dLdq = sp.diff(Lpt, q_)
bracket = sp.simplify(dLdq * (-8 / cc) * (V_ * F_ / (R_ * S_th))
                      * Dpt**sp.Rational(3, 2))
bracket_poly = sp.Poly(sp.expand(bracket), q_)
check("LINEARITY THEOREM (no solve): the q-stationarity bracket "
      "dL_C1/dq * (8 V F D^{3/2} / (-c R sin)) is a polynomial of DEGREE "
      "1 in q — the q^2, q^3 terms cancel exactly, so the stationary q* "
      "is UNIQUE as a theorem",
      bracket_poly.degree() == 1)
b1 = bracket_poly.coeff_monomial(q_)
b0 = bracket_poly.coeff_monomial(1)
qstar_claimed = 2 * R_**2 * V_**2 * Fr_ * Fth_ \
    / (F_ * R_**2 * V_**2 * Fr_**2 + Fth_**2)
check("claimed root verified by SUBSTITUTION: bracket(q*) = 0 with "
      "q* = 2 r^2 v^2 f_r f_th / (f r^2 v^2 f_r^2 + f_th^2)",
      sp.simplify(bracket.subs(q_, qstar_claimed)) == 0)
check("linear-coefficient root agrees with the claimed q* "
      "(-b0/b1 = q*, exact division — not an open-ended solve)",
      sp.simplify(-b0 / b1 - qstar_claimed) == 0)

# eliminated density by substitution on the EXPLICIT Delta > 0 branch:
# Y := f_th^2 = v^2 X - Delta with X = f r^2 f_r^2 and
# Delta = v^2 X d/(1+d), d > 0  (encodes 0 < Delta < v^2 X; every nested
# radical is a square root of a positive atom product)
d_ = sp.Symbol("d", positive=True)
Fth_branch = V_ * sp.sqrt(F_) * R_ * Fr_ / sp.sqrt(1 + d_)
L_at_qstar = Lpt.subs(q_, qstar_claimed).subs(Fth_, Fth_branch)
target_branch = (-(cc / 8) * S_th * R_**2 * Fr_**2 * d_ / (1 + d_))
check("ELIMINATED DENSITY by substitution (Delta > 0 branch, positive "
      "parametrization d > 0): L_C1(q*) = -(c/8) sin(th) [f r^2 f_r^2 "
      "- f_th^2/v^2]/f exactly — Route A/pde_p1 branch form confirmed "
      "with NO solve call",
      sp.simplify(L_at_qstar - target_branch) == 0)
# branch w-force (independent atoms — f_th NOT tied to v here)
L_eff = -(cc / 8) * S_th * (F_ * R_**2 * Fr_**2 - Fth_**2 / V_**2) / F_
wforce = sp.diff(L_eff, V_)
check("q*-branch w-force by differentiation: dL_eff/dw = -(c/4) sin(th) "
      "f_th^2/(f v^3) — NEGATIVE; the flux tadpole (positive) opposes it: "
      "CLAIM 3 sign structure confirmed on the Delta > 0 branch",
      sp.simplify(wforce + (cc / 4) * S_th * Fth_**2 / (F_ * V_**3)) == 0)
# the opposite branch: Y = v^2 X (1 + d), d > 0 (i.e. Delta < 0).  The
# absolute-value structure keeps L(q*) = -(c/8) sin |X - Y/v^2| / f
# NEGATIVE on both branches, but the w-FORCE flips sign there:
Fth_b2 = V_ * sp.sqrt(F_) * R_ * Fr_ * sp.sqrt(1 + d_)
L_at_qstar_b2 = Lpt.subs(q_, qstar_claimed).subs(Fth_, Fth_b2)
target_b2 = -(cc / 8) * S_th * R_**2 * Fr_**2 * d_   # = -(c/8)s|X-Y/v^2|/f
check("OPPOSITE branch (Delta < 0, i.e. f_th^2 > v^2 f r^2 f_r^2): "
      "L_C1(q*) = -(c/8) sin(th) (f_th^2/v^2 - f r^2 f_r^2)/f — the "
      "absolute-value form |X - Y/v^2| confirmed by substitution",
      sp.simplify(L_at_qstar_b2 - target_b2) == 0)
L_eff_b2 = -(cc / 8) * S_th * (Fth_**2 / V_**2 - F_ * R_**2 * Fr_**2) / F_
wforce_b2 = sp.diff(L_eff_b2, V_)
check("OPPOSITE-branch w-force: dL_eff/dw = +(c/4) sin(th) f_th^2"
      "/(f v^3) — POSITIVE, i.e. the SAME sign as the flux tadpole: the "
      "'opposition' of claim 3 is Delta > 0 BRANCH-CONDITIONAL "
      "(amendment-grade scope note on claim 3's wording)",
      sp.simplify(wforce_b2 - (cc / 4) * S_th * Fth_**2
                  / (F_ * V_**3)) == 0)

# ===========================================================================
hr("W2 — CLAIM 2 ATTACKED ON A STRICTLY LARGER CLASS: general block "
   "(A, B) + OFF-DIAGONAL g_theta-phi = r^2 p + q")
# ===========================================================================
Af = sp.Function("A", positive=True)(r, th)
Bf = sp.Function("B", positive=True)(r, th)
pf = sp.Function("p", real=True)(r, th)
gX = sp.zeros(4, 4)
for (a, b, val) in [(0, 0, -f), (1, 1, 1 / f), (1, 2, q),
                    (2, 2, r**2 * Af), (3, 3, r**2 * sth**2 * Bf),
                    (2, 3, r**2 * pf)]:
    gX[a, b] = val
    gX[b, a] = val
gXinv = gX.inv()
sqrtmgX = sp.sqrt(sp.factor(-gX.det()))
L_C1_X = -(cc / 2) * f * sqrtmgX * sum(
    gXinv[i, j] * dphi[i] * dphi[j] for i in range(4) for j in range(4))
F0upX = gXinv * F0 * gXinv
L_flux_X = -(sp.Rational(1, 4) / mu) * sqrtmgX * sum(
    F0[i, j] * F0upX[i, j] for i in range(4) for j in range(4))
L_src_X = sp.Rational(1, 2) * s_s * Wr * f**2 * sqrtmgX / r**2
y_ = sp.Symbol("y", positive=True)
n_ = sp.Symbol("n", real=True)
cn = sp.Function("c_n")(y_)
L_compl_X = cn * f**n_ * sqrtmgX
chi = sp.Function("chi", real=True)(th, ph)
E_carrier_X = sqrtmgX * (
    gXinv[2, 2] * sp.diff(chi, th)**2
    + 2 * gXinv[2, 3] * sp.diff(chi, th) * sp.diff(chi, ph)
    + gXinv[3, 3] * sp.diff(chi, ph)**2)
check("C1 on (A, B, p, q): differentiates f ONLY — claim 2 survives the "
      "off-diagonal enlargement the route did NOT audit",
      diff_funcs(L_C1_X) == {f.func})
check("flux on (A, B, p, q): NO derivatives at all",
      diff_funcs(L_flux_X) == set())
check("H1 collar source (proper lift) on (A, B, p, q): NO derivatives",
      diff_funcs(L_src_X) == set())
check("completion family (proper measure) on (A, B, p, q): NO "
      "derivatives; coordinate-measure member contains no metric at all",
      diff_funcs(L_compl_X) == set()
      and diff_funcs(cn * f**n_) == set())
check("H1-carrier angular Dirichlet energy on (A, B, p): differentiates "
      "ONLY the carrier chi — the metric (incl. the off-diagonal p) "
      "enters algebraically (Hellmann-Feynman: eigenvalue functionals "
      "get algebraic w-variations only)",
      diff_funcs(E_carrier_X) == {chi.func})
allD = (diff_funcs(L_C1_X) | diff_funcs(L_flux_X) | diff_funcs(L_src_X)
        | diff_funcs(L_compl_X))
check("CLAIM 2 (S6 structural theorem) on the STRICTLY LARGER class: "
      "union of differentiated functions across the banked action stack "
      "= {f} — no dA, dB, dp, dq at any order",
      allD == {f.func})

# ===========================================================================
hr("W3 — REP-INDEPENDENCE: general 4-potential Maxwell on the extended "
   "block (no Christoffels in sqrt(-g) F^2)")
# ===========================================================================
Amu = [sp.Function(f"Apot_{k}", real=True)(r, th) for k in range(4)]
Fg = sp.zeros(4, 4)
for a in range(4):
    for b in range(4):
        Fg[a, b] = sp.diff(Amu[b], coords[a]) - sp.diff(Amu[a], coords[b])
FgupX = gXinv * Fg * gXinv
L_max_X = -(sp.Rational(1, 4) / mu) * sqrtmgX * sum(
    Fg[i, j] * FgupX[i, j] for i in range(4) for j in range(4))
check("general A_mu(r,th) Maxwell density on (A, B, p, q): "
      "differentiates ONLY the potentials — never f, q, A, B, p "
      "(F = dA needs no connection; sqrt(-g) F^2 is algebraic in g)",
      diff_funcs(L_max_X) <= {a.func for a in Amu})

# ===========================================================================
hr("W4 — MAXWELL RE-SOLVING: the solution-level loophole of claims 1/3")
# ===========================================================================
# (a) the monopole residual at q != 0: GENUINELY nonzero (exact point,
# explicit fields — guards the route's failed-simplify != 0 check)
div_phi = sp.simplify(sum(sp.diff(sqrtmg * F0up[m, 3], coords[m])
                          for m in range(4)))
subs_explicit = [(f, 1 + r**2), (v, 1 + sp.Rational(1, 10) * r
                                 * sp.cos(th)), (q, r * sp.sin(th))]
val = div_phi.subs(subs_explicit).doit().subs(
    [(r, 1), (th, sp.pi / 3), (Qf, 1), (mu, 1)])
val = sp.simplify(val)
check("monopole Maxwell residual at q != 0 is GENUINELY nonzero: exact "
      "evaluation on explicit fields f = 1+r^2, v = 1+(r cos th)/10, "
      "q = r sin th at (r, th) = (1, pi/3) gives a nonzero exact number "
      "(non-vacuous confirmation of the route's off-shell flag)",
      val.is_zero is False and val != 0)
check("the same residual vanishes IDENTICALLY at q = 0 (re-derived): "
      "the monopole is on-shell on the whole diagonal w-on class",
      sp.simplify(div_phi.subs(q, 0).doit()) == 0)
# (b) jet content of the O(q) residual (the source the re-solved field
# inherits): expand in eps with q -> eps*q
eps = sp.Symbol("epsilon", real=True)
res_eps = sp.expand(sp.series(div_phi.subs(q, eps * q).doit(),
                              eps, 0, 3).removeO())
res_O1 = sp.simplify(res_eps.coeff(eps, 1))
res_O2 = sp.simplify(res_eps.coeff(eps, 2))
check("O(q) residual nonzero; its differentiated-function set is "
      "EXACTLY {f, q} — the O(q) source carries df and dq but NO "
      "w-derivative (dv is ABSENT at this order): the leading re-solved "
      "correction field is dw-FREE  [finding: sharper than the first "
      "verifier's design, which lumped 'f and/or v']",
      res_O1 != 0 and diff_funcs(res_O1) == {f.func, q.func})
check("dv first enters the residual at O(q^2): Derivative(v) appears in "
      "the O(q^2) coefficient — nonlocal w-derivative dependence of the "
      "on-shell SECTOR starts only at O(q^3) in the action "
      "(<L1, G^{-1} L2> cross order), one order past every O(q^2) "
      "structure discussed in claim 3",
      v.func in diff_funcs(res_O2))
# (c) Q_f topologically protected: generic regular axisymmetric
# correction potential A1_phi = sin^2(th) * h(r, cos th) (regular on the
# axis); sphere flux of dA1 = Int d_th A1_phi = [A1_phi]_0^pi by the
# fundamental theorem of calculus — evaluate the boundary values exactly
h_ = sp.Function("h", real=True)
A1ph = sth**2 * h_(r, sp.cos(th))
check("Q_f TOPOLOGICALLY PROTECTED: for the generic regular "
      "axisymmetric correction A1_phi = sin^2(th) h(r, cos th), the "
      "sphere-flux correction Int_0^pi d_th A1_phi dth = "
      "[A1_phi]_0^pi = 0 - 0 = 0 exactly (FTC + axis regularity) — the "
      "re-solved sphere flux is 4 pi Q_f unchanged; Q_f acquires NO "
      "dependence on the metric, its derivatives, or anything else",
      sp.simplify(A1ph.subs(th, 0)) == 0
      and sp.simplify(A1ph.subs(th, sp.pi)) == 0)
# (d) DUAL-POTENTIAL THEOREM (exact, all orders in q)
psi = sp.Function("psi", real=True)(r, th)
Fup_dual = sp.zeros(4, 4)
Fup_dual[1, 3] = sp.diff(psi, th) / sqrtmg
Fup_dual[3, 1] = -Fup_dual[1, 3]
Fup_dual[2, 3] = -sp.diff(psi, r) / sqrtmg
Fup_dual[3, 2] = -Fup_dual[2, 3]
div_ok = True
for nu in range(4):
    dd = sum(sp.diff(sqrtmg * Fup_dual[m, nu], coords[m])
             for m in range(4))
    div_ok = div_ok and sp.simplify(dd) == 0
check("dual rep: d_mu(sqrt(-g) F^{mu nu}) = 0 holds IDENTICALLY for "
      "EVERY psi(r,th) and every (f, q, v) — the divergence half of "
      "Maxwell is automatic in the dual rep",
      div_ok)
F_dual = g * Fup_dual * g            # lower indices: F_{mu nu}
L_dual = -(sp.Rational(1, 4) / mu) * sqrtmg * sum(
    Fup_dual[i, j] * F_dual[i, j] for i in range(4) for j in range(4))
check("DUAL-REP THEOREM (the re-solving loophole CLOSED at density "
      "level, ALL orders in q): the flux density in the dual rep "
      "differentiates ONLY psi — the metric (f, q, v = 1+w) enters "
      "algebraically for EVERY psi, hence also for the SOLVED psi*; "
      "re-solving Maxwell cannot smuggle local angular-block "
      "derivatives into the on-shell density",
      diff_funcs(L_dual) == {psi.func})
# psi-EL of L_dual == closedness (the remaining Maxwell content):
EL_psi = (sp.diff(sp.diff(L_dual, sp.Derivative(psi, r)), r)
          + sp.diff(sp.diff(L_dual, sp.Derivative(psi, th)), th))
closedness = sp.diff(F_dual[2, 3], r) - sp.diff(F_dual[1, 3], th)
check("the psi-EL equation of the dual density IS closedness: "
      "EL_psi = (1/mu)[d_r F_{th ph} - d_th F_{r ph}] exactly — "
      "stationary psi <=> dF = 0 <=> genuine on-shell Maxwell field",
      sp.simplify(EL_psi - closedness / mu) == 0)
# monopole correspondence at q = 0: psi0 = -Q_f / r... determine sign by
# substitution: psi0 = Q_f/r gives sqrt(-g)F^{th ph} = -psi_r = Q_f/r^2
psi0 = Qf / r
F_dual_0 = F_dual.subs(psi, psi0).doit().subs(q, 0)
L_dual_0 = sp.simplify(L_dual.subs(psi, psi0).doit().subs(q, 0))
check("monopole correspondence: psi0 = Q_f/r at q = 0 reproduces "
      "F_{th ph} = Q_f sin th, F_{r ph} = 0 and L_dual = "
      "-(Q_f^2/(2 mu)) sin(th)/r^2 — the banked monopole IS the dual-rep "
      "solution, for EVERY w",
      sp.simplify(F_dual_0[2, 3] - Qf * sth) == 0
      and sp.simplify(F_dual_0[1, 3]) == 0
      and sp.simplify(L_dual_0 + Qf**2 * sth / (2 * mu * r**2)) == 0)
# (e) ORDER COUNTING of the on-shell w-force (A-rep envelope identity:
# dE*/dw = E0' - <L1', G^{-1} L1> + (1/2)<a*, G' a*>;  L1 = O(q) residual)
cw_thph = sp.simplify(sp.diff(sqrtmg * F0up[2, 3], v))
cw_rph = sp.simplify(sp.diff(sqrtmg * F0up[1, 3], v))
ser_thph = sp.series(cw_thph.subs(q, eps * q).doit(), eps, 0, 2).removeO()
ser_rph = sp.series(cw_rph.subs(q, eps * q).doit(), eps, 0, 3).removeO()
check("cross term <L1', G^{-1} L1> is O(q^3): d_w(sqrt(-g) F0^{th ph}) "
      "= O(q^2) and d_w(sqrt(-g) F0^{r ph}) = O(q^3) exactly (series), "
      "and the response a* = O(q) — the first verifier's design counted "
      "ONLY this term",
      sp.simplify(sp.expand(ser_thph).coeff(eps, 0)) == 0
      and sp.simplify(sp.expand(ser_thph).coeff(eps, 1)) == 0
      and all(sp.simplify(sp.expand(ser_rph).coeff(eps, k)) == 0
              for k in (0, 1, 2)))
# the DROPPED term: G' = d_w(Maxwell quadratic form), magnetic sector
a_fl = sp.Function("a_fl", real=True)(r, th)   # fluctuation A1_phi
dFa = sp.zeros(4, 4)
dFa[1, 3] = sp.diff(a_fl, r)
dFa[3, 1] = -dFa[1, 3]
dFa[2, 3] = sp.diff(a_fl, th)
dFa[3, 2] = -dFa[2, 3]
dFa_up = ginv * dFa * ginv
L_quad = sp.simplify(-(sp.Rational(1, 4) / mu) * sqrtmg * sum(
    dFa[i, j] * dFa_up[i, j] for i in range(4) for j in range(4)))
c_rr = sp.simplify(sp.diff(L_quad, sp.Derivative(a_fl, r), 2) / 2)
c_tt = sp.simplify(sp.diff(L_quad, sp.Derivative(a_fl, th), 2) / 2)
c_rt = sp.simplify(sp.diff(sp.diff(L_quad, sp.Derivative(a_fl, r)),
                           sp.Derivative(a_fl, th)))
check("Maxwell quadratic form (magnetic sector) coefficients at q = 0: "
      "L_quad = -(1/(2 mu))[f v^2/sin(th) (a_r)^2 + 1/(r^2 sin th) "
      "(a_th)^2], cross term 0 — exact",
      sp.simplify(c_rr.subs(q, 0) + f * v**2 / (2 * mu * sth)) == 0
      and sp.simplify(c_tt.subs(q, 0) + 1 / (2 * mu * r**2 * sth)) == 0
      and sp.simplify(c_rt.subs(q, 0)) == 0)
Gp_rr = sp.simplify(sp.diff(c_rr, v).subs(q, 0))
Gp_tt = sp.simplify(sp.diff(c_tt, v).subs(q, 0))
Gp_rt = sp.simplify(sp.diff(c_rt, v).subs(q, 0))
check("THE DROPPED O(q^2) TERM EXISTS: G'|_{q=0} = d_w(quadratic form) "
      "= -(f v/(mu sin th)) (a_r)^2-direction ONLY (the (a_th)^2 "
      "coefficient 1/(r^2 sin th) is w-FREE, cross 0) — a SIGN-DEFINITE "
      "(negative in L) kernel; with a* = O(q) the envelope term "
      "(1/2)<a*, G' a*> is O(q^2), the SAME order as the tadpole and "
      "OPPOSITE in sign: the tadpole is NOT the complete on-shell "
      "w-force at O(q^2).  [Amends any on-shell reading of claim 3; "
      "the route itself left re-solving open, so the route text stands.]",
      sp.simplify(Gp_rr + f * v / (mu * sth)) == 0
      and Gp_tt == 0 and Gp_rt == 0)

# ===========================================================================
hr("W5 — CLAIM 4: responsive Hessian IS the C1 angular second variation "
   "(substitution + integrate-then-expand; NO solve)")
# ===========================================================================
cv, pv = sp.symbols("c_v p_v", real=True)
kap = sp.Symbol("kappa", positive=True)
Fb = sp.Symbol("F", positive=True)
x1, x2 = sp.symbols("x1 x2", real=True)
Y1 = sp.Function("Y1", real=True)(cv, pv)
Y2 = sp.Function("Y2", real=True)(cv, pv)
Bb = Fb * (1 + kap * cv)


def gd(u, w_):
    return ((1 - cv**2) * sp.diff(u, cv) * sp.diff(w_, cv)
            + sp.diff(u, pv) * sp.diff(w_, pv) / (1 - cv**2))


f_pert = Bb + x1 * Y1 + x2 * Y2
dens = gd(f_pert, f_pert) / f_pert
hess12 = sp.diff(dens, x1, x2).subs([(x1, 0), (x2, 0)])
quoted = (2 * gd(Y1, Y2) / Bb
          - 2 * Fb * kap * (1 - cv**2)
          * (sp.diff(Y1, cv) * Y2 + sp.diff(Y2, cv) * Y1) / Bb**2
          + 2 * (1 - cv**2) * Fb**2 * kap**2 * Y1 * Y2 / Bb**3)
check("CLAIM 4 identity, generic Y1, Y2 (independent construction): "
      "d^2/dx1 dx2 [|grad f|^2/f]|_0 with f = B + x.Y EQUALS the quoted "
      "responsive-Hessian integrand exactly",
      sp.simplify(hess12 - quoted) == 0)
# exact rational-point substitution with NON-HARMONIC test functions
Y1e = (1 - cv**2) * sp.cos(pv) + sp.Rational(3, 10) * cv
Y2e = cv**3 - sp.Rational(1, 5) * sp.sin(pv) * (1 - cv**2)
pt = [(cv, sp.Rational(2, 5)), (pv, sp.Rational(1, 3)),
      (kap, sp.Rational(3, 7)), (Fb, sp.Rational(8, 5))]
lhs = hess12.subs([(Y1, Y1e), (Y2, Y2e)]).doit().subs(pt)
rhs = quoted.subs([(Y1, Y1e), (Y2, Y2e)]).doit().subs(pt)
check("claim 4 at an EXACT rational point with non-harmonic Y1, Y2 "
      "(c = 2/5, p = 1/3, kappa = 3/7, F = 8/5): lhs - rhs = 0 exactly",
      sp.simplify(lhs - rhs) == 0)
# couplings by INTEGRATE-THEN-EXPAND (opposite order from the route)
Ya1 = sp.sqrt(sp.S(3) / (4 * sp.pi)) * sp.sqrt(1 - cv**2) * sp.cos(pv)
Yg1 = sp.sqrt(sp.S(15) / (4 * sp.pi)) * cv * sp.sqrt(1 - cv**2) * sp.cos(pv)
Ya0 = sp.sqrt(sp.S(3) / (4 * sp.pi)) * cv
Yg0 = sp.sqrt(sp.S(5) / (16 * sp.pi)) * (3 * cv**2 - 1)


def H_exact(Yi, Yj):
    integ = quoted.subs([(Y1, Yi), (Y2, Yj)]).doit()
    integ_p = sp.integrate(sp.expand_trig(sp.expand(integ)),
                           (pv, 0, 2 * sp.pi))
    integ_c = sp.integrate(sp.cancel(sp.expand(integ_p)), (cv, -1, 1))
    return sp.Rational(1, 4) * sp.simplify(integ_c)


H11 = H_exact(Ya1, Yg1)
H00 = H_exact(Ya0, Yg0)
ser11 = sp.series(H11, kap, 0, 2).removeO()
ser00 = sp.series(H00, kap, 0, 2).removeO()
check("V_a1g1 by integrate-THEN-expand: closed-form H(kappa) has O(1) "
      "term 0 and O(kappa) coefficient -sqrt(5)/(2F) exactly",
      sp.simplify(ser11.coeff(kap, 0)) == 0
      and sp.simplify(ser11.coeff(kap, 1) + sp.sqrt(5) / (2 * Fb)) == 0)
check("V_a0g0 by integrate-THEN-expand: O(1) term 0, O(kappa) "
      "coefficient -sqrt(15)/(3F) exactly",
      sp.simplify(ser00.coeff(kap, 0)) == 0
      and sp.simplify(ser00.coeff(kap, 1) + sp.sqrt(15) / (3 * Fb)) == 0)

# ===========================================================================
hr("W6 — NON-VACUITY GUARD on the route's S5 momenta / second variation")
# ===========================================================================
L_src_proper = sp.Rational(1, 2) * s_s * Wr * f**2 * sqrtmg / r**2
L_total = L_C1 + L_flux + L_src_proper
om = sp.Function("omega_fl", real=True)(r, th)
e1 = sp.Symbol("e1", real=True)
var1_w = sp.diff(L_total.subs(v, v + e1 * om), e1).subs(e1, 0).doit()
var1_q = sp.diff(L_total.subs(q, q + e1 * om), e1).subs(e1, 0).doit()
check("first w-variation with EXPLICIT fluctuation: NONZERO (not "
      "vacuous) and contains NO derivative of the fluctuation — "
      "pi_w = dL/d(w_r) = dL/d(w_th) = 0 confirmed independently",
      sp.simplify(var1_w) != 0 and om.func not in diff_funcs(var1_w))
check("first q-variation with EXPLICIT fluctuation: NONZERO and "
      "fluctuation-derivative-free — pi_q = 0 confirmed independently",
      sp.simplify(var1_q) != 0 and om.func not in diff_funcs(var1_q))
var2_w = sp.diff(L_total.subs(v, v + e1 * om), e1, 2).subs(e1, 0).doit()
check("second w-variation with EXPLICIT fluctuation: NONZERO (the "
      "route's derivative-free d2L check was not vacuous) and contains "
      "NO derivative of the fluctuation — zero gradient stiffness, zero "
      "DtN content for w (claim 1 S_phi0/DtN leg)",
      sp.simplify(var2_w) != 0 and om.func not in diff_funcs(var2_w))
# agreement of the route's Derivative-atom method with the explicit one
check("route's method cross-validated: dL/d(Derivative(v, r)) and the "
      "explicit-fluctuation variation agree (both give zero momentum)",
      sp.simplify(sp.diff(L_total, sp.Derivative(v, r))) == 0
      and sp.simplify(sp.diff(L_total, sp.Derivative(v, th))) == 0
      and sp.simplify(sp.diff(L_total, sp.Derivative(q, r))) == 0)
# route S7 q=0 joint-force claim re-derived
joint_w = sp.simplify(sp.diff(L_C1 + L_flux, v).subs(q, 0))
check("route S7 re-derived: at q = 0 the joint (C1 + flux) w-force = "
      "+(c/4) sin(th) f_th^2/(f v^3) exactly (flux adds nothing on the "
      "diagonal class; diagonal-point sign, q*-branch sign lives in W1)",
      sp.simplify(joint_w - (cc / 4) * sth * sp.diff(f, th)**2
                  / (f * v**3)) == 0)

# ===========================================================================
hr("W7 — STATICS PREMISE: time-dependent fields (T, r, theta)")
# ===========================================================================
fT = sp.Function("f", positive=True)(T, r, th)
qT = sp.Function("q", real=True)(T, r, th)
vT = sp.Function("v", positive=True)(T, r, th)
gT = sp.zeros(4, 4)
for (a, b, val) in [(0, 0, -fT), (1, 1, 1 / fT), (1, 2, qT),
                    (2, 2, r**2 * vT**2), (3, 3, r**2 * sth**2 / vT**2)]:
    gT[a, b] = val
    gT[b, a] = val
gTinv = gT.inv()
sqrtmgT = sp.sqrt(sp.factor(-gT.det()))
F0upT = gTinv * F0 * gTinv
L_flux_T = -(sp.Rational(1, 4) / mu) * sqrtmgT * sum(
    F0[i, j] * F0upT[i, j] for i in range(4) for j in range(4))
L_src_T = sp.Rational(1, 2) * s_s * Wr * fT**2 * sqrtmgT / r**2
phiT = -sp.log(fT) / 2
L_C1_T = -(cc / 2) * fT * sqrtmgT * sum(
    gTinv[i, j] * sp.diff(phiT, coords[i]) * sp.diff(phiT, coords[j])
    for i in range(4) for j in range(4))
check("NONSTATIONARY fields: flux density still zeroth-jet — no d_T of "
      "any metric function enters (the time-row extension IS structural "
      "for the flux)",
      diff_funcs(L_flux_T) == set())
check("NONSTATIONARY fields: source density still zeroth-jet",
      diff_funcs(L_src_T) == set())
check("NONSTATIONARY fields: C1 differentiates f only (now including "
      "f_T) — still no dw, dq, any order",
      diff_funcs(L_C1_T) == {fT.func})

# ===========================================================================
hr("SUMMARY")
# ===========================================================================
print(f"  verifier2 checks run: {NCHECK}")
if FAILURES:
    print(f"  {len(FAILURES)} CHECK(S) FAILED:")
    for lab in FAILURES:
        print(f"    - {lab}")
    sys.exit(1)
print("""  All verifier2 checks PASSED.

  Adjudicated verdicts, defects, and the weld/inventory adjudication are
  in the verifier report (returned to the session, to be folded into
  w_stiffness_results.md per verifier-before-record).  Headlines:
  - claims 1, 4 CONFIRMED;  claim 2 AMENDED (re-scope: 'banked ACTION
    stack, statics' — the nonstationary rung-2 weld constraint carries
    d_t K, a derivative of an angular-block amplitude, but is a derived
    constraint identity / partial import, not an action sector; K = 0 is
    forced on the native branch by the perturbed R-areal canon);
  - claim 3 CONFIRMED at density level, AMENDED for any on-shell
    reading: at q != 0 the on-shell w-force gains an O(q^2)
    response-screening term (W4e) OPPOSITE in sign to the tadpole — the
    tadpole is the exact density-level force but NOT the complete
    on-shell force at its own leading order;  and the 'opposition' to
    the C1 q*-branch force is Delta > 0 branch-conditional (W1);
  - claim 5 CONFIRMED (inventory sweep found no missed banked action
    piece; welds, symplectic gluing, seal bookkeeping, W_ff are
    constraint/bookkeeping/derived objects);
  - the dual-potential theorem (W4d) CLOSES the re-solving loophole at
    density level to ALL orders in q: the on-shell flux density carries
    no local angular-block derivatives in any rep; Q_f is topologically
    protected (W4c); the O(q) source carries df, dq only (dv enters at
    O(q^2), so nonlocal dw-dependence of the on-shell action starts at
    O(q^3)); the w-w response kernel has order-zero symbol (no gradient
    stiffness — argument-grade, consistent with W2 Arm-2's
    potential-only second variation).""")
