def main() -> None:
    print("operator selection variational test")
    print("=" * 37)
    print("For the spatial collar metric:")
    print("  dl^2 = d rho^2 + r(rho)^2 dOmega^2")
    print()
    print("A scalar Dirichlet energy probe has radial mode energy:")
    print("  E_l[a] = 1/2 integral [r^2 a'^2 + l(l+1) a^2] d rho")
    print()
    print("The Euler-Lagrange equation is:")
    print("  (r^2 a')' = l(l+1) a")
    print()
    print("On shell:")
    print("  r^2 a'^2 + l(l+1) a^2 = (r^2 a a')'")
    print("so:")
    print("  E_l,on-shell = 1/2 [r^2 a a']_boundary")
    print()
    print("Therefore:")
    print("  bulk harmonic elimination selects the DtN boundary kernel.")
    print()
    print("For banked P_phi0, ell=1, self-similar UDT collar:")
    print("  DtN gives K_warped|_{ell=1} = sqrt(2) B I_3")
    print("  B = I_{7/2}(6 sqrt(2)) / I_{5/2}(6 sqrt(2))")
    print()
    print("The intrinsic L1 = I_3 branch remains possible only if the")
    print("phi0 action is an interface-local boundary action rather than")
    print("the on-shell eliminated bulk collar energy.")


if __name__ == "__main__":
    main()
