def main() -> None:
    print("phi0 intrinsic S0 operator classification")
    print("=" * 48)
    print("At phi0, the intrinsic angular metric is:")
    print("  h_AB = R^2 omega_AB")
    print()
    print("A local rotationally invariant quadratic S0[a] with up to")
    print("two angular derivatives has the form:")
    print("  S0[a] = 1/2 alpha <a,a> + 1/2 beta <a, -R^2 Delta_S2 a>")
    print()
    print("On a spherical harmonic sector ell:")
    print("  S0 eigenvalue = alpha + beta ell(ell+1)")
    print()
    print("If the interface action must be blind to the constant mode:")
    print("  ell=0 eigenvalue = alpha = 0")
    print()
    print("Then the lowest nonconstant sector ell=1 has:")
    print("  S0 eigenvalue = 2 beta")
    print("  normalized L1 = (-R^2 Delta_S2)/2")
    print("  L1|_{ell=1} = I_3")
    print()
    print("No-approximation verdict:")
    print("  Intrinsic phi0 locality plus rotational invariance selects a")
    print("  small operator family. Adding constant-mode blindness selects")
    print("  the angular Laplacian branch, but not its coefficient.")


if __name__ == "__main__":
    main()
