def main() -> None:
    print("self-similar warped DtN solution")
    print("=" * 36)
    print("Use dimensionless y=r/R and a self-similar collar:")
    print("  f = y^(-q)")
    print()
    print("The harmonic angular-mode equation is:")
    print("  a_yy + (2-q/2) a_y/y - l(l+1) y^(q-2) a = 0")
    print()
    print("Set:")
    print("  beta = q/2")
    print("  x = sqrt(l(l+1)) y^beta / beta")
    print("  c = 2/q")
    print("  m = (1-c)/2 = (1-2/q)/2")
    print("  nu = |m|")
    print()
    print("Then the exact solution is:")
    print("  a(y) = x^m [A I_nu(x) + B K_nu(x)]")
    print()
    print("For 0<q<1/2, finite endpoint behavior selects:")
    print("  B = 0")
    print("  a_finite(y) = x^m I_nu(x)")
    print()
    print("Exact boundary logarithmic derivative at y=1:")
    print("  d ln a / d ln y = beta [m + x I_nu'(x)/I_nu(x)] at x=x0")
    print("  x0 = sqrt(l(l+1))/beta = 2 sqrt(l(l+1))/q")
    print()
    print("For the finite branch with nu=-m:")
    print("  d ln a / d ln y = beta x0 I_{nu+1}(x0)/I_nu(x0)")
    print()
    print("DtN verdict:")
    print("  The self-similar UDT warped collar has an exact DtN expression,")
    print("  but it is a Bessel-ratio boundary map, not the product-cylinder")
    print("  value sqrt(L).")


if __name__ == "__main__":
    main()
