def main() -> None:
    print("ell=1 self-similar DtN exact formula")
    print("=" * 43)
    print("For banked P_phi0:")
    print("  q = 1/3")
    print("  beta = q/2 = 1/6")
    print()
    print("For ell=1:")
    print("  l(l+1) = 2")
    print("  x0 = sqrt(2)/beta = 6 sqrt(2)")
    print("  m = (1-2/q)/2 = -5/2")
    print("  nu = 5/2")
    print()
    print("Finite endpoint branch:")
    print("  a(y) = x^(-5/2) I_{5/2}(x)")
    print("  x = 6 sqrt(2) y^(1/6)")
    print()
    print("Exact dimensionless boundary derivative:")
    print("  D_1 = d ln a / d ln y |_{y=1}")
    print("      = sqrt(2) I_{7/2}(6 sqrt(2)) / I_{5/2}(6 sqrt(2))")
    print()
    print("Product-cylinder DtN comparison:")
    print("  D_product = sqrt(2)")
    print()
    print("Exact ratio:")
    print("  D_1 / D_product = I_{7/2}(6 sqrt(2)) / I_{5/2}(6 sqrt(2))")
    print()
    print("No-approximation verdict:")
    print("  The exact self-similar UDT warped DtN map does not collapse")
    print("  algebraically to the product value unless this Bessel ratio equals 1.")
    print("  It should not be replaced by sqrt(2) or L1 without a separate")
    print("  boundary-action argument.")


if __name__ == "__main__":
    main()
