def main() -> None:
    print("half-split symmetry scope audit")
    print("=" * 34)
    print("The exact half split follows from:")
    print("  w_left + w_right = B")
    print("  w_left = w_right")
    print("  therefore w_left = w_right = B/2")
    print()
    print("Where side symmetry is native:")
    print("  intrinsic phi0 angular geometry")
    print("  h_AB = R^2 omega_AB")
    print("  normalized angular spectrum is common to both phi signs")
    print()
    print("Where side symmetry is not automatic:")
    print("  literal radial/bulk DtN through the collar")
    print("  flat exterior has q_out = 0")
    print("  negative-phi interior has q_in != 0")
    print()
    print("Therefore:")
    print("  intrinsic interface-local action can justify the half split if")
    print("  the two sides share one angular boundary action.")
    print("  bulk DtN propagation cannot use the half split unless its two")
    print("  one-sided kernels are proven symmetric or deliberately normalized.")
    print()
    print("No-approximation verdict:")
    print("  eta/2 is exact for a symmetric interface-local boundary action.")
    print("  It is not automatically exact for an asymmetric radial bulk-DtN bridge.")


if __name__ == "__main__":
    main()
