def main() -> None:
    print("derivative-dependent activation test")
    print("=" * 39)
    print("Candidate needed for s(q)=q/3:")
    print("  V = (q/6) f^2")
    print("with:")
    print("  q = -r f'/f")
    print()
    print("Substitute:")
    print("  V = -(r/6) f f'")
    print()
    print("But:")
    print("  r f f' = (r/2)(f^2)'")
    print("          = (1/2)(r f^2)' - (1/2) f^2")
    print()
    print("So:")
    print("  V = -(1/12)(r f^2)' + (1/12) f^2")
    print()
    print("Up to a boundary term, this is:")
    print("  V_eff = (1/12) f^2")
    print()
    print("That corresponds to a fixed source:")
    print("  dV_eff/df = f/6")
    print("  s = 1/6")
    print()
    print("No-approximation verdict:")
    print("  The naive derivative substitution V=(q/6)f^2 does not produce")
    print("  the intended self-coupled source. Up to a boundary term it becomes")
    print("  a fixed s=1/6 potential, which selects the non-finite companion branch.")


if __name__ == "__main__":
    main()
