def main() -> None:
    print("P_domain from Dirichlet principle")
    print("=" * 33)
    print("Scalar residual variable:")
    print("  y = ln h")
    print()
    print("Elementary relative boundary class:")
    print("  y(endpoint)=0")
    print("  y(phi0)=0")
    print()
    print("Residual scalar energy:")
    print("  E[y] = integral_I (y')^2 dt")
    print()
    print("Variation with fixed endpoint values:")
    print("  delta E = -2 integral_I y'' delta y dt")
    print("  boundary term vanishes because delta y=0 at both ends")
    print()
    print("Euler-Lagrange equation:")
    print("  y''=0")
    print()
    print("Unique minimizer in the relative class:")
    print("  y=0")
    print("  E_min=0")
    print()
    print("Any nonzero h residual has:")
    print("  E[y] > 0")
    print("  positive relative scalar excitation")
    print()
    print("Angular H1 carrier:")
    print("  omega_H1=dOmega_S2 is a harmonic angular representative, not a")
    print("  relative scalar residual.")
    print()
    print("Conclusion:")
    print("  If elementary phi0 mass emergence is the least-action representative")
    print("  in its fixed relative scalar boundary class, P_domain follows:")
    print("    keep H1 harmonic area carrier")
    print("    kill h residual")
    print()
    print("Remaining assumption:")
    print("  elementary means least-action/harmonic representative, not an excited")
    print("  relative scalar boundary-layer state.")


if __name__ == "__main__":
    main()
