"""This campaign's byte/scope checks only; not mathematical proof or promotion."""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = Path(__file__).resolve().parent.relative_to(ROOT).as_posix()
BASE = '5e022dff9346707563bed18b4ed7dd4150ab2b94'
CONTEXT = {'LIVE.md', 'HANDOFF.md', 'CURRENT_RESEARCH_PROGRAM.md',
           'CURRENT_SCIENTIFIC_PREMISES.md', 'INDEX.md', 'MEMORY.md'}

def git(*args):
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True,
                          check=True, timeout=15).stdout

def digest(data):
    return hashlib.sha256(data).hexdigest()

manifests = []
for step in range(1, 4):
    folder = f'{PKG}/step_{step:02d}'
    manifests += [f'{folder}/SOURCE_SHA256SUMS', f'{folder}/CANDIDATE_SHA256SUMS']
manifests += [f'{PKG}/step_01/review/STAGE_A_SHA256SUMS',
              f'{PKG}/step_01/review/REVIEW_SHA256SUMS',
              f'{PKG}/step_02/review/STAGE_A_SHA256SUMS.stdout',
              f'{PKG}/step_02/review/REVIEW_SHA256SUMS.stdout',
              f'{PKG}/step_03/review/STAGE_A_SHA256SUMS.stdout',
              f'{PKG}/step_03/review/source_hashes.stdout',
              f'{PKG}/step_03/review/direct_source_hashes.stdout']
# Require exactly one direct RC3 seal; do not silently skip a missing review.
rc3_options = [f'{PKG}/step_03/review/REVIEW_SHA256SUMS',
               f'{PKG}/step_03/review/REVIEW_SHA256SUMS.stdout']
rc3_seals = [name for name in rc3_options if (ROOT/name).is_file()]
assert len(rc3_seals) == 1, ('RC3 final review seal', rc3_seals)
manifests += rc3_seals
records = []
for manifest in manifests:
    lines = (ROOT/manifest).read_text().splitlines()
    seen = set()
    historical = []
    for line in lines:
        expected, relative = line.split(maxsplit=1)
        assert relative not in seen, ('duplicate', manifest, relative)
        seen.add(relative)
        path = Path(relative)
        assert not path.is_absolute() and '..' not in path.parts
        if relative in CONTEXT:
            actual = git('show', f'{BASE}:{relative}')
            historical.append(relative)
        else:
            actual = (ROOT/path).read_bytes()
        assert digest(actual) == expected, ('hash mismatch', manifest, relative)
    records.append({'manifest': manifest, 'sha256': digest((ROOT/manifest).read_bytes()),
                    'entries': len(lines), 'historical_CONTEXT_only': historical})

unchanged = ['CURRENT_SCIENTIFIC_PREMISES.tsv', 'CANON.md',
             'UDT_METRIC_KERNEL_DEVELOPMENT.md', 'UDT_METRIC_KERNEL_COVERAGE.tsv',
             'AGENTS.md', 'CLAUDE.md', 'CROSS_MODEL_VERIFY.md',
             'verify_current_scientific_premises.py', 'tests/test_startup_surface.py']
fixed_hashes = {}
for relative in unchanged:
    current = (ROOT/relative).read_bytes()
    assert current == git('show', f'{BASE}:{relative}'), ('changed source', relative)
    fixed_hashes[relative] = digest(current)

changed = git('diff', '--name-only', BASE, '--').decode().splitlines()
assert all(name in CONTEXT or name.startswith(PKG+'/') for name in changed), changed
assert git('branch', '--show-current').decode().strip() == 'grok'
assert not git('diff', '--check', BASE, '--', *sorted(CONTEXT))
baseline = json.loads((ROOT/PKG/'PRESERVATION_METADATA.json').read_text())
status = git('status', '--short', '--untracked-files=normal').decode().splitlines()
outside = sorted(line for line in status if line.startswith('?? ')
                 and not line[3:].startswith(PKG+'/'))
assert outside == baseline['untracked_status_lines'], 'untracked PATH metadata changed'
assert len(outside) == 46
cache = f'{PKG}/__pycache__/tensor_geometry.cpython-310.pyc'
assert not git('ls-files', '--', cache), 'generated bytecode still tracked'
# Only local presence, not content inspection, is needed for retained cache bytes.
assert (ROOT/cache).is_file()
print(json.dumps({'status': 'PASS', 'scope': 'CORRESPONDENCE_NOT_PROOF',
 'baseline': BASE, 'head_at_check': git('rev-parse', 'HEAD').decode().strip(),
 'manifests': records, 'unchanged_source_hashes': fixed_hashes,
 'changed_paths': changed, 'unrelated_untracked_metadata_count': len(outside),
 'protected_bytes': 'NOT_INSPECTED', 'backup_completeness': 'UNVERIFIED',
 'pre_reboot_unsaved_state_disposition': 'UNVERIFIED',
 'generated_bytecode': 'UNTRACKED_LOCAL_BYTES_RETAINED'}, indent=2))
