"""Packaging-only source readiness ledger; no scientific source modifications."""
from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[2]
D=Path(__file__).resolve().parent
rows=[]
def add(cid,pkg,step,statement,assumptions,existing,candidates,methods,excluded,history,files,replays):
 base=pkg+('/'+step if step else '')
 artifacts=[]
 for role,names in files.items():
  for n in names:
   p=R/base/n;assert p.is_file(),p
   artifacts.append(dict(role=role,path=str(p.relative_to(R)),sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
 rows.append(dict(candidate=cid,disposition='PROMOTE_EXACT_REVIEWED_CONDITIONAL_MATHEMATICS',proposed_grade=['BANKED_DERIVED_CONDITIONAL','VERIFIED-WITH-CAVEATS','NOT_PHYSICAL_ADOPTION','NOT_CANON'],statement=statement,assumptions=assumptions,required_existing_source_ids=existing,required_candidate_dependencies=candidates,methods_or_controls_not_separate_physical_premises=methods,excluded_inferences=excluded,review_and_repair_history=history,controlling_artifacts=artifacts,replay_labels=replays,unresolved_scientific_objections=[],remaining_integration_gates=['Parent current premise audit attribution and source preservation','Exact-scope banking/registry integration fidelity review'],current_gr_filter_qualification='Any inherited active/admitted/lawful Einstein claim is conditional on the full reviewed equation and class premises. Current G312 GR filter alone does not force Ricci response; its reviewed class-membership route remains UNCLOSED. DDR/Local Metric Sufficiency remain owner-provisional, not canon.'))
N='udt_nonlinear_mode_realizability_campaign_2026-09-09'
add('NR1',N,'step_01',
'Necessary quadratic obstruction Q=v_c dot u_s-v_s dot u_c=0, equivalently sum_p(A_c,p B_s,p-A_s,p B_c,p)=0, for exact realizability of the G327 eight-real-parameter tangent on every fixed supplied G324 compact split quotient.',
['Fixed T0>0; both time branches, phases and polarizations retained.','Exact families have sufficient mixed C2 dependence of the fields and required spatial derivatives on a common neighborhood of the whole compact slice.','All second-order fields and connected Lambda(epsilon) variations are allowed; legal periodic gauge does not change the obstruction.'],
['G303','G315','G324','G327'],[],['Compact second-variation momentum pairing','G325/G326 are not required scientific inputs'],
['Q=0 is not sufficient in NR1 alone.','No necessity for nonsmooth families, nonperiodic gauges, different quotient/domain or arbitrary modes.','Two polarizations may cancel; do not impose separate polarization obstructions.'],
['Fresh original source-first then exposed adversarial review; exact runtime model UNKNOWN, different-model untested.','One incomplete harmonic-support reviewer false pass is excluded; complete follow-up retained and replayed.','Reviewer exploratory right-inverse construction is not a downstream accepted lemma.','Parent structural check totals do not independently prove the theorem.'],
{'candidate':['INITIAL_CANDIDATE.md'],'reviewed_result':['REVIEWED_RESULT.md'],'review':['review/STAGE_A_INDEPENDENT.md','review/ADVERSARIAL_REVIEW.md']},['nr1_author','nr1_adm','nr1_harmonic'])
add('NR2',N,'step_02',
'Within the exact G327 tangent sector, Q=0 if and only if the tangent admits the reviewed exact local realization: NR1 gives mixed-C2 necessity, and every fixed Q=0 tangent has a jointly analytic parameter/spacetime exact Einstein family on a common local slab around the whole supplied compact slice.',
['Fixed compact split quotient and T0>0; positive determinant-one metric chart and dual K pairing.','For each fixed tangent choose epsilon0>0 and delta>0; no uniform choice over all amplitudes or endpoint limits.','Both arbitrary analytic c(epsilon)=O(epsilon^2) and Lambda(epsilon)=O(epsilon^2) are included at the reviewed scope; each Lambda is spacetime constant.','All constraints, auxiliary consistency, Bianchi propagation, compact gluing and linear tangent uniqueness remain load-bearing.'],
['G303','G315','G324','G327'],['NR1'],['Analytic noncharacteristic Cauchy-Kowalevski method, not new field law','G321 is method precedent, not an additional physical dependency','NR1 exploratory right inverse and incomplete-support false pass are excluded'],
['No arbitrary-mode integrability classification.','No smooth/Sobolev nonlinear stability or uniform amplitude/lifetime result.','Do not replace full Einstein evolution by only the spatial Ricci equations.'],
['Fresh original source-first and exposed direct review, same SymPy foundation; independent implementation uses an equivalent chart, not a different chart.','Initial 30-predicate output retained; later pre_bianchi_check.py is a reconstruction without a pre-run hash and cannot recover original chronology.','Explicit Bianchi/consistency completion and final reviewed argument control; historical full365/G325 failures are not current scientific blockers.','Runtime model UNKNOWN; different-model and formal/human review untested.'],
{'candidate':['INITIAL_CANDIDATE.md'],'reviewed_result':['REVIEWED_RESULT.md'],'history':['DISCOVERY_HISTORY.md'],'review':['review/STAGE_A_INDEPENDENT.md','review/ADVERSARIAL_REVIEW.md','review/SUMMARY_FIDELITY_REVIEW.md']},['nr2_author','nr2_evolution'])
L='udt_localized_geometry_campaign_2026-09-09'
add('LG1',L,'step_01',
'The complete local constraint-adjoint kernel on each connected embedded ball or annular collar of the supplied Taub slice has zero lapse and the three translations plus y partial_z-z partial_y; on the full-rank compact torus only the three translations descend. This gives necessary linear-source pairings and exact finite and mixed-C2 tangent balances for supported completions matching both metric and K outside.',
['gamma0=I and K0=diag(1,-2,-2)/(3T0), T0>0.','Full tensor Lie derivative/density pairing, connected local domain, legal compact quotient.','Exact supported completion agrees in BOTH gamma and K on its exterior.'],
['G303','G315','G324'],[],['KID/constraint-adjoint correspondence with checked hypotheses','NR1/NR2 motivate the question but are not scientific dependencies'],
['No sufficient gluing theorem.','A nonzero interior charge may be cancelled in a collar; it is not a universal no-go.','Do not replace the four-dimensional local kernel by the three-dimensional global torus kernel.'],
['Fresh source-first then direct review; original runtime model UNKNOWN and different-model untested.','Reviewer printed zero_residuals:18 is an inaccurate hardcoded count and is excluded; underlying checked residuals remain valid.'],
{'candidate':['CANDIDATE.md'],'review':['review/SOURCE_FIRST.md','review/DIRECT_REVIEW.md']},['lg1_author','lg1_adjoint'])
add('LG2',L,'step_02',
'For every fixed permitted T0, nested radii, cutoff and sufficiently high finite norm, all sufficiently small nonzero prescribed diagonal reflection-invariant Kasner interior parameters u admit a smooth exact global constraint completion on the same compact quotient, with the fixed Taub exterior, positive metric and Lambda=0. Its local Einstein development is not locally Taub in the inserted core.',
['0<|u|<min(u_star,0.1), with u_star depending on the frozen construction.','Both boundaries require smooth zero extension.','Use the exact nonlinear source covector J_i=-2 M_i before taking its derivative.','Chrusciel-Delay projected inverse is relative to a fixed reference kernel; decaying variational weight and growing output norm are distinct.','Eight reflections remove the fixed subspace of all four local KIDs.'],
['G303','G315','G324'],['LG1'],['Local deformation theorem with checked function spaces and hypotheses','Complex Weyl invariant separation','No new physical source or boundary law'],
['No arbitrary interior matching, quantitative u_star, uniform shrinking-domain norms or all-completion uniqueness.','No all-time exact exterior or stability.','Central inversion alone does not remove the rotational KID.','Raw cutoff data are not exact constraint data.','Raising the momentum index with the varying metric changes the off-constraint derivative and cannot replace repaired J.'],
['One focused scientific repair is mandatory: CANDIDATE.md together with REPAIR.md is the controlling result.','Initial direct-review defect and subsequent acceptance both retained.','Fresh original source-first context; runtime model UNKNOWN/different-model untested.'],
{'candidate':['CANDIDATE.md'],'repair':['REPAIR.md'],'review':['review/SOURCE_FIRST.md','review/INITIAL_DIRECT_REVIEW.md','review/DIRECT_REVIEW.md','review/SUMMARY_FIDELITY.md']},['lg2_author','lg2_repair'])
add('LE1','udt_localized_evolution_followup_2026-09-09','',
'Every actual smooth full-constraint completion sharing the lawful LG2 core, in every local globally hyperbolic development, has a datum/development-dependent positive common Kasner neighborhood of each compact core subball. There Kretschmann=-16 P/T^4 strictly decays while the full self-dual Weyl anisotropy A=1-6 I3^2/I2^3=u^2(u^2-3)^2/(1+u^2)^3 stays positive and constant; Taub has A=0.',
['Nonzero reviewed LG2 u range, actual completion and actual local development.','Diagnostic uses full Q=E+iB, not E alone.','Explicit |x|+L_p(T)<r is restricted to the intersection with the actual common development.'],
['G303','G315','G324'],['LG2'],['Local Cauchy uniqueness/domain of dependence','Known Kasner formulas are checked applications, not novelty claims'],
['No uniform lifetime, long-time persistence, collar conclusion or metric-distance estimate.','Curvature decay does not make this invariant anisotropy decay.'],
['Fresh original source-first/direct review. Two reviewer power-normalization failures remain preserved; continuation repaired reviewer calculation without changing candidate science.','Full rank-four boost check catches an E-only false invariance.','Runtime model UNKNOWN; no new independent derivation is claimed by this banking replay.'],
{'candidate':['CANDIDATE.md'],'review':['review/SOURCE_FIRST.md','review/DIRECT_REVIEW.md','review/FINAL_FIDELITY.md']},['le1_author','le1_boost'])
add('SE1','udt_spatial_curvature_evolution_2026-09-09','',
'For sufficiently regular actual local Einstein evolution and I2!=0, the reviewed oriented Gaussian/Fermi convention gives W=2 tau Q-3(KQ)_symTF-i curl Q and n(A)=36 I3[I3 tr(QW)-I2 tr(Q^2 W)]/I2^4. The explicit lawful analytic compact m=0 and m=1 data have identical pointwise gamma,K,Q and first metric/K jets at x=0 but rates 0 and -5930496/5764801; a nonflat comparator has positive rate 68040/28561.',
['Supplied future normal, orientation, Gaussian initial slice and Fermi frame.','I2!=0 and full self-dual Q diagnostic.','Matched example q=e cos(mx), e=1/6, gamma=I, K=diag(1/3-3q^2/4,-2/3-q,-2/3+q); nonflat comparator e=1/9 at its reviewed point.','Actual analytic Cauchy development, not merely formal initial jets.'],
['G303','G315'],['LE1','NR2:analytic development method only'],['Bianchi and analytic local Cauchy methods','NR2 tangent iff theorem is not required for these separately solved data'],
['Instantaneous zero derivative is only scalar stationarity; I3=0 is a diagnostic blind spot, I2=0 excluded.','No universal sign, full geometry classification or full-Cauchy-data nonuniqueness.','The matched fields differ away from the point.'],
['PROVENANCE_CORRECTION.md and reviewer PROVENANCE_FOLLOWUP.md are mandatory.','Author check_geometry.py was written after reviewer SF3 witness communication; original pre-exposure-code claim withdrawn. Hand reasoning was unfrozen.','Reviewer contributed the final witness, then independently extracted comparators: not blind construction independence.','No scientific repair; runtime model UNKNOWN/different-model untested.'],
{'candidate':['CANDIDATE.md'],'provenance_correction':['PROVENANCE_CORRECTION.md'],'review':['review/SOURCE_FIRST.md','review/DIRECT_REVIEW.md','review/PROVENANCE_FOLLOWUP.md','review/FINAL_FIDELITY.md']},['se1_geometry','se1_matched','se1_bianchi','se1_tensor'])
add('NE1','udt_nonlinear_ripple_geometry_2026-09-09','',
'The supplied polarized one-plus-cosine compact T3 data have the explicit exact smooth Lorentzian Einstein development on t>0 in the reviewed Gowdy/Bessel form, with complete original Ricci and initial-data matching and the G327 plus-cosine linear limit. For each fixed nonzero epsilon, P=O(t^-1/2) uniformly tends to zero, but lambda=lambda0+epsilon^2 sigma t+O(1), sigma>0; at equal supplied marked T2 orbit area, H_rho/H_rho0 tends uniformly to zero and the relative tidal contrast has alternating unbounded subsequences.',
['Supplied split compact quotient, Lambda=0 and original unit-metric data.','Exact construction covers every finite real epsilon at its reviewed scope; asymptotic comparison fixes epsilon!=0.','Matched orbit-area marking and areal normal are part of the comparison.','The Cauchy proof quantifies over inextendible causal curves.'],
['G303','G315','G327'],['SE1:initial datum provenance only'],['Explicit metric reduction and Bessel asymptotics','NR2 is not the existence input; LG2 is not an input'],
['No absolute curvature blowup, generic nonlinear stability/instability theorem or unmarked all-isometry comparison.','H_rho is not the volume expansion; later areal normal is not Gaussian normal.','Finite floating witnesses are not certified asymptotics.'],
['Original initial candidate plus REVIEWED_RESULT inextendibility clarification control.','Fresh source-first/direct review; independent implementation shares SymPy/mpmath and analytic foundations.','Actual hostile mutations/failures preserved; no substantive scientific repair required.','Runtime model UNKNOWN/different-model untested.'],
{'candidate':['INITIAL_CANDIDATE.md'],'reviewed_result':['REVIEWED_RESULT.md'],'review':['review/SOURCE_FIRST.md','review/DIRECT_REVIEW.md','review/FIDELITY_REVIEW.md']},['ne1_metric','ne1_profile','ne1_tidal'])
H='udt_hopfion_bridge_stability_reassessment_2026-09-08'
add('HB2',H,'step_02',
'For the unscaled positive-weight G331/G332 family on its global strict square-root and simple-Ricci-gap domain, both root branches give Y=5 A(grad R)/(2 Delta D0) and normal projector drift Pdot=Y tensor eta+xi tensor Yflat, Delta=(6-R)/2 and D0=b+C. Unequal weights give nonzero interior-torus drift and zero axis drift; equal nonround weights give zero initial drift.',
['All compatible C,Lambda and both signed roots/gaps retained.','Full inverse-metric and unit-normalization variations are included.','Actual smooth local Cauchy development and continued simple Ricci branch are conditional.'],
['G315','G330','G331','G332','G337'],[],['G330/G303 general Cauchy/isometry extension method; no automatic enlargement of pure-trace source theorem','HB1 source assessment and G321 method interface are not extra scientific dependencies'],
['No orbit-closure, stability, topology or physically adopted carrier conclusion from a first jet.','No recertification of old no-null carrier or reopening paused mass/stability mechanisms.','Gap-closing endpoint fixtures are controls outside the theorem domain.'],
['Fresh original source-first then exposed direct review; runtime model UNKNOWN.','Author imports accepted G337 variation engine; reviewer independently used Killing-divergence and toric-block routes.','Initial full-symbolic 60-second timeout retained, never a pass.','Two manual argv sidecars normalize paths; automatic JSON has authoritative literal argv.','Historical source/status-pin repairs preserve original science.'],
{'candidate':['CANDIDATE_INITIAL.md'],'reviewed_result':['REVIEWED_RESULT.md'],'freeze':['CANDIDATE_FREEZE.md'],'review':['review/SOURCE_FIRST_ARGUMENT.md','review/SOURCE_FIRST_SCALAR_ADDENDUM.md','review/REVIEW_RECORD.md','review/COMMAND_PROVENANCE.md']},['hb2_author','hb2_matched'])
add('HB3',H,'step_03',
'In the same strict HB2 family, complete-data T2 and simultaneous-conjugation symmetries preserve the angular simple Ricci line. For unequal weights, qdot=-120 w1(w1-w2)/(w2 Delta D0) is nonconstant in latitude; for every sufficiently small nonzero positive or negative time there are tori with closed leaves and other tori with dense nonclosed leaves. For equal nonround weights U2 symmetry preserves the Hopf line locally: all-closed persistence in this exact class holds iff the weights are equal.',
['Same strict global square-root/simple-gap domain, both root branches.','General local Cauchy uniqueness and complete-data isometry extension.','The tori may depend on time; the quantifier is existence at each sufficiently small nonzero time.','Denominator square is the nonconstant cubic (6-R)^2(R+2C^2-2Lambda)/2.'],
['G315','G330','G331','G332'],['HB2'],['Conditional Cauchy/isometry and rational/irrational linear-flow methods'],
['Not a statement about every fixed torus or every leaf.','Unequal rational initial Seifert cases have exceptional fibres and are not free Hopf bundles.','No topology change, stability, physical carrier/source law or old-carrier recertification.'],
['Fresh source-first/exposed direct reviewer, runtime model UNKNOWN.','Original dependency-pin failures and wrapper authentication failure are retained; finalization is a scoped hash/status repair, not changed science.','Python-build metadata changed in present replay only; scientific outputs match exactly.'],
{'candidate':['CANDIDATE_INITIAL.md'],'reviewed_result':['REVIEWED_RESULT.md'],'freeze':['CANDIDATE_FREEZE.md'],'dependency_finalization':['DEPENDENCY_HASH_FINALIZATION.md'],'review':['review/SOURCE_FIRST_ARGUMENT.md','review/REVIEW_RECORD.md','review/COMMAND_PROVENANCE.md']},['hb3_author','hb3_ratio'])
B='udt_berger_initial_data_preservation_campaign_2026-09-08'
add('BI2',B,'step_02',
'For every finite lawful left-invariant K on a fixed positive nonround Berger metric in the full BI1/G376 constraint quadric, complete-data symmetries yield an actual local homogeneous Einstein development. The original simple Ricci branch/projector and free Hopf circles, including absolute metric-period integral one, persist on a datum-dependent positive Gaussian interval while both complete gaps remain nonzero. Direct unaveraged horizontal metric descent through time zero holds iff the initial horizontal K block is scalar.',
['Use full G376 quadric, including both roots, zero and trace sectors and horizontal shear after initial SO2 diagonalization.','Track the ORIGINAL Ricci branch even if all three branches become simple.','Both gaps 4(x3-xj)(x3+xj-xk)/(x1 x2 x3) must remain nonzero.','Direct descent refers to the original unaveraged horizontal metric, not arbitrary quotient metrics.'],
['G315','G330','G376'],[],['General smooth Cauchy uniqueness/isometry extension; G337 underlies G376 full variation','BI3/HB results are not dependencies'],
['Shear causes departure of direct metric descent for all small nonzero times in both directions but does not destroy the circles.','Pure-trace K is not necessary.','No global lifetime, stability, physical carrier, topology change or exclusion of another quotient metric.'],
['First fresh reviewer accidentally saw a whiteboard log; preserved initial review is supplemented by a fresh focused source-first review with strict isolation.','Original two printed-control false passes (negated Ricci/gaps and all-true descent flags) are excluded and independently caught by saved-control correspondence.','Five actual author catches do not certify all output fields. Inherit G376/BI1 full-operator blind-spot limitations.','Present replay used an unchanged 33-input bounded copy of exposed_comparison.py because original writes EXPOSED_HASHES.json; original artifact bytes untouched.','Runtime model UNKNOWN, shared SymPy, different-model untested.'],
{'candidate':['CANDIDATE_INITIAL.md'],'reviewed_result':['REVIEWED_RESULT.md'],'freeze':['CANDIDATE_FREEZE.md'],'review':['review/SOURCE_FIRST_ARGUMENT.md','review/REVIEW_REPORT.md','focused_review/SOURCE_FIRST_ARGUMENT.md','focused_review/REVIEW_REPORT.md']},['bi2_author','bi2_focused','bi2_saved_comparison'])
add('BI3',B,'step_03',
'For every fixed positive nonround Berger gamma, marked point o, h!=0 and Lambda=R/2+3h^2, and every real epsilon, there is an actual analytic K on an epsilon-dependent local patch satisfying all exact constraints with that same gamma,Lambda and K(o)=h gamma, DK(o)=0, while the normal simple-Ricci-line drift is Y=epsilon e2/Delta and the mixed projector drift is epsilon/Delta. Nonzero epsilon gives actual marked short-normal departure under local Cauchy development.',
['Local analytic noncharacteristic constraint construction uses Hamiltonian elimination plus all three noncommuting momentum equations.','Fixed nonround simple gap; h!=0 is a parameterization restriction, not a general obstruction at h=0.','Marked point and normal continuation are supplied comparison data.'],
['G315','G330','G337','G376'],[],['Analytic Cauchy-Kowalevski and local Einstein Cauchy methods','BI2 mutation-driver reuse is a method/control, not a scientific dependency'],
['No global S3 gluing, global orbit/topology/stability or physical carrier result.','Bare polynomial jet is not an exact solution: residual -epsilon^2 u^4/2 remains the countercontrol.','Round case has no selected simple Ricci line.'],
['Fresh original source-first/direct review; independent different local e1 subfamily and full tensors.','Actual omit-2hB mutation passes 55 author checks but independent full Bdot diagonal detects it; mixed drift survivor unchanged. Inherit G376/BI1 false-pass exclusions.','Historical threaded git-lstat capture failure is operational; retained bounded capture repair changes no science.','Runtime model UNKNOWN/different-model untested.'],
{'candidate':['CANDIDATE_INITIAL.md'],'reviewed_result':['REVIEWED_RESULT.md'],'freeze':['CANDIDATE_FREEZE.md'],'review':['review/SOURCE_FIRST_ARGUMENT.md','review/REVIEW_REPORT.md']},['bi3_author','bi3_full'])
meta=dict(review_kind='Fresh scoped source-fidelity/readiness review with unchanged-code replay; not blind rederivation of all inherited science',reviewer='/root/bank_older_geometry',runtime_model_version='UNATTESTED',baseline_head='f5faabb43a582fec9a71c1d4a3b065efffae25bd',branch='grok',startup='Parent top-level startup attributed; reviewer independently checked branch/hash/status. Parent actual new prebank365 PASS 407.713s empty stderr, per parent message; not reviewer-owned.',source_first='Authority and source dependency assessment preceded proposed banking text; original author records and past verdicts deliberately exposed.',unchanged_originals='SOURCE_SNAPSHOT.json and ADDITIONAL_SOURCE_SNAPSHOT.json bind source payloads; final preservation receipt is separate.',grades_are_proposals=True,atomic_order=['G376 (BI1 already banked)','HB2','HB3','BI2','BI3','NR1','NR2','LG1','LG2','LE1','SE1','NE1'],already_banked=[{'candidate':'BI1','existing_id':'G376','disposition':'PREVIOUSLY_BANKED_DO_NOT_DUPLICATE','caveat':'Full G337-style operator and independent full tensor checks remain mandatory; author wrong-S-sign and missing derivative-index-connection mutants were false passes.'},{'existing_ids':['G377','G378','G379','G380','G381','G382'],'disposition':'PREVIOUSLY_BANKED_DIFFERENT_EXACT_CLAIMS','caveat':'Old pending/unpromoted headers in their original sources do not negate current banked status; they do not silently bank HB2/HB3/BI2/BI3.'}],candidates=rows)
(D/'CORE_READINESS.json').write_text(json.dumps(meta,indent=2)+'\n')
print('Wrote',len(rows),'exact core candidates; artifacts',sum(len(x['controlling_artifacts']) for x in rows))
