"""Package exact reviewed additions; no source science is edited."""
from pathlib import Path
import hashlib,json
D=Path(__file__).resolve().parent;R=D.parents[1]
def artifacts(base,groups):
 out=[]
 for role,files in groups.items():
  for f in files:
   p=R/base/f;assert p.is_file(),p
   out.append(dict(role=role,path=str(p.relative_to(R)),sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
 return out
qual='Any inherited Einstein/admitted/lawful vacuum wording is conditional on the full reviewed equation/class premises. Current G312 is GR filter only: response-class membership remains UNCLOSED; DDR/Local Metric Sufficiency owner-provisional, not canon.'
grade=['BANKED_DERIVED_CONDITIONAL','VERIFIED-WITH-CAVEATS','NOT_PHYSICAL_ADOPTION','NOT_CANON']
recipe=dict(candidate='ORIGINAL_CURVATURE_RECIPE',disposition='PROMOTE_PRECISE_ORIGINAL_REVIEWED_APPLICATION',proposed_grade=grade,
statement='For every real constant A!=0 on the supplied regular local G313 plane-wave patch g=-2du dv+dx^2+dy^2+A(x^2-y^2)du^2, the explicitly chosen Weyl plus FIRST-pair-dual quadratic recipe has full tensor B=4 A^2 du^tensor4. Its unique real future-raised fourth root is beta=-sqrt(2|A|)du when partial_v is future. It is parallel/null/closed and its raised current is conserved. The resulting local orbit-quotient amount is |dTheta| dx dy and, for the supplied finite-area labels and spacing Delta>0, mu=Delta dxdy realizes the chosen product and graph-cut observer readout Gamma=omega=-g(U,C).',
assumptions=['Exact coefficient-one sum of Weyl and first-dual contributions, BOTH inverse metrics and Hodge half-factor.','Constant real A, supplied time orientation and local regular patch; all future unit timelike auxiliary/measurement observers in their declared roles.','Finite-area transverse patch, phase/labels, cross-phase identification, positive spacing and cuts remain supplied query choices.','A=0 is separately recomputed: B and real root vanish, and the division-based extraction formula is invalid there.','Four operations remain distinct: passive coordinate rescaling, common positive affine phase/spacing gauge at FIXED current and measure, metric homothety, and changing the recipe coefficient.'],
required_existing_source_ids=['G313'],required_candidate_dependencies=[],comparison_source_ids=['G351','G352'],
methods_or_controls_not_separate_physical_premises=['Full metric curvature and differential geometry, exact bivector contraction and full coordinate tensor checks.','G351/G352 supply the comparison measure/readout definitions with owner-provisional physical interpretation; no old unpromoted current-representation result is required.','G355 is a later mathematical generalization, not the historical proof input.'],
excluded_inferences=['Chosen recipe and coefficient are not physically selected; root uniqueness is only for the fixed recipe/time orientation.','Area-valued geometric amount is not a dimensionless physical population/count; physical conversion and support remain open.','Conserved within-phase null flow does not select cross-phase labels.','No preferred scale/history, detector/source/energy/matter law, stability, global completion or extension to A(u).','G352 continuous product is not literal atomic counting or a general singular-measure construction.','At fixed current/measure phase gauge, the new phase gradient is rescaled and is no longer the same fixed-B root unless gauge factor is one.'],
review_and_repair_history=['Fresh original reviewer /root/curvature_phase_adversarial_review reconstructed from sources/work order before candidate exposure; independent full dense tensor implementation plus bivector argument.','Author received the short Stage A finding before final prose freeze; neither final prose nor exposed Stage B replay is outcome-independent of that communication.','No post-review scientific repair required. Prefreeze symbolic-domain failure at A=0 preserved; both nonzero real signs checked and flat case separately recomputed.','One orchestration output loss was followed by identical retained replay; original lost output and its chronology cannot be recovered from hashes.','Nine actual hostile mutations caught; grouped zero-differentials mutation stops at first exterior-derivative guard and is not a separate divergence-only mutation.','Exact original runtime model UNKNOWN, different-model/human/formal axes untested; shared SymPy.','Portable saved-artifact adapter authenticates original scripts and changes only two path bindings in memory; original old Stage B runner writes historic scratch and was not directly rerun.'],
prior_banking_relationship={'G353':'Explicitly leaves original c19b5fb1 recipe as a conditional dependency, NOT separately promoted.','G355':'Subsumes the full B/root/phase-closure result in its wider harmonic class, but does not by itself bank the complete original fixed-A quotient amount, arbitrary graph-cut/readout and four-operation application.','recommended_treatment':'Bank original precise application with explicit overlap/successor reference, avoiding any new physical selection claim.'},
controlling_artifacts=artifacts('udt_g313_curvature_phase_current_candidate_2026-09-06',{'candidate':['CANDIDATE_ARGUMENT.md'],'review':['REVIEW_RECORD.md','review_2026-09-06/STAGE_A_RECONSTRUCTION.md','review_2026-09-06/STAGE_B_ADVERSARIAL_REVIEW.md'],'history':['DISCOVERY_AND_EXPOSURE.md'],'replay_packaging':['replay_2026-09-06/PORTABILITY_NOTE.md','replay_2026-09-06/portable_saved_artifact_replay.py'],'saved_result':['AUTHOR_RESULT.json','WITNESS_INPUTS.json']}),
replay_labels=['recipe_author','recipe_independent'],unresolved_scientific_objections=[],current_gr_filter_qualification=qual)
rd=dict(candidate='RD1',disposition='PROMOTE_EXACT_CONDITIONAL_MATHEMATICS_WITH_PRACTICAL_RD2_STOP_RETAINED',proposed_grade=grade,
statement='RD1.1: On the declared full waveform Hilbert domain, BA_T=I, S=A_VB and uniform response/noise budgets with kappa<1 imply ||h|| <= (||By_T||+eta_B)/(1-kappa) and ||y_V-Sy_T|| <= rho (||By_T||+eta_B)/(1-kappa)+eta_r. Finite distinct evaluations of real whole-line L2 functions bandlimited to [-b,-a] union [a,b], 0<a<b, have positive-definite Gram and interpolate every real finite target with minimum norm squared v^T G^-1 v. RD1.2: For exact noiseless independent training and fixed norm cap, the sharp holdout interval radius is ||p|| sqrt(H_max^2-||h0||^2), with both endpoints attained, p=0 exact prediction and insufficient cap incompatibility. RD1.3: The supplied arm transfer formula satisfies |T-1| <= min(2,2|x|,|x mu|+(2/3)x^2(1+mu^2)) for all real x and |mu|<=1; the reviewed unit-arm and stationary whole-line Plancherel hypotheses yield the stated row/operator corollaries.',
assumptions=['All maps, full waveform/support domain, norms, disturbance class and budgets are supplied/frozen independently of reserved confirmation outcomes.','Uniform disturbances may be nonlinear; any probabilistic conclusion inherits only the specified joint event and its justified coverage.','Bounded left inverse and kappa<1 are sufficient, not necessary for every useful prediction-only quotient.','Point-sampling surjectivity is only the finite static model with distinct asynchronous geocentric sample times, nonzero nominal plus coefficients and no uniform waveform norm cap.','Sharp interval is the exact noiseless REAL Hilbert problem with independent training functionals and G=TT*>0.','Arm formula uses x=pi f L/c_E, sinc(z)=sin(z)/z; ideal unit arms and stationary whole-line frequency-to-L2 transfer are explicit hypotheses.','CO2 matrix/delay values are supplied nominal design data, not metrological certification.'],
required_existing_source_ids=[],required_candidate_dependencies=[],application_source_roles=[{'source':'G261/G313/current G312 qualification','role':'Conditional UDT/weak-wave geometric interpretation only; abstract Hilbert/interpolation/arm-formula inequalities do not require adopted physical response.'},{'source':'CO1','role':'Supplied weak tensor-wave/measurement and full-domain interpretation; not an extra lemma needed for the self-contained norm proofs.'},{'source':'CO2','role':'Required numerical input provenance for the included nominal matrix/delay illustrations; independent scalar recomputation reuses the exact saved design output.'},{'source':'FW1/FW2','role':'Exposed finite-cyclic/static control and historical practical-stop context, not inputs to the mathematical proofs.'}],
methods_or_controls_not_separate_physical_premises=['Hilbert geometry, triangle/Cauchy-Schwarz inequalities, analytic exponential-polynomial/Vandermonde argument, Fourier Plancherel and elementary characteristic-function/Taylor bounds.','Conventional physical apparatus response, weak-plane regime, sky/time conventions and calibration are supplied comparison assumptions, not metric-derived detector laws.'],
excluded_inferences=['No finite-sample left inverse on the unrestricted infinite-dimensional waveform space follows from three-by-two static rank.','No actual finite-arm/rotating/filtered/cleaned flight-product surjectivity or fit of arbitrary records inside a weak norm ball.','No quantitative physical norm cap or actual target sensitivity is supplied.','Marginal one-sigma curves do not supply hard envelopes, complete covariance or simultaneous coverage.','Arm-only error is not complete calibration/cleaning/rotation/astrometry/support/noise control.','No source selection, new observation, data-unsealing, event result, generic GW/UDT no-go, or physical adoption.'],
retained_practical_disposition='RD2 NOT CLEARED: examined work has no supported complete target-level response/support coefficient, waveform-size bound and joint noise allowance. This evidence/design stop remains; it does not block the completed conditional mathematics or claim no adequate future design can exist.',
review_and_repair_history=['Fresh original source-first reviewer /root/rd1_response_review, exact runtime model UNKNOWN; distinct stdlib Fraction/scalar quadrature/elimination implementations.','Author received reviewer domain cautions, training-bound/nonvacuity refinements and arm-integral contributions before candidate freeze; sections2/5 explicitly disclose collaboration. Sections3/4 were first target-exposed and separately checked.','Initial and final verdicts VERIFIED-WITH-CAVEATS, no scientific repair; practical RD2 gate remained closed.','Five invalid producer assertions actually rerun, four in-memory formula mutants caught; same-code regressions distinct from independent arguments.','Packaging-only git-thread resource failure and mistaken no-index whitespace-exit assumption retained with corrected helper; ten original EOF whitespace exceptions are preserved.','Old primary-document fetch failures and source-comment/caller convention discrepancy remain disclosed; no flight-data bug or 2017 deployment equivalence inferred.','Present original four reviewer scripts all replay byte-identically; arm script source pins passed. Two exact public C source definitions now preserved with authorized path-only portable replay, without source-science change.'],
controlling_artifacts=artifacts('udt_gw_response_robustness_design_campaign',{'candidate':['step_01/CANDIDATE.md'],'review':['step_01/review/SOURCE_FIRST_SEAL.md','step_01/review/INDEPENDENT_SOURCE_NOTES.md','step_01/review/TRAINING_BOUND_NOTE.md','step_01/review/INITIAL_REVIEW.md','step_01/review/FINAL_REVIEW.md','step_01/review/REVIEW_RESULT.json','step_01/review/PACKAGING_REVIEW.md'],'source_ledger':['SOURCE_LEDGER.md'],'saved_result':['step_01/checks_run.stdout']}),
replay_labels=['rd1_definitions','rd1_target','rd1_arm','rd1_regression','rd1_portable'],unresolved_scientific_objections=[],current_gr_filter_qualification=qual)
(D/'ADDITIONAL_READINESS.json').write_text(json.dumps(dict(review_kind='Source-fidelity/readiness with original unchanged-code replays',runtime_model_version='UNATTESTED',candidates=[recipe,rd]),indent=2)+'\n')
# Parent-confirmed role separation: a method link or independently verified datum credit is not a logical result dependency.
p=D/'CORE_READINESS.json';core=json.loads(p.read_text())
for x in core['candidates']:
 if x['candidate']=='SE1':
  x['required_candidate_dependencies']=['LE1'];x['attributed_candidate_method_sources']=[{'candidate':'NR2','role':'Analytic Cauchy development method interface only; tangent iff and fixed sector not imported.'}]
 if x['candidate']=='NE1':
  x['required_candidate_dependencies']=[];x['attributed_candidate_datum_sources']=[{'candidate':'SE1','role':'Initial-data provenance; NE1 verifies its own explicit metric, constraints and exact development.'}]
p.write_text(json.dumps(core,indent=2)+'\n')
print('Additional2 ready; parent-confirmed role separation saved.')
