#!/usr/bin/env python3
"""Build the preregistered post-July mass-branch reconciliation tables."""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent

SOURCES = [
    ("A01", "CURRENT_SCIENTIFIC_PREMISES.tsv", "current premise authority"),
    ("A02", "P4_ARC_SUMMARY_2026-07-31.md", "P4 package and scope index"),
    ("A03", "udt_p4_routeA_slice2b_full_cell_2026-07-29/AUDIT_REPORT.md", "mass-reading and census atlas"),
    ("A04", "udt_p4_bookkeeping_forcing_2026-07-29/AUDIT_REPORT.md", "constants/fields census fork"),
    ("A05", "udt_p4_gradient_seat_2026-07-29/AUDIT_REPORT.md", "F02 landing and mass readings"),
    ("A06", "udt_p4_angular_completion_2026-07-30/AUDIT_REPORT.md", "F02 completion cut"),
    ("A07", "udt_p4_period_gate_2026-07-30/AUDIT_REPORT.md", "global completion branches"),
    ("A08", "udt_p4_stability_slice_2026-07-30/AUDIT_REPORT.md", "F01/F02 sector Hessians"),
    ("A09", "udt_p4_timelive_stage_T1_2026-07-31/AUDIT_REPORT.md", "bounded everything-on time posing"),
    ("A10", "udt_p4_timelive_stage_T3_2026-07-31/AUDIT_REPORT.md", "time branch and mass compatibility"),
    ("A11", "udt_p4_angular_stage_A3_2026-07-31/AUDIT_REPORT.md", "angular-live census"),
    ("A12", "native_hopfion_topology_audit_2026-07-19/AUDIT_REPORT.md", "F04 carrier/topology/stability scope"),
    ("A13", "udt_stability_family_survivor_map_2026-08-01/AUDIT_REPORT.md", "seven-label survivor map"),
    ("A14", "udt_stability_family_ontology_audit_2026-08-01/AUDIT_REPORT.md", "corrected object ontology"),
    ("A15", "udt_stability_derivation_closure_sweep_2026-08-01/AUDIT_REPORT.md", "upstream missing-law sweep"),
    ("A16", "udt_native_stability_configuration_space_audit_2026-08-01/AUDIT_REPORT.md", "native parent arena and realization gate"),
    ("A17", "udt_f01_lambda_schur_check_2026-08-01/AUDIT_REPORT.md", "current F01 local index correction"),
    ("A18", "udt_stability_action_boundary_bridge_audit_2026-08-01/AUDIT_REPORT.md", "action/boundary bridge status"),
    ("A19", "udt_f01_second_wall_inverse_stability_2026-08-01/AUDIT_REPORT.md", "conditional F01 inverse surface"),
    ("A20", "udt_p4_cold_adversarial_review_2026-08-01/AUDIT_REPORT.md", "P4 common-realization caveat"),
]

FAMILY_FIELDS = [
    "family_id", "object_kind", "realization_status", "mass_or_energy_reading",
    "variation_census", "completion_boundary", "stability_status",
    "time_angular_status", "carrier_action_status", "effect_of_more_structure",
    "maximum_claim", "open_gate", "source_basis",
]

FAMILIES = [
    ["F01", "CONDITIONAL_REALIZED_P4_CONSTANTS_FAMILY", "CONDITIONAL_NONEMPTY",
     "FOUR_LABELED_CANDIDATE_MASS_READINGS_NONZERO_ON_INTEGRATED_I_P_ZERO_E0_NONZERO_BRANCH__NONE_PROMOTED",
     "CONSTANTS_CENSUS__INTEGRATED_MODULI_ROWS__POINTWISE_ROWS_KILL_NONZERO_BRANCH",
     "MIXED_CREASE_GLUE_CERTIFIED__DOUBLE_CREASE_AND_CYCLIC_N1_EMPTY__PHYSICAL_BOUNDARY_OPEN",
     "ALL_FOUR_OWNED_LOCAL_JOINT_INDICES_ONE_UNDER_GERM_FLAT__RESTRICTED_TWO_RESPONSE_NONNEGATIVE_REGION_EXISTS_CONDITIONALLY",
     "FORMAL_TIME_ANGULAR_COMPATIBILITY__NO_COMMON_NONZERO_ONSHELL_OBJECT",
     "METRIC_GEOMETRY_WITH_CONDITIONAL_P4_RESPONSE__NO_CARRIER_ADOPTED",
     "MORE_VARIATION_DESTROYS_POINTWISE_BRANCH_AND_RESTORED_MU_DESTROYS_POSITIVE_FIELD_SLICE__TWO_WALL_RESPONSES_CAN_CONDITIONALLY_REPAIR_RESTRICTED_FORM",
     "CONDITIONAL_GEOMETRIC_MASS_BEARING_BRANCH",
     "NATIVE_VARIATION_RESPONSE_PHYSICAL_BOUNDARY_COMPLETE_WALL_HESSIAN_TIME_BOOTSTRAP",
     "A02;A03;A04;A07;A08;A09;A10;A11;A13;A14;A16;A17;A18;A19;A20"],
    ["F02", "CONDITIONAL_REALIZED_P4_FIELDS_FAMILY", "CONDITIONAL_LANDING_TYPED_NOT_EXHAUSTED",
     "M_GEN_M_DENS_COORD_M_DENS_PROPER_EQUAL_2_ELL_E0_AND_NONZERO_GENERICALLY__M_WALL_ZERO_DISSENTS__NONE_PROMOTED",
     "FIELDS_CENSUS__P1_4D_LOCKED_LANDING__P_ZERO_F_H_AFFINE_LAMBDA_ZERO__FULL_CONDITION_STACK_REQUIRED",
     "ACYCLIC_BRANCH_UNTOUCHED_CONDITIONALLY__CYCLIC_OR_TYPED_FOLD_CAN_FORCE_MASSLESS__PHYSICAL_COMPLETION_OPEN",
     "NO_M_JET_UNSTABLE_FOR_E0_NONZERO__JET_QUADRATIC_SECTOR_NONNEGATIVE_IFF_64_E0_SQ_ELL_4_LE_G_P_C_M_PI_4__NO_FULL_CERTIFICATE",
     "FORMAL_TIME_ANGULAR_MODULES__COMMON_FIXED_ONSHELL_REALIZATION_OPEN",
     "METRIC_GEOMETRY_WITH_CONDITIONAL_P4_RESPONSE__NO_CARRIER_ADOPTED",
     "ADDING_JET_STIFFNESS_CAN_REPAIR_THE_TESTED_SECTOR__ADDING_CYCLIC_OR_FOLD_COMPLETION_CAN_KILL_THE_MASS_BRANCH",
     "CONDITIONAL_GEOMETRIC_MASS_BEARING_LANDING_WITH_SECTOR_DICHOTOMY",
     "SELECTED_CENSUS_FULL_RESPONSE_FIXED_REALIZATION_BOUNDARY_TIME_BOOTSTRAP",
     "A02;A04;A05;A06;A07;A08;A11;A13;A14;A15;A16;A20"],
    ["F03", "CONTROL_STRATUM_NOT_FAMILY", "PRESENT_CONTROL_UNION",
     "ZERO_CANDIDATE_MASS_READINGS_ON_E0_ZERO_CONTROLS",
     "MULTIPLE_CONTROL_COMPONENTS_NOT_ONE_SOLUTION_FAMILY",
     "CONTROL_DOMAINS_ONLY", "PSD_DEGENERATE_NOT_ISOLATED",
     "NOT_PROMOTED", "CONDITIONAL_P4_CONTROL", "RETAINS_FLAT_DIRECTIONS",
     "MASSLESS_REGRESSION_CONTROL_ONLY", "NOT_A_NATIVE_BASIN_TARGET", "A08;A13;A14;A16"],
    ["F04", "CONDITIONAL_REALIZED_HOPFION_MODEL_FAMILY", "OBSERVED_STATIC_FINITE_BOX_CARRIER_CONDITIONAL",
     "NONZERO_CONDITIONAL_STATIC_ENERGY__NO_NATIVE_UDT_MASS_ASSIGNMENT",
     "ROUND_S2_CARRIER_FIELD_ON_FINITE_CARTESIAN_BOX__SEPARATE_FROM_P4_CENSUSES",
     "COMPUTATIONAL_FIXED_BOUNDARY__PHYSICAL_FINITE_CELL_BOUNDARY_OPEN",
     "SETTLED_STATIC_FINITE_BOX_CONDITIONAL__TIME_PERSISTENCE_OPEN",
     "NO_NATIVE_TIME_EQUATION_OR_TOPOLOGY_PROPAGATION_THEOREM",
     "S2_POSIT__L2_PLUS_L4_CONDITIONAL__CARRIER_EMERGENCE_OPEN",
     "TURNING_ON_THE_POSITED_CARRIER_ACTION_CREATES_THE_CONDITIONAL_ENERGY_LANDSCAPE__IT_IS_NOT_A_METRIC_ONLY_BRANCH",
     "CONDITIONAL_ENERGY_BEARING_STATIC_MODEL_NOT_NATIVE_MASS",
     "CARRIER_MAP_NATIVE_ACTION_PHYSICAL_BOUNDARY_TIME_BOOTSTRAP",
     "A01;A12;A13;A14;A15;A16"],
    ["F05", "STRUCTURAL_COMPLETION_CLASS_NOT_FAMILY", "CROSS_CUTTING_CLASSIFIER",
     "MASSLESS_CONSTANT_RINGS_EXIST__MASS_BEARING_COMPLETIONS_ONLY_CONDITIONAL_AND_BELONG_TO_UNDERLYING_P4_BRANCHES",
     "NO_OWN_RESPONSE_OR_VARIATION_DOMAIN", "ALL_DEFINITE_CYCLIC_FORCES_MASSLESS__MIXED_SIGN_OR_MIXED_POSTURE_CONDITIONAL",
     "NOT_STABILITY_TESTABLE_WITHOUT_NEW_RESPONSE", "NO_TIME_PERSISTENCE_OBJECT",
     "NO_SEPARATE_CARRIER_OR_ACTION", "GLOBAL_COMPLETION_CAN_KILL_OR_ADMIT_F01_F02_MEMBERS_BUT_DOES_NOT_CREATE_A_PEER_FAMILY",
     "COMPLETION_AND_MASS_CLASSIFICATION_ONLY", "REALIZED_PARENT_RESPONSE_PERTURBATION_DOMAIN", "A07;A13;A14;A15;A16"],
    ["F06", "EXACT_EMPTY_SCOPE_NOT_FAMILY", "EMPTY_IN_REGISTERED_SCOPES",
     "NO_MASS_BEARING_OBJECT_IN_CYCLIC_N1_OR_DOUBLE_CREASE_SCOPES", "MULTIPLE_SCOPED_NEGATIVES",
     "REGISTERED_EMPTY_COMPLETIONS", "NOT_APPLICABLE", "NOT_APPLICABLE", "CONDITIONAL_P4_NEGATIVE_SCOPES",
     "ADDED_COMPLETION_CONSTRAINTS_ELIMINATE_THE_NONZERO_BRANCH", "EXACT_SCOPED_NONEXISTENCE_ONLY",
     "REOPEN_IF_CONTROLLING_PREMISE_CHANGES", "A07;A08;A13;A14;A16"],
    ["F07", "FORMAL_MODULE_CLASS_NOT_FAMILY", "FORMAL_ONLY",
     "NO_REALIZED_MASS_OR_ENERGY_READING", "STATIC_TIME_ANGULAR_FORMAL_MODULES",
     "COMMON_COMPLETION_OPEN", "NO_STABILITY_OPERATOR_OR_FIXED_BACKGROUND",
     "FORMAL_COMPATIBILITY_ONLY__NO_COMMON_NONZERO_ONSHELL_OBJECT",
     "NO_COMPLETE_NATIVE_RESPONSE", "TURNING_ON_TIME_AND_ANGULAR_ROWS_WITHIN_THEIR_REGISTERED_LAYERS_PRESERVES_FORMAL_ARCHITECTURE_BUT_DOES_NOT_CREATE_A_SOLUTION",
     "MISSING_JOIN_LOCATOR_ONLY", "COMMON_FIELD_EQUATION_BOUNDARY_TANGENT_DOMAIN", "A09;A10;A11;A13;A14;A15;A16;A20"],
]

MECHANISM_FIELDS = [
    "axis_id", "bounded_layer", "structure_state", "affected_objects", "exact_effect",
    "selection_status", "source_basis",
]

MECHANISMS = [
    ["M01", "P4_QUADRATIC_STATIC_RESPONSE", "INTEGRATED_MODULI_ROWS", "F01",
     "ADMITS_I_P_ZERO_E0_NONZERO_BRANCH_WITH_ALL_FOUR_LABELED_MASS_READINGS_NONZERO",
     "CENSUS_FORK_OPEN", "A03;A04"],
    ["M02", "P4_QUADRATIC_STATIC_RESPONSE", "POINTWISE_MODULI_ROWS", "F01",
     "FORCES_E0_ZERO_AND_REMOVES_THE_F01_NONZERO_BRANCH", "CENSUS_FORK_OPEN", "A03;A04"],
    ["M03", "P4_FIELD_MODULI", "P1_4D_LOCKED_AFFINE_LANDING", "F02",
     "ADMITS_GENERIC_E0_NONZERO_WITH_THREE_AGREEING_CANDIDATE_READINGS_AND_ZERO_WALL_READING",
     "CONDITIONAL_FULL_CUTTING_CONDITIONS", "A05"],
    ["M04", "P4_FIELD_MODULI_STABILITY", "NO_M_JET", "F02",
     "EXACT_UNSTABLE_WITNESS_FOR_E0_NONZERO", "CONDITIONAL_SECTOR", "A08"],
    ["M05", "P4_FIELD_MODULI_STABILITY", "JET_QUADRATIC_STIFFNESS", "F02",
     "SECTOR_NONNEGATIVE_IFF_64_E0_SQ_ELL_4_LE_G_P_C_M_PI_4",
     "COEFFICIENTS_AND_FULL_REALIZATION_NOT_SELECTED", "A08;A13"],
    ["M06", "F01_LOCAL_HESSIAN", "FREE_ANGULAR_WALL_TRACES_GERM_FLAT", "F01",
     "FIELD_BLOCK_HAS_INDEX_ONE_AND_POSITIVE_MODULUS_SCHUR_LEAVES_JOINT_INDEX_ONE",
     "SUPPLIED_CONDITIONAL_DOMAIN", "A08;A17"],
    ["M07", "F01_LOCAL_HESSIAN", "ODD_ZERO_ANGULAR_TRACES_GERM_FLAT", "F01",
     "REDUCED_FIELD_CORE_POSITIVE_BUT_RESTORED_MU_GIVES_NEGATIVE_JOINT_WITNESS_AND_INDEX_ONE",
     "SUPPLIED_CONDITIONAL_DOMAIN", "A08;A17"],
    ["M08", "F01_RESTRICTED_WALL_HESSIAN", "FINITE_ANGULAR_RESPONSE_TAU_PLUS_DIRECT_CURVATURE_ETA", "F01",
     "ABOVE_THE_FIELD_CROSSING_NONNEGATIVE_IFF_ETA_EXCEEDS_EXACT_THRESHOLD_IN_DECLARED_TWO_PARAMETER_SLICE",
     "RESPONSES_NOT_SELECTED_COMPLETE_HESSIAN_OPEN", "A19"],
    ["M09", "P4_GLOBAL_COMPLETION", "MIXED_CREASE_GLUE", "F01;F05",
     "CERTIFIES_A_CONDITIONAL_F01_MASS_BEARING_COMPLETION", "POSTURE_AND_PHYSICAL_BOUNDARY_NOT_SELECTED", "A07;A08"],
    ["M10", "P4_GLOBAL_COMPLETION", "DOUBLE_CREASE_OR_CYCLIC_N1", "F01;F06",
     "NONZERO_MASSIVE_SCOPE_EMPTY", "EXACT_SCOPED_NEGATIVE", "A07;A08"],
    ["M11", "P4_GLOBAL_COMPLETION", "ALL_DEFINITE_CYCLIC_VS_MIXED_SIGN", "F01;F02;F05",
     "ALL_DEFINITE_CYCLIC_FORCES_EACH_E0_ZERO__MIXED_SIGN_ESCAPE_REMAINS_CONDITIONAL",
     "COMPLETION_DATA_NOT_SELECTED", "A07;A15"],
    ["M12", "TIME_LIVE_T1_TO_T3", "EVERYTHING_ON_WITHIN_TIME_JET_LE_2_REGISTERED_LAYER", "F01;F02;F07",
     "STATIC_RESPONSE_ARCHITECTURE_EMBEDS_AND_MASSIVE_IMPLIES_NONUNIFORM_PROPER_PERIOD_ON_LOOP_BRANCH__NO_COMMON_ONSHELL_SOLUTION",
     "FORMAL_BOUNDED_LAYER_ONLY", "A09;A10;A20"],
    ["M13", "ANGULAR_LIVE_A1_TO_A3", "FULL_REGISTERED_SMOOTH_TORUS_TO_TWO_CAP_S3_CENSUS", "F01;F02;F07",
     "NO_SOLUTION_DEPENDENT_NATIVE_INTEGER_CUTS_E0_OR_MODULI__COMPLETION_JOIN_AND_ONSHELL_COEXISTENCE_OPEN",
     "FORMAL_BOUNDED_LAYER_ONLY", "A11;A20"],
    ["M14", "HOPFION_STATIC_MODEL", "ROUND_S2_PLUS_L2_L4_PLUS_FINITE_BOX", "F04",
     "SUPPLIES_NONZERO_STATIC_ENERGY_AND_CONDITIONAL_STATIC_STABILITY",
     "POSIT_AND_CONDITIONAL_NOT_METRIC_NATIVE", "A12;A14;A16"],
    ["M15", "ACTION_BOUNDARY_BRIDGE", "C2_BACH_OR_EH_OR_TWO_STAGE", "F01",
     "PARTIAL_ANALOGIES_ONLY_AND_ZERO_EXACT_F01_SECOND_WALL_GERM_MAPS",
     "C2_INACTIVE_WITHOUT_STRONG_CSN__EH_CONDITIONAL__BRIDGE_OPEN", "A01;A18"],
    ["M16", "GLOBAL_LOCAL_BOOTSTRAP", "WORKING_SCHEMA_NO_RETURN_MAP", "F01;F02;F04;F05;F07",
     "SELECTS_NO_FAMILY_RESPONSE_BOUNDARY_OR_MASS_VALUE", "WORKING_POSIT_OPERATION_OPEN", "A01;A15;A16"],
]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_tsv(path: Path, fields: list[str], rows: list[list[str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(fields)
        writer.writerows(rows)


def main() -> None:
    source_rows = []
    for source_id, relpath, role in SOURCES:
        data = (ROOT / relpath).read_bytes()
        source_rows.append([source_id, relpath, str(len(data)), sha256_bytes(data), role])
    write_tsv(OUT / "SOURCE_INVENTORY.tsv", ["source_id", "path", "bytes", "sha256", "role"], source_rows)
    write_tsv(OUT / "FAMILY_RECONCILIATION.tsv", FAMILY_FIELDS, FAMILIES)
    write_tsv(OUT / "MECHANISM_EFFECT_MATRIX.tsv", MECHANISM_FIELDS, MECHANISMS)

    source_identity = "\n".join("\t".join(row[:4]) for row in source_rows).encode()
    result = {
        "outcome": "MULTIPLE_CONDITIONAL_MASS_BEARING_ROUTES_RECONCILED__NO_NATIVE_STABLE_MASS",
        "family_rows": len(FAMILIES),
        "conditional_realized_family_rows": 3,
        "geometry_only_candidate_mass_routes": 2,
        "carrier_conditional_energy_routes": 1,
        "structural_completion_classes": 1,
        "exact_empty_scopes": 1,
        "formal_module_classes": 1,
        "control_strata": 1,
        "mechanism_rows": len(MECHANISMS),
        "source_rows": len(source_rows),
        "source_identity_sha256": sha256_bytes(source_identity),
        "native_realized_stable_families": 0,
        "newly_selected_mass_definitions": 0,
        "new_physics_objects": 0,
        "external_cold_review": "PASS_AFTER_REQUIRED_PRIORITY_WORDING_REPAIR__CLOSED",
        "maximum_conclusion": "VERIFIED_WITH_CAVEATS_BRANCH_AND_MECHANISM_RECONCILIATION_ONLY",
    }
    (OUT / "RESULT.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
