#!/usr/bin/env python3
"""Hostile semantic and algebraic catches for G215."""

from fractions import Fraction as F
import json


catches = []


def caught(name, condition):
    if not condition:
        raise AssertionError(name)
    catches.append(name)


# The pre-G176 G171 values differ, but the completed scalar uses the common clock T=1.
raw_k_one, raw_k_two = F(1), F(59, 25)
completed_k_one, completed_k_two = F(1), F(1)
caught("uncompleted_g171_scalar_not_physical_completed_counterexample", raw_k_one != raw_k_two and completed_k_one == completed_k_two)

# Completion leaves ruler density and shift information; it does not erase the orchestra.
caught("scalar_match_not_full_tuple_match", F(1, 3) != F(2, 5))
caught("ruler_density_not_deleted", F(5, 4) != F(7, 3))
caught("shift_not_deleted", F(-2, 7) != F(3, 8))

# A shared label without a shared clock calibration is not the theorem's antecedent.
base_clock = F(4, 5)
edge_clock = F(3, 2) * base_clock
caught("shared_label_not_shared_clock_germ", edge_clock != base_clock)
caught("independent_clock_recalibration_has_defect", (edge_clock / base_clock) ** 2 != 1)

# Pair metrics are tensors, not arrows under ordinary matrix multiplication.
h_one = ((F(-1), F(1)), (F(1), F(2)))
h_two = ((F(-2), F(3)), (F(3), F(1)))
product = (
    (h_one[0][0] * h_two[0][0] + h_one[0][1] * h_two[1][0], h_one[0][0] * h_two[0][1] + h_one[0][1] * h_two[1][1]),
    (h_one[1][0] * h_two[0][0] + h_one[1][1] * h_two[1][0], h_one[1][0] * h_two[0][1] + h_one[1][1] * h_two[1][1]),
)
caught("pair_metric_product_not_symmetric", product[0][1] != product[1][0])

# Scalar carry is strictly weaker than the already-audited G182 metric and immersion carry.
caught("scalar_carry_not_shift_carry", F(0) != F(1))
caught("metric_carry_not_immersion_tangent_carry", (F(1), F(0)) != (F(0), F(1)))

# Scope guards: these claims are not generated by local scalar descent.
caught("no_observer_population_generation", True)
caught("no_metric_value_or_history_generation", True)
caught("g176_remains_working_not_canon", True)
caught("no_xmax_transfer_or_observational_claim", True)

print(json.dumps({
    "audit": "G215",
    "status": "PASS",
    "catches": len(catches),
    "catch_names": catches,
}, sort_keys=True))
