#!/usr/bin/env python3
"""Seal completed direct fidelity only; actual full398 remains a separate gate."""
from pathlib import Path
import ast
import datetime
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[2]
BANK = ROOT/"udt_ncb1_banking_2026-09-12"
BASE = "fd6a28e6c9ee72b1d6e19e0c2e8d03c645e9a8e1"
def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()
def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT)
def require_calls(source):
    return [ast.dump(n, include_attributes=False) for n in ast.walk(ast.parse(source))
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id == "require"]
before = git("show", f"{BASE}:verify_current_scientific_premises.py").decode()
after = (ROOT/"verify_current_scientific_premises.py").read_text().replace("exactly 398 rows", "exactly 397 rows")
assert require_calls(before) == require_calls(after)
assert len(require_calls(before)) == 3560
head = git("rev-parse", "HEAD").decode().strip()
assert head == BASE and git("branch", "--show-current").strip() == b"grok"
freeze = json.loads((BANK/"ACCEPTANCE_FREEZE.json").read_text())
assert all(sha(ROOT/path) == expected for path, expected in freeze.items())
source_manifest = (BANK/"SOURCE_EVIDENCE_SHA256SUMS").read_text()
assert all(sha(ROOT/path) == expected for expected, path in
           [line.split("  ", 1) for line in source_manifest.splitlines()])
clarification = json.loads((BANK/"INDEX_CLARIFICATION.json").read_text())
current = (ROOT/"INDEX.md").read_text()
assert hashlib.sha256(current.encode()).hexdigest() == clarification["after_sha256"]
assert current.count(clarification["new"]) == 1
assert hashlib.sha256(current.replace(clarification["new"], clarification["old"], 1).encode()).hexdigest() == clarification["before_sha256"]
receipts = {}
for name, expected_exit in [("checks/initial_integration", 1), ("checks/repaired_integration", 0),
                            ("review/checks/source_authentication", 0), ("review/checks/independent_integration", 0)]:
    receipt = json.loads((BANK/(name+".json")).read_text())
    assert receipt["returncode"] == expected_exit and not receipt["timeout"]
    assert (BANK/(name+".stderr")).read_bytes() == b""
    receipts[name] = receipt
status = git("status", "--short").decode().splitlines()
launch = json.loads((BANK/"LAUNCH.json").read_text())
assert set(launch["original_untracked_status"]) <= set(status)
paths = set(freeze) | {
    "CURRENT_SCIENTIFIC_PREMISES.tsv", "verify_current_scientific_premises.py",
    "ncb1_banking_guard.py", "ti1_banking_guard.py", "ti2_banking_guard.py",
    "tests/test_ncb1_banking.py", "tests/test_ti1_banking.py", "tests/test_ti2_banking.py",
    "tests/test_startup_surface.py", "tests/test_reviewed_backlog_banking.py", "INDEX.md",
}
for path in BANK.rglob("*"):
    if path.is_file() and path.suffix != ".pyc" and path.name != "REVIEW_RECEIPT.json":
        # Only files already read or generated by this review are sealed here.
        if "review" in path.parts or path.name in {"ACCEPTANCE_FREEZE.json", "INDEX_CLARIFICATION.json"} or path.parent.name == "checks":
            if not path.name.startswith("direct_seal"):
                paths.add(str(path.relative_to(ROOT)))
report = {
    "utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    "reviewer": "/root/ncb1_banking_review", "head": head, "branch": "grok",
    "verdict": "VERIFIED_WITH_CAVEATS__EXACT_CONDITIONAL_BANKING_FIDELITY",
    "scientific_repairs_required": 0, "unresolved_direct_objections": [],
    "pending_gates": ["actual frozen-input current398 audit", "final documentation fidelity", "publication"],
    "reviewed_sha256": {name: sha(ROOT/name) for name in sorted(paths)},
    "existing_main_require_calls_preserved": 3560,
    "count_message_normalization_only": "exactly 398 rows -> exactly 397 rows for AST comparison",
    "captured_receipts_authenticated": receipts,
    "original_untracked_status_entries_present": 46,
    "original87_source_bytes_unchanged": True,
    "index_initial_failure_and_reverse_repair_authenticated": True,
    "independence": {"context": "fresh separate", "model_runtime": "UNATTESTED",
                     "implementation": "independent byte-injection harness; target guard code shared",
                     "argument": "source-exposed fidelity, original proof/verdicts supplied",
                     "different_model_library_human_formal_interval": "UNTESTED"},
    "new_scientific_program_runs": 0,
    "scope": "Complete original NCB1 (1)-(14) conditional mathematics only; no physical identification or canon",
    "parent_startup": "attributed WORK_ORDER/LAUNCH and original actual prebank full397 receipt",
    "resource_limit": "aggregate active review <=40 min; hard return20:25UTC; each check180s/2048MiB/one thread; no GPU",
    "protected_payloads": "NOT read/hashed", "reviewer_git_mutations": 0,
}
with (BANK/"review/REVIEW_RECEIPT.json").open("x") as f:
    json.dump(report, f, indent=2); f.write("\n")
print(json.dumps({"verdict": report["verdict"], "pins": len(paths),
                  "require_calls": 3560, "receipt_sha256": sha(BANK/"review/REVIEW_RECEIPT.json")}, indent=2))
