"""Save parent source-scope assessment; no scientific calculation or source mutation."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
HERE = Path(__file__).resolve().parent

def pin(path):
    return {'path': path, 'sha256': hashlib.sha256((ROOT/path).read_bytes()).hexdigest()}

def item(key, package, statement, assumptions, exclusions, sources, candidates, files, history, roles):
    return dict(id=key, package=package, statement=statement, assumptions=assumptions,
                exclusions=exclusions, required_source_ids=sources,
                required_candidate_ids=candidates, source_roles=roles,
                artifacts=[pin(package+'/'+f) for f in files], history=history,
                original_scientific_status='REVIEWED_CONDITIONAL_UNPROMOTED',
                banking_recommendation='ELIGIBLE_EXACT_SCOPE_PENDING_INTEGRATION_REVIEW',
                review_type='Parent full-source/readiness and unchanged-code reproduction; original separate-context reviews retained; no new independent reproof',
                banking_reviewer_model='UNATTESTED')

items = [
item('NCI1','udt_null_clock_depth_integrability_assessment_2026-09-10',
     'For a supplied smooth connected time-oriented Lorentzian four-domain and future unit U, one smooth endpoint scalar Psi reproduces delta=log(omega_B/omega_A) for EVERY sufficiently short regular future affine-null segment iff exp(-Psi)U is conformal Killing, iff sigma=0 and alpha=a_flat-(div U/3)U_flat is exact. Locally closed alpha suffices with zero shear; globally all periods must vanish. Psi is unique up to one additive constant. Static, conformal, flat shear and flat nonclosed-alpha controls retain their declared observer dependence.',
     ['All local null directions and short subsegments are included in the tested property, not physically populated by assumption','Smooth regular supplied (g,U), signature -+++; metric Levi-Civita geometry','Positive homogeneous scale-factor representatives; normalized clock slope, not raw affine slope'],
     ['No requirement that general UDT comparisons admit one endpoint scalar','No congruence/geometry/history selection, physical light identification, universal query realization or dynamical closure','Known geometric application; no mathematical novelty claim'],
     ['G176','G216','G217','G220'],[],
     ['INITIAL_CANDIDATE.md','REPAIR.md','DIRECT_REVIEW.md','SOURCE_REVIEW.md','SOURCE_MAP.md','DECISION_BRIEF.md','check_integrability.py','AUTHOR_CHECK_OUTPUT.txt'],
     ['One preserved domain/normalization wording repair; full focused review accepted; original proof and code unchanged. Source-review hash/read-list transcription repairs disclosed. Optional parenthesis cleanup is not an acceptance gate. Original G325 failure is historical.'],
     {'G176':'working completed-pair typing','G216/G217':'clock slope/jet typing','G220':'regular supplied null-clock query','G138/G247':'comparison/cycle semantics retained, not a new law','Dirmeier/Plaue/Scherfner':'credited classical method; direct complete proof is in frozen sources'}),
item('DCI1','udt_directional_clock_curvature_whiteboard_2026-09-10',
     'For any supplied smooth local Lorentzian four-metric and future unit congruence, the declared ideal all-direction normalized clock-slope record q(n), observer-time mean drift dot(m), and separately supplied A=div(a), W=w_ab*w^ab determine Ric(U,U)=3 dot(m)-3m^2-(15/2)V+A+W, where m=<q> and V is even-direction variance. Exact drift, acceleration-divergence, twist and shear metric witnesses defeat the stated reduced record maps. W>=0 gives only the stated one-sided implication when W is omitted; only A+W enters this target.',
     ['All-direction properly calibrated infinitesimal null queries; common rest-frame/units and smooth observer-time mean','Full spacetime acceleration divergence and full vorticity norm; stated curvature sign','Inverse record map excludes complete metric derivatives, incidence, path, travel-time and transport information'],
     ['No arbitrary-record realizability, full curvature/metric reconstruction or minimum-data theorem','Separately supplied motion channels are not proven instrument access or statistically independent measurements','Zero finite scalar depths on each own branch do not mean equal incidence or full kernel'],
     ['G220'],[],
     ['INITIAL_CANDIDATE.md','DATA_FREEZE.md','REPAIR.md','review/REVIEW.md','SOURCE_NOTES.md','DECISION_BRIEF.md','check_candidate.py','checks/AUTHOR_01_EXCLUSION.json'],
     ['Candidate unchanged. Original exit-zero static_time_constancy diagnostic was vacuous after t=0 substitution and remains EXCLUDED; corrected retained-t test and mutant were accepted in fresh focused R1 review. Known Raychaudhuri application.'],
     {'NCI1':'credited directional identity independently rederived; endpoint-potential criterion NOT required','G220':'regular null-clock slope','G215/G216/G333/G358':'typing/nonduplication comparisons, not field-law assumptions'}),
item('KTI1','udt_kernel_twist_information_audit_2026-09-10',
     'For the supplied stationary family g=-(dt+B)^2+dx^2+dy^2+dz^2, B=b(x dy-y dx)/2, U=partial_t, jointly marked coordinate-pair spatial first jets recover b=partial_x beta_y-partial_y beta_x and W=b^2/2, although completed scalar and each regular null depth vanish. Central pair values/all U-time jets and the explicitly restricted adapted h/V coefficient map do not recover W. Genuine individual pair immersions exist. Matched covariance differs from coordinate-query reselection; common smooth synchronization preserves curl, while point shift alone is not twist.',
     ['Declared local family, real b, jointly supplied chart/clock/ruler/orientation/calibration and transverse derivatives','G176 working completion; full retained pair h/shift prior to terminal scalar compression','Adapted h/V ambiguity excludes ambient E, coordinate J fields/derivatives, structure and transport; different ambient coframes remain different inputs'],
     ['No general-lapse/time-live/arbitrary-metric sufficiency theorem','No native family, physical pair population, acquisition protocol or selected scale','No orthogonal joint three-slice from noncommuting rest directions; no equality of null incidence/path domains'],
     ['G176','G179','G180','G182','G216','G220'],[],
     ['INITIAL_CANDIDATE.md','DATA_FREEZE.md','REPAIR_LOG.md','review/REVIEW.md','SOURCE_NOTES.md','DECISION_BRIEF.md','check_candidate.py'],
     ['Preserved initial ShapeError from a 3x3 instead of 3x1 zero control; one shape-only repair, candidate unchanged. Separate direct-metric review accepted. G179/NCI1 code reuse is declared, not independent evidence.'],
     {'DCI1':'credited antecedent twisting example, independently recomputed geometry; positive result does not require DCI1 curvature factorization','G179':'completed conditional evaluator','G180':'one-dimensional tape only','G182':'common ambient coframe condition'}),
item('ER1','udt_exact_metric_kernel_expansion_2026-09-10',
     'For supplied smooth local g=-N^2(dt+beta_i dx^i)^2+gamma_ij dx^i dx^j, N>0, gamma SPD, U=N^-1 partial_t, F_ij=partial_i beta_j-partial_j beta_i-beta_i partial_t beta_j+beta_j partial_t beta_i and W=N^2 gamma^ik gamma^jl F_ij F_kl/4. Six actual constant-direction pair surfaces with common comparison clock K=partial_t, retained T=N, m=N sqrt(gamma(v,v)), B=beta(v)/m and common first derivatives reconstruct the metric components/first jet and W. Common positive T/m, reconstructed SPD and three sum-shift equalities are necessary and sufficient ONLY for this smooth marked six-direction realization recipe. Exact coupled and density-omission witnesses and time-live tape coordinate/clock distinction are included.',
     ['Smooth actual record functions on one common marked neighborhood, six fixed directions ei and ei+ej; transverse/time derivatives and original ruler densities supplied','G166 unrestricted coframe envelope is not derived native UDT solution space; G176 remains working','Positive rest form gamma is not the coordinate t-slice metric','First-order comparison is shift-amplitude expansion about zero shift, not every linearization'],
     ['No native assembly, physical pair/calibration population, arbitrary-network inverse theorem or instrument acquisition','No field law, nonlinear dynamical development, global reach, genericity or persistence','Time-dependent tape determinant -1 does not preserve fixed-tape clock; unchanged K must be carried','Density-normalized outputs alone can agree while W changes; no physical scale selection'],
     ['G166','G176','G179','G180','G182','G216'],[],
     ['INITIAL_CANDIDATE.md','DATA_FREEZE.md','REPAIR_LOG.md','review/REVIEW.md','SOURCE_AND_FREEDOM_MAP.md','DECISION_BRIEF.md','check_exact_geometry.py'],
     ['No scientific repair. Original candidate and scientific outputs unchanged. Editorial stationarity/amplitude wording narrowed in brief; model attestation and pointer clarified. Documentation size/literal-guard failures and repairs preserved.'],
     {'KTI1':'credited stationary special case; full exact formula independently proved','G179':'completed evaluator','G180':'one-dimensional ruler integration; not time-live clock-grid theorem','G182':'Gram versus supplied ambient carry'}),
item('LC2','udt_local_clock_metric_benchmark_campaign_2026-09-07',
     'Frozen LC1 contract plus LC2 retrospective published-summary benchmark: one corrected downward gradient -12.4 +/-2.6 units (10^-19/cm), supplied g=9.803 m/s^2 and c_E=299792458 m/s give reference -10.907308499... and residual -1.492691500... units. Both declared descriptive one-standard-uncertainty bands include zero, with upper SD sqrt(2.6^2+0.1^2)=2.601922... (zero-covariance comparator) and 2.7 (arbitrary admissible cross-correlation). At supplied stationary/effective-linear/finite-cloud scope, upward d ln N/dh=(1.24 +/-0.26)*10^-16 m^-1; equivalent support acceleration is the SAME datum. Frozen sensitivity displacements and unrestricted-additive-bias nonidentifiability are included.',
     ['LC1 ENTIRE frozen comparison contract and input roles, including W4 WORKING physical-metric identification','One exposed published corrected gradient and total standard uncertainty; conventional atomic/laser/gravimeter/correction/geometry readout supplied','Centered adequate marginal-error model; Q covariance assumption is comparator only, C permits correlation not unbounded omitted bias','Rounded source inputs, fixed unit conversion, externally supplied reference; no calibration retuning'],
     ['Conditional published-summary benchmark, NOT derived empirical truth or new independent experiment','No hard error bounds, validated confidence coverage, p-value or uniquely UDT test','Not unrestricted pointwise metric jet, Earth/source solution, full history or global scale','Clock-inverted heights/second same-data analysis excluded; negative-half scenario is rounding-sensitive'],
     ['G261','G276'],[],
     ['step_01/COMPARISON_CONTRACT.md','step_01/INITIAL_COMPARISON_CONTRACT.md','step_01/INPUTS.json','step_01/review/INITIAL_REVIEW.md','step_01/review/FINAL_REVIEW.md','step_02/CANDIDATE_RESULT.md','step_02/review/INITIAL_REVIEW.md','step_02/review/FINAL_REVIEW.md','step_02/review/PACKAGING_FIDELITY.md','DECISION_BRIEF.md','step_02/evaluate_benchmark.py'],
     ['LC1 shifted-band decision-rule wording repair. LC2 original numerical result correct; four initial output-validator false passes preserved and one grouped check repair accepted. All result fields remain exact. Current author/focused/independent replays differ only in Python build metadata; preserved false-pass output byte-identical. Exact public source cache bytes additionally preserved in this banking package.'],
     {'LC1':'included frozen contract, not a separate second result/experiment','G261/W4':'working physical metric coupling, no instrument law derivation','G276':'ratios versus calibrated dimensional anchors','ORS2':'credited Killing identity independently reconstructed in original review; no route-ranking premise'})
]
items.append(item('FW2','udt_gw170817_fixed_window_test_campaign_2026-09-07',
     'Under the ENTIRE repaired FW1 frozen static cyclic finite operator, supplied CO2 design, twelve PSD-training and twenty-one reference offsource records, the repaired FW2 screen fails its declared sensitivity gate: at residual h_rss=1e-21 strain sqrt(second), strict crossings are 5/168,3/168,3/168 for the three frozen inclusive bands, versus required152/168. At the largest predeclared amplitude1e-19 each is8/168. The retained maximum Q=31313.959932... is Virgo-channel-dominated in this functional; its physical cause remains unidentified. Only a finite procedure result is accepted.',
     ['Exact FW1 R1 freeze, supplied resolution query, static/cyclic finite response and zero-DC/Nyquist domain','Exactly99 saved extracts on33 preselected offsource supports;12 training/21 threshold records,24 frozen synthetic realizations','Original PSD, cross terms, maximum threshold, PCG64 seeds, inclusive integer bins, real/imag draw order, core norm, window and stopping rule retained','Float64/complex128 finite numerical correspondence at the original documented relative tolerances, not exact arithmetic'],
     ['No event result, population power, confidence coverage or physical geometric constraint','No universal physical response retention, waveform/source law, UDT confirmation/refutation or instrument-wide exclusion','No deletion of extreme background, retuning, reopening event or new observations','No bound on better future statistics; exposed backgrounds stay exposed development data'],
     [],['CO1','CO2'],
     ['step_01/CANDIDATE.md','step_01/FREEZE.json','step_01/DISCOVERY_HISTORY.md','step_01/review/INITIAL_REVIEW.md','step_01/review/FINAL_REVIEW.md','step_02/CANDIDATE.md','step_02/review/INITIAL_REVIEW.md','step_02/review/FINAL_REVIEW.md','step_02/AUTHOR_REPAIR_READY.json','step_02/evaluation_R1_run.stdout','step_02/review/independent_replay.py','step_02/review/independent_operator.py','DECISION_BRIEF.md'],
     ['FW1 deterministic-generator/normalization/floor/relative-guard repair; FW2 float-frequency inclusive-bin defect corrected by integer membership. Initial4/168,3/168,4/168 counts superseded and preserved. Initial failed generators, review serialization/phase-accuracy failures, two overlapping killed author runs and CLI exit-zero UNPERFORMED review remain. Current replay reads only authenticated offsource extracts and preserved artifacts; no original HDF5/event samples opened.'],
     {'CO1':'conditional wave/finite response scope, not selected physical waveforms','CO2':'required supplied fixed design matrix/delays','FW1':'ENTIRE included frozen contract and review; not a second empirical result'}))

(HERE/'PARENT_CANDIDATES.json').write_text(json.dumps({'candidates':items},indent=2)+'\n')
print('Saved six parent-assessed result packages; LC1/LC2 one benchmark and FW1/FW2 one finite procedure result.')
