"""Render the reviewable banking packet from the frozen source transcription."""
from pathlib import Path
import csv
import io
import json

HERE=Path(__file__).resolve().parent
d=json.loads((HERE/'BANKED_CLAIMS.json').read_text())
lines=['# Reviewed backlog — exact-scope acceptance record','',
'DRAFT FOR INTEGRATION FIDELITY REVIEW. Source/readiness gates and the new prebank audit passed;',
'expanded-registry checks and fresh integration review remain pending. No acceptance is claimed',
'from this draft alone. Charles authorized promotion on 2026-09-10; see WORK_ORDER.md.','',
'## What is proposed for acceptance','',
'Thirty exact result entries, G383--G412: **27 conditional mathematical results**,',
'**one fixed-query design control** (G409=CO2), **one retrospective published-summary benchmark**',
'(G411=LC2, including the LC1 contract), and **one finite procedure result**',
'(G412=FW2, including the FW1 freeze). All remain VERIFIED-WITH-CAVEATS, OWNER_AUTHORIZED,',
'NOT_PHYSICAL_ADOPTION and NOT_CANON. The three distinct non-theorem categories are not silently',
'graded BANKED_DERIVED_CONDITIONAL. CP1 is this ledger\'s short alias for the original reviewed',
'constant-wave curvature/phase/current application; it is not a new scientific candidate.','',
'The ENTIRE original candidate, mathematical argument, data/freedom freeze, controlling review,',
'repair, exclusion and discovery history owns each claim. BANKED_CLAIMS.json pins those artifacts,',
'records exact quantifiers and distinguishes required accepted dependencies from rederived methods,',
'controls and source credit. BANKED_ROWS.tsv is the exact proposed addition, not a replacement',
'for the source arguments. A table, checklist, program or passing guard is not scientific proof.','',
'| Registry | Original result | Accepted object at its reviewed scope |',
'|---|---|---|']
for c in d['claims']:
    summary=c['statement'].split('. ')[0].replace('|','\\|')
    lines.append(f"| {c['premise_id']} | {c['id']} | {summary} |")
lines += ['', '## Authority, dependency closure and limits','',
'Current authority is G312 GR FILTER ONLY. DDR and Local Metric Sufficiency remain owner-provisional.',
'Every inherited Einstein/admitted/lawful/vacuum statement is CONDITIONAL on its full reviewed',
'equation/class premises; the filter does not establish response-class membership. Banking no more',
'adopts those equations than using a supplied geometry selects a physical universe. G166 native',
'mixed/time-live assembly remains OPEN and its unrestricted coframe envelope is not the derived',
'UDT solution space. G176 remains WORKING_FOUNDATIONAL_CLARIFICATION, not canon.','',
'Required new dependencies precede their users in the added sequence. In particular HB2 precedes',
'HB3, NR1 precedes NR2, LG1 precedes repaired LG2 and LE1, ND1 precedes ND2, QC1 precedes QC2,',
'GL1 precedes GL2, TM1 precedes TM2, and CO1/CO2 precede the included finite procedure result.',
'BI2/BI3 inherit already-banked BI1/G376. SE1 credits the NR2 analytic-development method without',
'importing its tangent-iff theorem; NE1 credits SE1 data provenance but independently supplies its',
'explicit metric/constraints. DCI1 rederives its directional identity, KTI1 independently recomputes',
'the twisting example, and ER1 proves its broader formula: their predecessor credit is not an',
'unproved new premise. GL2\'s included zero-coefficient metric control credits ND1 separately from',
'its positive necessity argument. RF1 does not inherit GL1\'s ambient-extension assumption.','',
'G353\'s original row and source explicitly left the initial curvature recipe separately unpromoted.',
'That historical dependency declaration remains byte-identical. G383 is the later standalone',
'acceptance of the exact original application, including its quotient measure/cut/scaling scope;',
'G355\'s broader root classification is not retroactively relabeled as having accepted all of it.','',
'Physical identification remains OPEN. No claim here chooses light, matter, mass, energy, a source',
'law, response coefficient, field history, observer/pair population, absolute scale or X_max.',
'No device/transfer assumptions become native UDT derivations. Small-domain, regularity, positivity,',
'symmetry, compactness, marking, calibration and equation conditions are substantive hypotheses.',
'Known geometry and standard PDE/linear-algebra methods remain credited applications; novelty and',
'familiar physical appearance are not acceptance criteria. Negative results retain their quantifiers.','',
'CO2 is a FLOAT64 design at one supplied nominal geometry, not an empirical null or uniform error',
'bound. LC2 uses one already exposed published gradient, not two experiments or a new blind test;',
'standard uncertainties are neither hard error bounds nor validated confidence intervals. FW2 is',
'one failed frozen offsource procedure, not population power, an event result, a metric constraint',
'or an instrument-wide rejection. Its reserved event remains unexamined; all33 backgrounds remain',
'exposed, including the extreme record. RD1\'s practical response/support gate remains uncleared.','',
'## Discovery, failed checks and review independence','',
'All original evidence is preserved, including initial candidates, failures, false passes, repairs,',
'excluded checks, lost-output qualifications and historical UNPROMOTED headers. The per-claim',
'history in BANKED_CLAIMS.json is part of the scope, not optional background. Examples include',
'LG2\'s exact source-covector repair; BI2/BI3 false-pass and full-tensor qualifications; NR1\'s',
'incomplete harmonic-support check; SE1\'s provenance correction/followup; QC1\'s excluded/vacuous',
'checks; GL1/RF1 parse/check repairs; DCI1\'s premature time substitution; KTI1\'s ShapeError;',
'ER1\'s wording/packaging repairs; LC1/LC2 band-rule/validator repairs; and FW2\'s inclusive-bin',
'repair with its original failed/overlapping executions. None is transformed into a historical pass.','',
'Original scientific separate-context reviews remain the substantive review evidence. Two NEW',
'complementary source/dependency contexts inspected the earlier full arguments and controlling',
'reviews; the parent checked the newer geometric applications and clock/finite-procedure returns.',
'One later fresh context reviews the banking transcription, dependency closure and integration.',
'Source-first exposure and actual allocation/overlap are recorded in the review reports and',
'SESSION_RECORD.md. A reused scientific program is a reproduction, not a new independent argument.',
'Configured parent gpt-6-astra/xhigh was observed earlier in this session; runtime model/version',
'is UNATTESTED. Different-model, human-specialist and formal-proof review remain UNTESTED.',
'No successful allocation is used to infer restored general capacity.','',
'## Actual checks and preservation','',
'New prebank full365: python3 verify_current_scientific_premises.py, exit0/PASS, empty stderr,',
'407.712643seconds, 105408KiB max RSS, 2GiB/900s caps. It started',
'2026-09-10T23:57:24.144105+00:00. checks/prebank_365.* owns the actual streams and capture',
'provenance. This is a new execution, not a rehearsal or source-reviewer rerun.','',
'Selected unchanged source programs recomputed the load-bearing algebra/geometry/benchmark or',
'finite procedure outputs; exact commands, environments, limits, stdout/stderr and correspondence',
'are in checks/ and the two source-review directories. Metadata-only Python build/date differences',
'are explicit; no blanket byte-identity claim is made. FW2\'s full saved-offsource replay is',
'byte-identical; no HDF5/event data were opened. Public source cache definitions used by the',
'historical reviews are copied with exact provenance where needed for reproducible banking.',
'Original scientific code is unchanged; no new field solve, fit or physical hypothesis was used.','',
'Baseline grok=origin/grok f5faabb43a582fec9a71c1d4a3b065efffae25bd was freshly fetched and',
'ff-only pulled before this task. Removing the30 additions must reproduce ALL365 original rows',
'byte-for-byte in their exact prior order and the original header. The new rows are prepended',
'in dependency order. SOURCE_EVIDENCE_SHA256SUMS pins the complete tracked original result packages',
'and specifically included review/source-cache evidence; it excludes protected/unrelated payloads.',
'Historical source-registry snapshots and the exact G312 authority transition are authenticated,',
'never waived or rewritten to impersonate current bytes.','',
'Original46 untracked status entries must retain fingerprint',
'55e7c4508622f912730f9c068cc571c370b3977bc1110eb0a48a8218dbe024c2.',
'Name/status preservation does not certify their payloads or backup completeness. Protected work',
'was not read, hashed, mined, staged or changed. No CANON or fixed through-G352 manuscript/coverage',
'change, runtime configuration change, history deletion, disk repair or archive access is included.',
'Backup completeness and pre-reboot unsaved-state disposition remain UNVERIFIED; ScratchDisk blocks',
'archive-dependent work only.','',
'The tracked-brief census is a bounded maintained-backlog check, not an exhaustive repository',
'science census. DISPOSITIONS.tsv distinguishes already-banked historical headings, the new entries,',
'document/route-control records, genuinely open product gates and excluded protected work.','',
'## Return and continuing discipline','',
'At every later authorized roadmap closeout, record one explicit disposition for each result:',
'bank at its demonstrated scope, hold for a NAMED missing gate, or retain as control/exploration.',
'A useful conditional result need not wait for physical identification, while review alone neither',
'promotes nor canonizes it. This banking task launches no successor campaign. Return to Charles',
'for lay discussion of an exact next question, with the conditional nonlinear-development line visible.','']
with (HERE/'BANKING_RECORD.md').open('x') as f:f.write('\n'.join(lines))

dispositions=[]
for c in d['claims']:
    dispositions.append([c['id'],c['premise_id'],'PROPOSED_EXACT_SCOPE_ACCEPTANCE',c['grade'],
                         c['artifacts'][0]['path'],'Source/readiness passed; final integration gates pending.'])
old=[('content_bridge','G353--G356'),('shared_readout_constraints','G357--G360'),
     ('phase_product_persistence','G361--G363'),('recipe_restrictiveness','G364--G366'),
     ('source_metric_connection','G367--G369'),('metric_source_reconstruction','G370--G371'),
     ('optional_coupled_development','G372--G373'),('vacuum_common_scale','G374--G375'),
     ('BI1_and_Berger_global_constraints','G376--G378'),('closed_fibres','G379--G380'),
     ('neighboring_tidal_consistency','G381--G382')]
for name,ids in old:
    dispositions.append([name,ids,'ALREADY_BANKED','EXISTING_EXACT_REGISTRY_GRADE',
                         'CURRENT_SCIENTIFIC_PREMISES.tsv','Historical UNPROMOTED headers do not revoke later acceptance; no duplicate entry.'])
for name,path,reason in [
    ('SC1','udt_shared_readout_metric_constraint_campaign_2026-09-06/DECISION_BRIEF.md','Source map retained as navigation/control, not a standalone derived claim.'),
    ('PE1','udt_goce_product_eligibility_audit_2026-09-07/DECISION_BRIEF.md','Reviewed documentary gate: deployed processor/configuration, calibration support and justified joint errors remain OPEN; no device certification.'),
    ('GOCE_documentation','udt_goce_documentation_followup_2026-09-07/DECISION_BRIEF.md','Documentation/enquiry draft retained; current enquiry remains UNSENT, product eligibility OPEN. Old await-reply language is historical.'),
    ('ORS1--ORS3','udt_observational_route_selection_campaign_2026-09-07/DECISION_BRIEF.md','Historical route-selection/source map; useful geometric/benchmark consequences are scoped in the accepted successors, not a current route endorsement.'),
    ('LC1','udt_local_clock_metric_benchmark_campaign_2026-09-07/step_01/COMPARISON_CONTRACT.md','Entire contract included under G411=LC2; not a second experiment or separate outcome.'),
    ('FW1','udt_gw170817_fixed_window_test_campaign_2026-09-07/step_01/CANDIDATE.md','Entire R1 finite freeze included under G412=FW2; no event or empirical-response gate cleared.'),
    ('RD2','udt_gw_response_robustness_design_campaign/DECISION_BRIEF.md','Never executed; practical support/response/error bridge remains uncleared. No promotion of a nonexistent result.'),
    ('protected_unbanked_work','AGENTS.md','Excluded: specific dispatch absent; payloads not inspected, reconstructed, hashed or promoted.'),
    ('fixed_manuscript_and_CANON','AGENTS.md','Fixed through-G352 edition and CANON unchanged; Charles has not authorized canon changes.')]:
    dispositions.append([name,'','RETAIN_DOCUMENT_CONTROL_OR_OPEN_GATE','NO_NEW_SCIENTIFIC_GRADE',path,reason])
with (HERE/'DISPOSITIONS.tsv').open('x',newline='') as f:
    w=csv.writer(f,delimiter='\t',lineterminator='\n');w.writerow(['item','registry_ids','disposition','category','source','reason_or_remaining_gate']);w.writerows(dispositions)
print('Wrote reviewable banking record and',len(dispositions),'dispositions.')
